import type { SlideData } from '../../types/presentation';
import { createExecutiveCloseContactSlide } from '../../utils/nextGenSlideFactories';
import {
  createEnterpriseCloudMigrationFunnelSlide,
  createZeroTrustIdentityPerimeterSlide,
  createAiDataFlywheelLifecycleSlide,
  createIncidentCommandWarRoomSlide,
  createRegulatoryGdprDataLineageSlide,
} from '../../utils/modern/transformationFactories';
import {
  createSaasUnitEconomicsBreakdownSlide,
  createGlobalFintechLedgerSettlementSlide,
  createMultiTenantDatabaseShardingSlide,
  createContinuousCompliancePostureSlide,
  createDeveloperPlatformCatalogMeshSlide,
} from '../../utils/modern/saasFinancialFactories';
import {
  createBoardroomMarketInflectionThesisSlide,
  createAsymmetricThreatDefenseMatrixSlide,
  createHardwareAcceleratorDieTopologySlide,
  createCustomerExperienceJourneyDeltaSlide,
  createExecutiveBoardMandateCtaSlide,
} from '../../utils/modern/boardroomStrategyFactories';
import {
  createNeuralVectorSearchTopologySlide,
  createModelQuantizationSpeculativeDecodingSlide,
  createCqrsEventSourcingFabricSlide,
  createPostMergerIntegrationRoadmapSlide,
  createCspmCiemCloudEntitlementGraphSlide,
  createConfidentialComputingEnclaveSlide,
  createPredictiveAutoscalingPodMatrixSlide,
  createCapexOpexCapitalAllocationSlide,
  createTransferPricingTaxTopologySlide,
  createSalesQuotaCompensationMatrixSlide,
  createExecutiveSuccessionLeadershipBenchSlide,
} from '../../utils/customizationSlideFactories';
import {
  createInteractiveBranchingCloseSlide,
  createBeforeAfterShowcasePanSlide,
  createSearchSerpProofLightboxSlide,
  createCognitiveInversionPunchlineSlide,
  createTalentPyramidFunnelSvgSlide,
  createHexagonalTechClusterSlide,
  createConnectedRoadmapRailPulseSlide,
  createCampaignPerformanceLightboxSlide,
  createExecutiveRosterKeypadSlide,
  createFlatStepProcessFlowSlide,
  createFlatSplitNarrativeStepperSlide,
  createFlatTimelineMilestoneRailSlide,
  createFlatRevealBentoGridSlide,
  createFlatDepthSentenceStackSlide,
  createFlatTypewriterCodeWalkthroughSlide,
} from '../../utils/flatGlobalSuiteFactories';
import {
  createExecutiveMandateScorecardSlide,
  createBoardQuorumResolutionLedgerSlide,
  createMacroEconomicThreatRadarSlide,
  createZeroTrustNetworkMeshSlide,
  createDistributedConsensusRaftLogSlide,
  createDataPipelineLineageDagSlide,
  createCodeWalkthroughSyntaxLensSlide,
  createTierComparisonFeatureMatrixSlide,
  createArrGrowthBridgeWaterfallSlide,
  createMultiTierSaasPackagingTableSlide,
  createFlywheelGrowthMomentumOrbitSlide,
  createEnterpriseCaseStudyHeroSlide,
  createClientWallSocialProofGridSlide,
  createIncidentRetrospectiveTimelineSlide,
  createInteractiveFaqTabbedDeckSlide,
  createAudienceDecisionForkMatrixSlide,
} from '../../utils/globalPptExpansionFactories';

export const deckSegmentModern: SlideData[] = [
  createExecutiveCloseContactSlide('slide-121'),
  createEnterpriseCloudMigrationFunnelSlide('slide-122'),
  createZeroTrustIdentityPerimeterSlide('slide-123'),
  createAiDataFlywheelLifecycleSlide('slide-124'),
  createIncidentCommandWarRoomSlide('slide-125'),
  createRegulatoryGdprDataLineageSlide('slide-126'),
  createSaasUnitEconomicsBreakdownSlide('slide-127'),
  createGlobalFintechLedgerSettlementSlide('slide-128'),
  createMultiTenantDatabaseShardingSlide('slide-129'),
  createContinuousCompliancePostureSlide('slide-130'),
  createDeveloperPlatformCatalogMeshSlide('slide-131'),
  createBoardroomMarketInflectionThesisSlide('slide-132'),
  createAsymmetricThreatDefenseMatrixSlide('slide-133'),
  createHardwareAcceleratorDieTopologySlide('slide-134'),
  createCustomerExperienceJourneyDeltaSlide('slide-135'),
  createExecutiveBoardMandateCtaSlide('slide-136'),
  createNeuralVectorSearchTopologySlide('slide-137'),
  createModelQuantizationSpeculativeDecodingSlide('slide-138'),
  createCqrsEventSourcingFabricSlide('slide-139'),
  createPostMergerIntegrationRoadmapSlide('slide-140'),
  createCspmCiemCloudEntitlementGraphSlide('slide-141'),
  createConfidentialComputingEnclaveSlide('slide-142'),
  createPredictiveAutoscalingPodMatrixSlide('slide-143'),
  createCapexOpexCapitalAllocationSlide('slide-144'),
  createTransferPricingTaxTopologySlide('slide-145'),
  createSalesQuotaCompensationMatrixSlide('slide-146'),
  createExecutiveSuccessionLeadershipBenchSlide('slide-147'),
  createInteractiveBranchingCloseSlide('slide-148'),
  createBeforeAfterShowcasePanSlide('slide-149'),
  createSearchSerpProofLightboxSlide('slide-150'),
  createCognitiveInversionPunchlineSlide('slide-151'),
  createTalentPyramidFunnelSvgSlide('slide-152'),
  createHexagonalTechClusterSlide('slide-153'),
  createConnectedRoadmapRailPulseSlide('slide-154'),
  createCampaignPerformanceLightboxSlide('slide-155'),
  createExecutiveRosterKeypadSlide('slide-156'),
  createFlatStepProcessFlowSlide('slide-157'),
  createFlatSplitNarrativeStepperSlide('slide-158'),
  createFlatTimelineMilestoneRailSlide('slide-159'),
  createFlatRevealBentoGridSlide('slide-160'),
  createFlatDepthSentenceStackSlide('slide-161'),
  createFlatTypewriterCodeWalkthroughSlide('slide-162'),
  createExecutiveMandateScorecardSlide('slide-163'),
  createBoardQuorumResolutionLedgerSlide('slide-164'),
  createMacroEconomicThreatRadarSlide('slide-165'),
  createZeroTrustNetworkMeshSlide('slide-166'),
  createDistributedConsensusRaftLogSlide('slide-167'),
  createDataPipelineLineageDagSlide('slide-168'),
  createCodeWalkthroughSyntaxLensSlide('slide-169'),
  createTierComparisonFeatureMatrixSlide('slide-170'),
  createArrGrowthBridgeWaterfallSlide('slide-171'),
  createMultiTierSaasPackagingTableSlide('slide-172'),
  createFlywheelGrowthMomentumOrbitSlide('slide-173'),
  createEnterpriseCaseStudyHeroSlide('slide-174'),
  createClientWallSocialProofGridSlide('slide-175'),
  createIncidentRetrospectiveTimelineSlide('slide-176'),
  createInteractiveFaqTabbedDeckSlide('slide-177'),
  createAudienceDecisionForkMatrixSlide('slide-178'),
];
