import type { SlideData } from '../../types/presentation';
import {
  createExecutivePnlWaterfallTableSlide,
  createCompetitiveFeatureHeatmapSlide,
  createCustomerPersonaArchetypeSplitSlide,
  createGlobalDataJurisdictionBoundarySlide,
  createHardwareInterfaceBlueprintSlide,
  createMultiHorizonValueRealizationBridgeSlide,
  createTwoSidedEcosystemFlywheelSlide,
  createIshikawaRootCauseFishboneSlide,
  createModularConsumptionPricingCalculatorSlide,
  createLiveProductViewportWalkthroughSlide,
  createEnterpriseRiskTaxonomyHeatmapSlide,
  createGlobalPartnerTieringLadderSlide,
  createTalentCompetencyGapHeatmapSlide,
  createSloErrorBudgetBurnWaterfallSlide,
  createWeightedDecisionTradeoffMatrixSlide,
  createCustomerChurnInterventionLadderSlide,
} from '../../utils/suite2026SlideFactories';
import {
  createAiInferenceCostTokenWaterfallSlide,
  createCrossFunctionalRaciMatrixSlide,
  createZeroTrustMicrosegmentationMapSlide,
  createSaasMagicNumberEfficiencyGaugeSlide,
  createSupplyChainGeopoliticalChokepointSlide,
  createIncidentSev1CommandTimelineSlide,
  createCloudFinopsUnitRateOptimizationSlide,
  createProductMarketFitCohortTrianglesSlide,
  createEnterpriseAiGovernanceGuardrailsSlide,
  createDataLakehouseMedallionPipelineSlide,
  createMergerAcquisitionSynergyBridgeSlide,
  createDeveloperProductivitySpaceFrameworkSlide,
  createHybridCloudDrFailoverTopologySlide,
  createCustomerHealthScorecardMatrixSlide,
  createValueStreamBottleneckFlowSlide,
} from '../../utils/suite2027SlideFactories';
import {
  createSyntheticDataCurationPipelineSlide,
  createCloudNativeWasmMicroserviceMeshSlide,
  createSovereignAiDatacenterPowerGridSlide,
  createAutonomousCodeSecurityPatchingLoopSlide,
  createCrossCloudMeshLatencyRoutingSlide,
  createEnterpriseGenaiAppObservabilitySlide,
  createZeroDowntimeSchemaEvolutionStepperSlide,
  createEnterpriseSoftwareSupplyChainChokepointSlide,
  createAiAgentMultiTurnOrchestrationDagSlide,
  createEnterpriseDataCleanRoomAuditSlide,
  createHyperscaleK8sCostAllocatorMatrixSlide,
  createCyberResilienceRansomwareReadinessRadarSlide,
  createSaasExpansionRetentionWaterfallGaugeSlide,
  createDeveloperExperienceFrictionIndexHeatmapSlide,
  createGeopoliticalSovereignCloudComplianceCompassSlide,
} from '../../utils/suite2028SlideFactories';
import { createSuite2029Slides } from '../../utils/suite2029SlideFactories';
import { createSuite2030Slides } from '../../utils/suite2030SlideFactories';
import { createSuite2031Slides } from '../../utils/suite2031SlideFactories';

export const deckSegmentSuites: SlideData[] = [
  createExecutivePnlWaterfallTableSlide('slide-229'),
  createCompetitiveFeatureHeatmapSlide('slide-230'),
  createCustomerPersonaArchetypeSplitSlide('slide-231'),
  createGlobalDataJurisdictionBoundarySlide('slide-232'),
  createHardwareInterfaceBlueprintSlide('slide-233'),
  createMultiHorizonValueRealizationBridgeSlide('slide-234'),
  createTwoSidedEcosystemFlywheelSlide('slide-235'),
  createIshikawaRootCauseFishboneSlide('slide-236'),
  createModularConsumptionPricingCalculatorSlide('slide-237'),
  createLiveProductViewportWalkthroughSlide('slide-238'),
  createEnterpriseRiskTaxonomyHeatmapSlide('slide-239'),
  createGlobalPartnerTieringLadderSlide('slide-240'),
  createTalentCompetencyGapHeatmapSlide('slide-241'),
  createSloErrorBudgetBurnWaterfallSlide('slide-242'),
  createWeightedDecisionTradeoffMatrixSlide('slide-243'),
  createCustomerChurnInterventionLadderSlide('slide-244'),
  createAiInferenceCostTokenWaterfallSlide('slide-245'),
  createCrossFunctionalRaciMatrixSlide('slide-246'),
  createZeroTrustMicrosegmentationMapSlide('slide-247'),
  createSaasMagicNumberEfficiencyGaugeSlide('slide-248'),
  createSupplyChainGeopoliticalChokepointSlide('slide-249'),
  createIncidentSev1CommandTimelineSlide('slide-250'),
  createCloudFinopsUnitRateOptimizationSlide('slide-251'),
  createProductMarketFitCohortTrianglesSlide('slide-252'),
  createEnterpriseAiGovernanceGuardrailsSlide('slide-253'),
  createDataLakehouseMedallionPipelineSlide('slide-254'),
  createMergerAcquisitionSynergyBridgeSlide('slide-255'),
  createDeveloperProductivitySpaceFrameworkSlide('slide-256'),
  createHybridCloudDrFailoverTopologySlide('slide-257'),
  createCustomerHealthScorecardMatrixSlide('slide-258'),
  createValueStreamBottleneckFlowSlide('slide-259'),
  createSyntheticDataCurationPipelineSlide('slide-260'),
  createCloudNativeWasmMicroserviceMeshSlide('slide-261'),
  createSovereignAiDatacenterPowerGridSlide('slide-262'),
  createAutonomousCodeSecurityPatchingLoopSlide('slide-263'),
  createCrossCloudMeshLatencyRoutingSlide('slide-264'),
  createEnterpriseGenaiAppObservabilitySlide('slide-265'),
  createZeroDowntimeSchemaEvolutionStepperSlide('slide-266'),
  createEnterpriseSoftwareSupplyChainChokepointSlide('slide-267'),
  createAiAgentMultiTurnOrchestrationDagSlide('slide-268'),
  createEnterpriseDataCleanRoomAuditSlide('slide-269'),
  createHyperscaleK8sCostAllocatorMatrixSlide('slide-270'),
  createCyberResilienceRansomwareReadinessRadarSlide('slide-271'),
  createSaasExpansionRetentionWaterfallGaugeSlide('slide-272'),
  createDeveloperExperienceFrictionIndexHeatmapSlide('slide-273'),
  createGeopoliticalSovereignCloudComplianceCompassSlide('slide-274'),
  ...createSuite2029Slides(275),
  ...createSuite2030Slides(290),
  ...createSuite2031Slides(305),
];
