import type { SlideData } from '../../types/presentation';
import {
  createTeamGridSlide,
  createCaseStudySlide,
  createQuoteCalloutSlide,
  createComparisonColumnsSlide,
  createCallToActionSlide,
} from '../../utils/slideArchetypeFactories';
import {
  createAuthenticityHookSlide,
  createAvoidCommoditySlide,
  createSwotAnalysisSlide,
  createCompetitorMatrixSlide,
  createExecutiveContactSlide,
} from '../../utils/expandedSlideFactories';
import {
  createExecutiveSummarySlide,
  createSystemArchitectureFlowSlide,
  createRoiMetricCalculatorSlide,
  createCustomerJourneyMapSlide,
  createMatrixComparisonGridSlide,
  createTechStackGridSlide,
  createTeamHierarchyOrgSlide,
  createSecurityComplianceMatrixSlide,
  createProductRoadmapTimelineSlide,
  createInteractiveFaqFlowSlide,
  createKeyMetricScorecardSlide,
  createCaseStudyImpactSlide,
  createDualColumnProsConsSlide,
  createInteractiveCodePlaygroundSlide,
  createClosingCtaShowcaseSlide,
  createTimelineRailSlide,
} from '../../utils/enterpriseSlideFactories';
import {
  createPersonalVpnSlide,
  createMeetingTranscriptSlide,
  createLlmBenchmarkSlide,
  createServicesGravitySlide,
  createSeoDominanceSlide,
  createStaffAugPipelineSlide,
  createCraftsmanshipBenchmarkSlide,
  createWeeklyCadenceSlide,
  createCompetitiveMoatSlide,
  createRapidFeedbackSlide,
  createInteractivePollSlide,
  createLiveQaSlide,
  createEmbedStageSlide,
  createCountdownLaunchSlide,
  createExecutiveTakeawaysSlide,
} from '../../utils/extendedSlideFactories';
import {
  createCodeDiffComparisonSlide,
  createGlobalCloudEdgeMeshSlide,
  createApiEndpointInspectorSlide,
  createDatabaseSchemaErdSlide,
  createSecurityThreatModelSlide,
  createAiAgentSwarmDagSlide,
  createFinancialBurnRunwaySlide,
  createBentoKpiMosaicSlide,
  createCanaryReleaseGaugeSlide,
  createIncidentRcaPostmortemSlide,
  createSlasAndUptimeStatusSlide,
  createAudioWaveformStudioSlide,
  createHardwareSiliconSpecSlide,
  createCohortRetentionHeatmapSlide,
  createVerifiableAuditLedgerSlide,
} from '../../utils/kineticSuiteSlideFactories';
import {
  createExecutiveGovernanceMatrixSlide,
  createOkrCascadeAlignmentSlide,
  createCloudCostFinopsOptimizerSlide as createCloudCostFinOpsOptimizerSlide,
  createCustomerSentimentRadarSlide,
} from '../../utils/globalPptSlideFactories';

export const deckSegmentEnterprise: SlideData[] = [
  createTeamGridSlide('slide-21'),
  createCaseStudySlide('slide-22'),
  createQuoteCalloutSlide('slide-23'),
  createComparisonColumnsSlide('slide-24'),
  createCallToActionSlide('slide-25'),
  createAuthenticityHookSlide('slide-26'),
  createAvoidCommoditySlide('slide-27'),
  createSwotAnalysisSlide('slide-28'),
  createCompetitorMatrixSlide('slide-29'),
  createExecutiveContactSlide('slide-30'),
  createExecutiveSummarySlide('slide-31'),
  createSystemArchitectureFlowSlide('slide-32'),
  createRoiMetricCalculatorSlide('slide-33'),
  createCustomerJourneyMapSlide('slide-34'),
  createMatrixComparisonGridSlide('slide-35'),
  createTechStackGridSlide('slide-36'),
  createTeamHierarchyOrgSlide('slide-37'),
  createSecurityComplianceMatrixSlide('slide-38'),
  createProductRoadmapTimelineSlide('slide-39'),
  createInteractiveFaqFlowSlide('slide-40'),
  createKeyMetricScorecardSlide('slide-41'),
  createCaseStudyImpactSlide('slide-42'),
  createDualColumnProsConsSlide('slide-43'),
  createInteractiveCodePlaygroundSlide('slide-44'),
  createClosingCtaShowcaseSlide('slide-45'),
  createTimelineRailSlide('slide-46'),
  createPersonalVpnSlide('slide-47'),
  createMeetingTranscriptSlide('slide-48'),
  createLlmBenchmarkSlide('slide-49'),
  createServicesGravitySlide('slide-50'),
  createSeoDominanceSlide('slide-51'),
  createStaffAugPipelineSlide('slide-52'),
  createCraftsmanshipBenchmarkSlide('slide-53'),
  createWeeklyCadenceSlide('slide-54'),
  createCompetitiveMoatSlide('slide-55'),
  createRapidFeedbackSlide('slide-56'),
  createInteractivePollSlide('slide-57'),
  createLiveQaSlide('slide-58'),
  createEmbedStageSlide('slide-59'),
  createCountdownLaunchSlide('slide-60'),
  createExecutiveTakeawaysSlide('slide-61'),
  createCodeDiffComparisonSlide('slide-62'),
  createGlobalCloudEdgeMeshSlide('slide-63'),
  createApiEndpointInspectorSlide('slide-64'),
  createDatabaseSchemaErdSlide('slide-65'),
  createSecurityThreatModelSlide('slide-66'),
  createAiAgentSwarmDagSlide('slide-67'),
  createFinancialBurnRunwaySlide('slide-68'),
  createBentoKpiMosaicSlide('slide-69'),
  createCanaryReleaseGaugeSlide('slide-70'),
  createIncidentRcaPostmortemSlide('slide-71'),
  createSlasAndUptimeStatusSlide('slide-72'),
  createAudioWaveformStudioSlide('slide-73'),
  createHardwareSiliconSpecSlide('slide-74'),
  createCohortRetentionHeatmapSlide('slide-75'),
  createVerifiableAuditLedgerSlide('slide-76'),
  createExecutiveGovernanceMatrixSlide('slide-77'),
  createOkrCascadeAlignmentSlide('slide-78'),
  createCloudCostFinOpsOptimizerSlide('slide-79'),
  createCustomerSentimentRadarSlide('slide-80'),
];
