import type { SlideData } from '../../types/presentation';
import {
  createGpuClusterFabricSlide,
  createRagNeedleHaystackSlide,
  createEbpfKernelTelemetrySlide,
  createSaasNetRevenueRetentionSlide,
  createBoardroomMaSynergySlide,
} from '../../utils/kineticRevolutionFactories';
import {
  createLlmAgenticWorkflowSlide,
  createZeroDowntimeBlueGreenSlide,
  createPostQuantumPqcKemSlide,
  createDeveloperPlatformBackstageSlide,
  createSoc2Type2EvidenceStreamSlide,
  createAiModelDistillationSlide,
  createExecutiveCompensationClawbackSlide,
  createEnterpriseLlmFineTuningSlide,
  createDistributedVectorIndexSlide,
  createRealtimeFinancialFraudSlide,
  createAutonomousCloudCostSlide,
  createLakehouseIcebergAcidSlide,
  createMultiRegionActiveActiveSlide,
  createSupplyChainCarbonCbamSlide,
  createChaosMeshNetworkPartitionSlide,
} from '../../utils/globalPptMasteryFactories';
import {
  createAgenticEvalRedTeamSlide,
  createGitOpsArgoCdSyncSlide,
  createNvmeFabricsRdmaSlide,
  createConfidentialGpuAttestSlide,
  createEbpfDdosXdpSlide,
  createActiveInferenceMemorySlide,
  createSovereignAiCleanRoomSlide,
  createIncidentCommandPlaybookSlide,
  createGpuHbmInterconnectSlide,
  createRealtimeFeatureStoreSlide,
  createDistributedWalRaftSlide,
  createFinopsUnitEconomicsSlide,
  createCrossBorderDataResidencySlide,
  createZeroTrustSpiffeSlide,
  createBoardCapitalAllocationSlide,
} from '../../utils/globalPptNextGenFactories';
import {
  createPqcMigrationFlowSlide,
  createAgentHierarchicalMemorySlide,
  createActiveActiveShardingSlide,
  createZeroTrustApiMeshSlide,
  createAutonomousVulnerabilityLoopSlide,
  createEdgeComputeOrchestratorSlide,
  createCloudFinopsLadderSlide,
  createBoardAiRiskOversightSlide,
  createSovereignQkdBackboneSlide,
  createAgentSwarmMemoryRegistrySlide,
  createHyperscaleShardingTopologySlide,
  createMicroservicesZeroTrustPolicySlide,
  createAutonomousSiemTriageSlide,
  createEdgeFleetDensitySlide,
  createBoardFiduciaryEsgHorizonSlide,
} from '../../utils/globalPptEvolutionFactories';

export const deckSegmentRevolutionMastery: SlideData[] = [
  createGpuClusterFabricSlide('slide-179'),
  createRagNeedleHaystackSlide('slide-180'),
  createEbpfKernelTelemetrySlide('slide-181'),
  createSaasNetRevenueRetentionSlide('slide-182'),
  createBoardroomMaSynergySlide('slide-183'),
  createLlmAgenticWorkflowSlide('slide-184'),
  createZeroDowntimeBlueGreenSlide('slide-185'),
  createPostQuantumPqcKemSlide('slide-186'),
  createDeveloperPlatformBackstageSlide('slide-187'),
  createSoc2Type2EvidenceStreamSlide('slide-188'),
  createAiModelDistillationSlide('slide-189'),
  createExecutiveCompensationClawbackSlide('slide-190'),
  createEnterpriseLlmFineTuningSlide('slide-191'),
  createDistributedVectorIndexSlide('slide-192'),
  createRealtimeFinancialFraudSlide('slide-193'),
  createAutonomousCloudCostSlide('slide-194'),
  createLakehouseIcebergAcidSlide('slide-195'),
  createMultiRegionActiveActiveSlide('slide-196'),
  createSupplyChainCarbonCbamSlide('slide-197'),
  createChaosMeshNetworkPartitionSlide('slide-198'),
  createAgenticEvalRedTeamSlide('slide-199'),
  createGitOpsArgoCdSyncSlide('slide-200'),
  createNvmeFabricsRdmaSlide('slide-201'),
  createConfidentialGpuAttestSlide('slide-202'),
  createEbpfDdosXdpSlide('slide-203'),
  createActiveInferenceMemorySlide('slide-204'),
  createSovereignAiCleanRoomSlide('slide-205'),
  createIncidentCommandPlaybookSlide('slide-206'),
  createGpuHbmInterconnectSlide('slide-207'),
  createRealtimeFeatureStoreSlide('slide-208'),
  createDistributedWalRaftSlide('slide-209'),
  createFinopsUnitEconomicsSlide('slide-210'),
  createCrossBorderDataResidencySlide('slide-211'),
  createZeroTrustSpiffeSlide('slide-212'),
  createBoardCapitalAllocationSlide('slide-213'),
  createPqcMigrationFlowSlide('slide-214'),
  createAgentHierarchicalMemorySlide('slide-215'),
  createActiveActiveShardingSlide('slide-216'),
  createZeroTrustApiMeshSlide('slide-217'),
  createAutonomousVulnerabilityLoopSlide('slide-218'),
  createEdgeComputeOrchestratorSlide('slide-219'),
  createCloudFinopsLadderSlide('slide-220'),
  createBoardAiRiskOversightSlide('slide-221'),
  createSovereignQkdBackboneSlide('slide-222'),
  createAgentSwarmMemoryRegistrySlide('slide-223'),
  createHyperscaleShardingTopologySlide('slide-224'),
  createMicroservicesZeroTrustPolicySlide('slide-225'),
  createAutonomousSiemTriageSlide('slide-226'),
  createEdgeFleetDensitySlide('slide-227'),
  createBoardFiduciaryEsgHorizonSlide('slide-228'),
];
