import type {
  ThreeHorizonsStrategySlideData,
  AiAgentFleetTopologySlideData,
} from '../../types/presentation';

// =============================================================================
// Archetype 01: Three Horizons Strategy Matrix (three-horizons-strategy-matrix)
// =============================================================================
export const createThreeHorizonsStrategySlide = (
  id = `slide-three-horizons-${Date.now()}`,
  overrides?: Partial<ThreeHorizonsStrategySlideData>
): ThreeHorizonsStrategySlideData => ({
  id,
  type: 'three-horizons-strategy-matrix',
  title: 'Three Horizons Strategic Growth Architecture',
  subtitle: 'Capital Allocation, Horizon Trajectories, and Stage-Gate Governance (FY26-30)',
  kicker: 'Strategic Capital Allocation',
  activeStep: 1,
  maxSteps: 3,
  portfolioSummary: {
    totalCapExMillionUsd: 420,
    projectedRoiMultiplier: 3.8,
    blendedGrowthRatePercent: 28.4,
    isPortfolioRebalanced: true,
    isReviewApproved: true,
  },
  executiveSignoff: {
    chiefStrategyOfficer: 'Alim Ul Karim, Chief Software Engineer',
    chiefSoftwareEngineer: 'Alim Ul Karim, Chief Software Engineer',
    reviewQuarter: 'Q4 FY2026',
    isApproved: true,
  },
  horizons: [
    {
      id: 'horizon-1',
      horizonNumber: 1,
      name: 'Defend & Extend Core',
      subtitle: 'Operational Cash Flow Engine',
      timeframeYears: '0 - 18 Months',
      targetCapitalAllocationPercent: 70,
      targetRevenuePercentage: 82,
      strategicFocus: 'Margin Optimization & Churn Mitigation',
      stageGateCriteria: 'Sustained >38% EBITDA Margin & 99.99% Core SLA',
      isHorizonActive: true,
      initiatives: [
        {
          id: 'init-h1-1',
          name: 'Split-DB Multi-Region Consolidation',
          leadOwner: 'Core Infrastructure Group',
          metricTarget: 'Reduce Operating COGS by $24M',
          currentValue: '$18.5M Achieved',
          isFunded: true,
          isMilestoneAchieved: true,
          riskProfile: 'LOW',
        },
        {
          id: 'init-h1-2',
          name: 'Enterprise Contract Renewal Automation',
          leadOwner: 'Customer Operations',
          metricTarget: 'Net Retention Rate > 124%',
          currentValue: '126.2% NRR',
          isFunded: true,
          isMilestoneAchieved: true,
          riskProfile: 'LOW',
        },
      ],
    },
    {
      id: 'horizon-2',
      horizonNumber: 2,
      name: 'Scale Emerging High-Velocity',
      subtitle: 'Adjacent High-Growth Vectors',
      timeframeYears: '18 - 36 Months',
      targetCapitalAllocationPercent: 20,
      targetRevenuePercentage: 15,
      strategicFocus: 'Rapid Market Capture & Customer Acquisition',
      stageGateCriteria: 'ARR Surpasses $75M with Net Margin Breakeven',
      isHorizonActive: false,
      initiatives: [
        {
          id: 'init-h2-1',
          name: 'Autonomous Model Context Gateway',
          leadOwner: 'AI Platform Group',
          metricTarget: '15,000 Connected Enterprise Nodes',
          currentValue: '4,200 Connected Nodes',
          isFunded: true,
          isMilestoneAchieved: false,
          riskProfile: 'BALANCED',
        },
      ],
    },
    {
      id: 'horizon-3',
      horizonNumber: 3,
      name: 'Seed Disruptive Paradigms',
      subtitle: 'Transformational Option Value',
      timeframeYears: '3 - 5 Years',
      targetCapitalAllocationPercent: 10,
      targetRevenuePercentage: 3,
      strategicFocus: 'Fundamental R&D & Autonomous Systems',
      stageGateCriteria: 'Defensible Patents & 10x Unit Economic Disruption',
      isHorizonActive: false,
      initiatives: [
        {
          id: 'init-h3-1',
          name: 'Sub-10ms Sovereign Neuro-Mesh',
          leadOwner: 'Deep Applied Research',
          metricTarget: 'Sub-5ms End-to-End Latency Benchmark',
          currentValue: '12ms Prototype',
          isFunded: true,
          isMilestoneAchieved: false,
          riskProfile: 'HIGH',
        },
      ],
    },
  ],
  ...overrides,
});

// =============================================================================
// Archetype 02: AI Agent Fleet Topology (ai-agent-fleet-topology)
// =============================================================================
export const createAiAgentFleetTopologySlide = (
  id = `slide-ai-fleet-${Date.now()}`,
  overrides?: Partial<AiAgentFleetTopologySlideData>
): AiAgentFleetTopologySlideData => ({
  id,
  type: 'ai-agent-fleet-topology',
  title: 'Autonomous AI Agent Fleet Topology',
  subtitle: 'Hierarchical Supervisor Controller, Distributed Dispatcher & Sandboxed Worker Swarms',
  kicker: 'Autonomous Multi-Agent Systems',
  activeStep: 1,
  maxSteps: 4,
  supervisor: {
    controllerId: 'sup-ctrl-core-01',
    modelFamily: 'Claude 3.5 Sonnet / Gemini Pro 1.5',
    contextWindowTokens: 1048576,
    currentTaskQueueDepth: 32,
    isOperational: true,
    isAutonomousDispatchEnabled: true,
  },
  governorMetrics: {
    tokenBudgetMaxMillion: 25.0,
    tokensConsumedMillion: 14.8,
    loopAnomalyCount: 0,
    hasBlockedUnsafeCalls: true,
    isComplianceEnforced: true,
  },
  liveTelemetry: {
    activeAgentsCount: 5,
    completedTasksCount: 184,
    p95TaskLatencySeconds: 4.2,
    isFleetSynchronized: true,
  },
  agentWorkers: [
    {
      id: 'agent-worker-01',
      name: 'Code Architect Agent',
      role: 'Surgical Code Synthesizer',
      specialization: 'TypeScript / React AST',
      status: 'EXECUTING',
      activeTokensUsed: 482000,
      taskSuccessRatePercent: 99.4,
      isHealthy: true,
      isSandboxIsolated: true,
      activeToolName: 'replace_file_content',
    },
    {
      id: 'agent-worker-02',
      name: 'Security Auditor Agent',
      role: 'Zero-Trust Policy Evaluator',
      specialization: 'Static Analysis & Secrets Gate',
      status: 'EXECUTING',
      activeTokensUsed: 290000,
      taskSuccessRatePercent: 100.0,
      isHealthy: true,
      isSandboxIsolated: true,
      activeToolName: 'run_linter_check',
    },
    {
      id: 'agent-worker-03',
      name: 'Deep Research Agent',
      role: 'Information Retrieval Specialist',
      specialization: 'Semantic Indexing & Web API',
      status: 'WAITING_IO',
      activeTokensUsed: 780000,
      taskSuccessRatePercent: 98.7,
      isHealthy: true,
      isSandboxIsolated: true,
      activeToolName: 'search_web',
    },
    {
      id: 'agent-worker-04',
      name: 'DevOps Deployer Agent',
      role: 'Hermetic Release Orchestrator',
      specialization: 'GitOps & Infrastructure As Code',
      status: 'IDLE',
      activeTokensUsed: 150000,
      taskSuccessRatePercent: 100.0,
      isHealthy: true,
      isSandboxIsolated: true,
      activeToolName: 'gitmap_deploy',
    },
    {
      id: 'agent-worker-05',
      name: 'QA Verification Agent',
      role: 'Continuous Assertion Engine',
      specialization: 'Evidence Ledger Verification',
      status: 'IDLE',
      activeTokensUsed: 340000,
      taskSuccessRatePercent: 100.0,
      isHealthy: true,
      isSandboxIsolated: true,
      activeToolName: 'verify_evidence_gate',
    },
  ],
  ...overrides,
});
