// lint-allow: file-size reason="Central keynote presentation deck definition with pre-seeded mastery archetypes" max=750
import { PresentationDeck } from '../types/presentation';
import {
  createMetricGridSlide, createProblemSolutionSlide, createQuadrantMatrixSlide,
  createMarketOpportunitySlide, createTimelineRoadmapSlide, createFeatureGridSlide,
  createArchitectureDiagramSlide, createQuoteCalloutSlide, createStatsCalloutSlide,
  createTeamGridSlide, createCaseStudySlide, createComparisonColumnsSlide,
  createProcessCycleSlide, createCodeTerminalSlide, createCallToActionSlide,
  createGrowthEngineSlide, createTalentPyramidSlide, createCostComparisonSlide,
  createDepthStackSlide, createRevealGridSlide, createBeforeAfterShowcaseSlide,
} from '../utils/slideArchetypeFactories';
import {
  createAuthenticityHookSlide, createAvoidCommoditySlide, createSwotAnalysisSlide,
  createCompetitorMatrixSlide, createExecutiveContactSlide,
} from '../utils/expandedSlideFactories';
import {
  createExecutiveSummarySlide, createSystemArchitectureFlowSlide, createRoiMetricCalculatorSlide,
  createCustomerJourneyMapSlide, createMatrixComparisonGridSlide, createTechStackGridSlide,
  createTeamHierarchyOrgSlide, createSecurityComplianceMatrixSlide, createProductRoadmapTimelineSlide,
  createInteractiveFaqFlowSlide, createKeyMetricScorecardSlide, createCaseStudyImpactSlide,
  createDualColumnProsConsSlide, createInteractiveCodePlaygroundSlide, createClosingCtaShowcaseSlide,
  createTimelineRailSlide,
} from '../utils/enterpriseSlideFactories';
import {
  createPersonalVpnSlide, createMeetingTranscriptSlide, createLlmBenchmarkSlide,
  createServicesGravitySlide, createSeoDominanceSlide, createStaffAugPipelineSlide,
  createCraftsmanshipBenchmarkSlide, createWeeklyCadenceSlide, createCompetitiveMoatSlide,
  createRapidFeedbackSlide, createInteractivePollSlide, createLiveQaSlide,
  createEmbedStageSlide, createCountdownLaunchSlide, createExecutiveTakeawaysSlide,
} from '../utils/extendedSlideFactories';
import {
  createCodeDiffComparisonSlide, createGlobalCloudEdgeMeshSlide, createApiEndpointInspectorSlide,
  createDatabaseSchemaErdSlide, createSecurityThreatModelSlide, createAiAgentSwarmDagSlide,
  createFinancialBurnRunwaySlide, createBentoKpiMosaicSlide, createCanaryReleaseGaugeSlide,
  createIncidentRcaPostmortemSlide, createSlasAndUptimeStatusSlide, createAudioWaveformStudioSlide,
  createHardwareSiliconSpecSlide, createCohortRetentionHeatmapSlide, createVerifiableAuditLedgerSlide,
} from '../utils/kineticSuiteSlideFactories';
import {
  createExecutiveGovernanceMatrixSlide, createOkrCascadeAlignmentSlide,
  createCloudCostFinopsOptimizerSlide as createCloudCostFinOpsOptimizerSlide,
  createCustomerSentimentRadarSlide, createCompetitiveBattlecardSlide,
  createLaunchReadinessChecklistSlide, createDeveloperGatewaySandboxSlide,
  createRagPipelineTopologySlide, createSocIncidentWarRoomSlide,
  createMerkleTreeStateLedgerSlide, createInvestorCapTableWaterfallSlide,
  createRealtimeEventStreamFabricSlide, createSupplyChainRiskMatrixSlide,
  createTalentCompetencyRadarSlide, createSustainabilityEsgScorecardSlide,
} from '../utils/globalPptSlideFactories';
import {
  createThreeHorizonsStrategySlide, createAiAgentFleetTopologySlide,
  createApiRateLimitGatewaySlide, createMultiCloudDrFailoverSlide,
  createFintechPaymentClearingSlide, createEsgDecarbonizationRoadmapSlide,
  createModelContextProtocolMeshSlide, createDataCleanRoomSlide,
  createDeveloperPlatformIdpSlide, createExecutiveMaSynergySlide,
  createCyberThreatKillChainSlide, createSupplyChainDigitalTwinSlide,
  createVoiceAiConversationalMeshSlide, createComplianceSoc2ReadinessLadderSlide,
  createValueStreamDoraFlywheelSlide,
  createExecutiveStorytellingHookSlide, createLeadershipSynergyDuoSlide,
  createOperationalWorkCultureSlide, createBentoCapabilitiesMatrixSlide,
  createOpportunityCostWaterfallSlide, createBenchmarkRegionalPricingSlide,
  createSprintOnboardingRoadmapSlide, createSimulatedBrowserShowcaseSlide,
  createClientTestimonialWallSlide, createGlobalEdgeMeshSlide,
  createAiGovernanceSafetyGovernorSlide, createDeveloperVelocityFlywheelSlide,
  createStrategicDecarbonizationEsgSlide, createMarketTensionQuadrantSlide,
  createExecutiveCloseContactSlide,
} from '../utils/nextGenSlideFactories';
import {
  createEnterpriseCloudMigrationFunnelSlide, createZeroTrustIdentityPerimeterSlide,
  createAiDataFlywheelLifecycleSlide, createIncidentCommandWarRoomSlide,
  createRegulatoryGdprDataLineageSlide,
} from '../utils/modern/transformationFactories';
import {
  createSaasUnitEconomicsBreakdownSlide, createGlobalFintechLedgerSettlementSlide,
  createMultiTenantDatabaseShardingSlide, createContinuousCompliancePostureSlide,
  createDeveloperPlatformCatalogMeshSlide,
} from '../utils/modern/saasFinancialFactories';
import {
  createBoardroomMarketInflectionThesisSlide, createAsymmetricThreatDefenseMatrixSlide,
  createHardwareAcceleratorDieTopologySlide, createCustomerExperienceJourneyDeltaSlide,
  createExecutiveBoardMandateCtaSlide,
} from '../utils/modern/boardroomStrategyFactories';
import { createModernSlide, MODERN_FACTORIES } from '../utils/modern/registry';
import {
  createNeuralVectorSearchTopologySlide,
  createModelQuantizationSpeculativeDecodingSlide,
  createCqrsEventSourcingFabricSlide,
  createPostMergerIntegrationRoadmapSlide,
  createCspmCiemCloudEntitlementGraphSlide,
  createConfidentialComputingEnclaveSlide,
  createPredictiveAutoscalingPodMatrixSlide,
  createCapexOpexCapitalAllocationSlide,
  createTransferPricingTaxTopologySlide,
  createSalesQuotaCompensationMatrixSlide,
  createExecutiveSuccessionLeadershipBenchSlide,
} from '../utils/customizationSlideFactories';
import {
  createInteractiveBranchingCloseSlide,
  createBeforeAfterShowcasePanSlide,
  createSearchSerpProofLightboxSlide,
  createCognitiveInversionPunchlineSlide,
  createTalentPyramidFunnelSvgSlide,
  createHexagonalTechClusterSlide,
  createConnectedRoadmapRailPulseSlide,
  createCampaignPerformanceLightboxSlide,
  createExecutiveRosterKeypadSlide,
  createFlatStepProcessFlowSlide,
  createFlatSplitNarrativeStepperSlide,
  createFlatTimelineMilestoneRailSlide,
  createFlatRevealBentoGridSlide,
  createFlatDepthSentenceStackSlide,
  createFlatTypewriterCodeWalkthroughSlide,
} from '../utils/flatGlobalSuiteFactories';
import {
  createExecutiveMandateScorecardSlide,
  createBoardQuorumResolutionLedgerSlide,
  createMacroEconomicThreatRadarSlide,
  createZeroTrustNetworkMeshSlide,
  createDistributedConsensusRaftLogSlide,
  createDataPipelineLineageDagSlide,
  createCodeWalkthroughSyntaxLensSlide,
  createTierComparisonFeatureMatrixSlide,
  createArrGrowthBridgeWaterfallSlide,
  createMultiTierSaasPackagingTableSlide,
  createFlywheelGrowthMomentumOrbitSlide,
  createEnterpriseCaseStudyHeroSlide,
  createClientWallSocialProofGridSlide,
  createIncidentRetrospectiveTimelineSlide,
  createInteractiveFaqTabbedDeckSlide,
  createAudienceDecisionForkMatrixSlide,
} from '../utils/globalPptExpansionFactories';
import {
  createGpuClusterFabricSlide,
  createRagNeedleHaystackSlide,
  createEbpfKernelTelemetrySlide,
  createSaasNetRevenueRetentionSlide,
  createBoardroomMaSynergySlide,
} from '../utils/kineticRevolutionFactories';
import {
  createLlmAgenticWorkflowSlide,
  createZeroDowntimeBlueGreenSlide,
  createPostQuantumPqcKemSlide,
  createDeveloperPlatformBackstageSlide,
  createSoc2Type2EvidenceStreamSlide,
  createAiModelDistillationSlide,
  createExecutiveCompensationClawbackSlide,
  createEnterpriseLlmFineTuningSlide,
  createDistributedVectorIndexSlide,
  createRealtimeFinancialFraudSlide,
  createAutonomousCloudCostSlide,
  createLakehouseIcebergAcidSlide,
  createMultiRegionActiveActiveSlide,
  createSupplyChainCarbonCbamSlide,
  createChaosMeshNetworkPartitionSlide,
} from '../utils/globalPptMasteryFactories';
import {
  createAgenticEvalRedTeamSlide,
  createGitOpsArgoCdSyncSlide,
  createNvmeFabricsRdmaSlide,
  createConfidentialGpuAttestSlide,
  createEbpfDdosXdpSlide,
  createActiveInferenceMemorySlide,
  createSovereignAiCleanRoomSlide,
  createIncidentCommandPlaybookSlide,
  createGpuHbmInterconnectSlide,
  createRealtimeFeatureStoreSlide,
  createDistributedWalRaftSlide,
  createFinopsUnitEconomicsSlide,
  createCrossBorderDataResidencySlide,
  createZeroTrustSpiffeSlide,
  createBoardCapitalAllocationSlide,
} from '../utils/globalPptNextGenFactories';
import {
  createPqcMigrationFlowSlide,
  createAgentHierarchicalMemorySlide,
  createActiveActiveShardingSlide,
  createZeroTrustApiMeshSlide,
  createAutonomousVulnerabilityLoopSlide,
  createEdgeComputeOrchestratorSlide,
  createCloudFinopsLadderSlide,
  createBoardAiRiskOversightSlide,
  createSovereignQkdBackboneSlide,
  createAgentSwarmMemoryRegistrySlide,
  createHyperscaleShardingTopologySlide,
  createMicroservicesZeroTrustPolicySlide,
  createAutonomousSiemTriageSlide,
  createEdgeFleetDensitySlide,
  createBoardFiduciaryEsgHorizonSlide,
} from '../utils/globalPptEvolutionFactories';
import {
  createExecutivePnlWaterfallTableSlide,
  createCompetitiveFeatureHeatmapSlide,
  createCustomerPersonaArchetypeSplitSlide,
  createGlobalDataJurisdictionBoundarySlide,
  createHardwareInterfaceBlueprintSlide,
  createMultiHorizonValueRealizationBridgeSlide,
  createTwoSidedEcosystemFlywheelSlide,
  createIshikawaRootCauseFishboneSlide,
  createModularConsumptionPricingCalculatorSlide,
  createLiveProductViewportWalkthroughSlide,
  createEnterpriseRiskTaxonomyHeatmapSlide,
  createGlobalPartnerTieringLadderSlide,
  createTalentCompetencyGapHeatmapSlide,
  createSloErrorBudgetBurnWaterfallSlide,
  createWeightedDecisionTradeoffMatrixSlide,
  createCustomerChurnInterventionLadderSlide,
} from '../utils/suite2026SlideFactories';
import {
  createAiInferenceCostTokenWaterfallSlide,
  createCrossFunctionalRaciMatrixSlide,
  createZeroTrustMicrosegmentationMapSlide,
  createSaasMagicNumberEfficiencyGaugeSlide,
  createSupplyChainGeopoliticalChokepointSlide,
  createIncidentSev1CommandTimelineSlide,
  createCloudFinopsUnitRateOptimizationSlide,
  createProductMarketFitCohortTrianglesSlide,
  createEnterpriseAiGovernanceGuardrailsSlide,
  createDataLakehouseMedallionPipelineSlide,
  createMergerAcquisitionSynergyBridgeSlide,
  createDeveloperProductivitySpaceFrameworkSlide,
  createHybridCloudDrFailoverTopologySlide,
  createCustomerHealthScorecardMatrixSlide,
  createValueStreamBottleneckFlowSlide,
} from '../utils/suite2027SlideFactories';
import {
  createSyntheticDataCurationPipelineSlide,
  createCloudNativeWasmMicroserviceMeshSlide,
  createSovereignAiDatacenterPowerGridSlide,
  createAutonomousCodeSecurityPatchingLoopSlide,
  createCrossCloudMeshLatencyRoutingSlide,
  createEnterpriseGenaiAppObservabilitySlide,
  createZeroDowntimeSchemaEvolutionStepperSlide,
  createEnterpriseSoftwareSupplyChainChokepointSlide,
  createAiAgentMultiTurnOrchestrationDagSlide,
  createEnterpriseDataCleanRoomAuditSlide,
  createHyperscaleK8sCostAllocatorMatrixSlide,
  createCyberResilienceRansomwareReadinessRadarSlide,
  createSaasExpansionRetentionWaterfallGaugeSlide,
  createDeveloperExperienceFrictionIndexHeatmapSlide,
  createGeopoliticalSovereignCloudComplianceCompassSlide,
} from '../utils/suite2028SlideFactories';
import { createSuite2029Slides } from '../utils/suite2029SlideFactories';
import { createSuite2030Slides } from '../utils/suite2030SlideFactories';

export const INITIAL_DECK: PresentationDeck = {
  id: 'white-presentation-v1',
  title: 'White Presentation System - Executive Keynote',
  version: '1.3.1',
  author: 'Riseup Asia Architectural Team',
  defaultThemeId: 'white-brand',
  canvas: {
    width: 1920,
    height: 1080,
    aspectRatio: '16:9',
  },
  slides: [
    {
      id: 'slide-01',
      type: 'white-master',
      title: 'Stories Are Emotional Bridges',
      headline: 'Stories Are Emotional Bridges',
      subtitle: 'Transform raw data and technical architecture into unforgettable enterprise impact.',
      kicker: 'STRATEGIC NARRATIVE',
      bulletPoints: [
        {
          id: 'bp-1',
          icon: 'heart',
          title: 'Emotional Resonance',
          description: 'Facts inform, but emotional connections drive multimillion-dollar decisions and leadership alignment.',
        },
        {
          id: 'bp-2',
          icon: 'users',
          title: 'Human-Centered Context',
          description: 'Bridge executive vision with operational reality through clear, empathetic engineering narratives.',
        },
        {
          id: 'bp-3',
          icon: 'chat',
          title: 'Catalyst for Action',
          description: 'A well-crafted story breaks through executive inertia, galvanizing teams toward swift execution.',
        },
      ],
      heroImage: {
        src: '/assets/screenshots/hero-speaker-clean.png',
        alt: 'Speaker sharing emotional narrative with audience',
        featherDirection: 'left',
      },
      neonGlow: {
        color: '#F43F5E',
        shape: 'heart',
        pulseRateSeconds: 2.2,
      },
      logo: {
        src: '/assets/logos/6 - Riseup Asia Logo Transparent Only BK.png',
        alt: 'Riseup Asia Logo',
        heightPx: 42,
      },
    },
    {
      id: 'slide-02',
      type: 'title',
      title: 'Autonomous Presentation Architecture',
      subtitle: 'The Next-Generation Declarative Slide Platform for High-Stakes Tech Keynotes',
      kicker: 'KEYNOTE PRESENTATION',
      presenter: {
        name: 'Alim Ul Karim',
        role: 'Chief Software Engineer',
        company: 'Riseup Asia LLC',
      },
      date: 'September 2026',
    },
    {
      id: 'slide-03',
      type: 'persona',
      title: 'Technical Leadership',
      name: 'Alim Ul Karim',
      role: 'Chief Software Engineer',
      quote: 'We engineer sovereign, high-leverage software architectures with zero defect tolerance.',
      avatarUrl: '/assets/screenshots/hero-speaker-clean.png',
      metrics: [
        { value: '15+ Yrs', label: 'Enterprise Systems' },
        { value: '40M+', label: 'Active End Users' },
      ],
      bioBullets: [
        'Direct architect of multi-tenant enterprise cloud systems across North America & Asia.',
        'Pioneer of deterministic AI workflows, autonomous loop orchestration, and zero-defect QA.',
        'Senior enterprise software consultant for scalable cloud architectures.',
      ],
    },
    createBeforeAfterShowcaseSlide('slide-04'),
    {
      id: 'slide-05',
      type: 'steps',
      title: 'Autonomous Delivery Lifecycle',
      kicker: 'AUTONOMOUS WORKFLOW',
      heading: 'Three phases, one week each',
      steps: [
        { label: 'Discover', title: 'Talk to 5 users', detail: 'Interview five real users. Extract architectural pain points and write specifications within 24 hours.' },
        { label: 'Prototype', title: 'One click, one screen', detail: 'Build the thinnest sovereign slice that solves the mission. Zero fluff, pure DOM performance.' },
        { label: 'Ship', title: 'Behind a flag', detail: 'Continuous production deployment every Friday. Immediate real-time validation across active teams.' },
      ],
    },
    createGrowthEngineSlide('slide-06'),
    createTalentPyramidSlide('slide-07'),
    createCostComparisonSlide('slide-08'),
    createMetricGridSlide('slide-09'),
    createProblemSolutionSlide('slide-10'),
    createQuadrantMatrixSlide('slide-11'),
    createMarketOpportunitySlide('slide-12'),
    createTimelineRoadmapSlide('slide-13'),
    createFeatureGridSlide('slide-14'),
    createArchitectureDiagramSlide('slide-15'),
    createDepthStackSlide('slide-16'),
    createRevealGridSlide('slide-17'),
    createProcessCycleSlide('slide-18'),
    createStatsCalloutSlide('slide-19'),
    createCodeTerminalSlide('slide-20'),
    createTeamGridSlide('slide-21'),
    createCaseStudySlide('slide-22'),
    createQuoteCalloutSlide('slide-23'),
    createComparisonColumnsSlide('slide-24'),
    createCallToActionSlide('slide-25'),
    createAuthenticityHookSlide('slide-26'),
    createAvoidCommoditySlide('slide-27'),
    createSwotAnalysisSlide('slide-28'),
    createCompetitorMatrixSlide('slide-29'),
    createExecutiveContactSlide('slide-30'),
    createExecutiveSummarySlide('slide-31'),
    createSystemArchitectureFlowSlide('slide-32'),
    createRoiMetricCalculatorSlide('slide-33'),
    createCustomerJourneyMapSlide('slide-34'),
    createMatrixComparisonGridSlide('slide-35'),
    createTechStackGridSlide('slide-36'),
    createTeamHierarchyOrgSlide('slide-37'),
    createSecurityComplianceMatrixSlide('slide-38'),
    createProductRoadmapTimelineSlide('slide-39'),
    createInteractiveFaqFlowSlide('slide-40'),
    createKeyMetricScorecardSlide('slide-41'),
    createCaseStudyImpactSlide('slide-42'),
    createDualColumnProsConsSlide('slide-43'),
    createInteractiveCodePlaygroundSlide('slide-44'),
    createClosingCtaShowcaseSlide('slide-45'),
    createTimelineRailSlide('slide-46'),
    createPersonalVpnSlide('slide-47'),
    createMeetingTranscriptSlide('slide-48'),
    createLlmBenchmarkSlide('slide-49'),
    createServicesGravitySlide('slide-50'),
    createSeoDominanceSlide('slide-51'),
    createStaffAugPipelineSlide('slide-52'),
    createCraftsmanshipBenchmarkSlide('slide-53'),
    createWeeklyCadenceSlide('slide-54'),
    createCompetitiveMoatSlide('slide-55'),
    createRapidFeedbackSlide('slide-56'),
    createInteractivePollSlide('slide-57'),
    createLiveQaSlide('slide-58'),
    createEmbedStageSlide('slide-59'),
    createCountdownLaunchSlide('slide-60'),
    createExecutiveTakeawaysSlide('slide-61'),
    createCodeDiffComparisonSlide('slide-62'),
    createGlobalCloudEdgeMeshSlide('slide-63'),
    createApiEndpointInspectorSlide('slide-64'),
    createDatabaseSchemaErdSlide('slide-65'),
    createSecurityThreatModelSlide('slide-66'),
    createAiAgentSwarmDagSlide('slide-67'),
    createFinancialBurnRunwaySlide('slide-68'),
    createBentoKpiMosaicSlide('slide-69'),
    createCanaryReleaseGaugeSlide('slide-70'),
    createIncidentRcaPostmortemSlide('slide-71'),
    createSlasAndUptimeStatusSlide('slide-72'),
    createAudioWaveformStudioSlide('slide-73'),
    createHardwareSiliconSpecSlide('slide-74'),
    createCohortRetentionHeatmapSlide('slide-75'),
    createVerifiableAuditLedgerSlide('slide-76'),
    createExecutiveGovernanceMatrixSlide('slide-77'),
    createOkrCascadeAlignmentSlide('slide-78'),
    createCloudCostFinOpsOptimizerSlide('slide-79'),
    createCustomerSentimentRadarSlide('slide-80'),
    createCompetitiveBattlecardSlide('slide-81'),
    createLaunchReadinessChecklistSlide('slide-82'),
    createDeveloperGatewaySandboxSlide('slide-83'),
    createRagPipelineTopologySlide('slide-84'),
    createSocIncidentWarRoomSlide('slide-85'),
    createMerkleTreeStateLedgerSlide('slide-86'),
    createInvestorCapTableWaterfallSlide('slide-87'),
    createRealtimeEventStreamFabricSlide('slide-88'),
    createSupplyChainRiskMatrixSlide('slide-89'),
    createTalentCompetencyRadarSlide('slide-90'),
    createSustainabilityEsgScorecardSlide('slide-91'),
    createThreeHorizonsStrategySlide('slide-92'),
    createAiAgentFleetTopologySlide('slide-93'),
    createModelContextProtocolMeshSlide('slide-94'),
    createCyberThreatKillChainSlide('slide-95'),
    createComplianceSoc2ReadinessLadderSlide('slide-96'),
    createApiRateLimitGatewaySlide('slide-97'),
    createMultiCloudDrFailoverSlide('slide-98'),
    createFintechPaymentClearingSlide('slide-99'),
    createEsgDecarbonizationRoadmapSlide('slide-100'),
    createDataCleanRoomSlide('slide-101'),
    createDeveloperPlatformIdpSlide('slide-102'),
    createExecutiveMaSynergySlide('slide-103'),
    createSupplyChainDigitalTwinSlide('slide-104'),
    createVoiceAiConversationalMeshSlide('slide-105'),
    createValueStreamDoraFlywheelSlide('slide-106'),
    createExecutiveStorytellingHookSlide('slide-107'),
    createLeadershipSynergyDuoSlide('slide-108'),
    createOperationalWorkCultureSlide('slide-109'),
    createBentoCapabilitiesMatrixSlide('slide-110'),
    createOpportunityCostWaterfallSlide('slide-111'),
    createBenchmarkRegionalPricingSlide('slide-112'),
    createSprintOnboardingRoadmapSlide('slide-113'),
    createSimulatedBrowserShowcaseSlide('slide-114'),
    createClientTestimonialWallSlide('slide-115'),
    createGlobalEdgeMeshSlide('slide-116'),
    createAiGovernanceSafetyGovernorSlide('slide-117'),
    createDeveloperVelocityFlywheelSlide('slide-118'),
    createStrategicDecarbonizationEsgSlide('slide-119'),
    createMarketTensionQuadrantSlide('slide-120'),
    createExecutiveCloseContactSlide('slide-121'),
    createEnterpriseCloudMigrationFunnelSlide('slide-122'),
    createZeroTrustIdentityPerimeterSlide('slide-123'),
    createAiDataFlywheelLifecycleSlide('slide-124'),
    createIncidentCommandWarRoomSlide('slide-125'),
    createRegulatoryGdprDataLineageSlide('slide-126'),
    createSaasUnitEconomicsBreakdownSlide('slide-127'),
    createGlobalFintechLedgerSettlementSlide('slide-128'),
    createMultiTenantDatabaseShardingSlide('slide-129'),
    createContinuousCompliancePostureSlide('slide-130'),
    createDeveloperPlatformCatalogMeshSlide('slide-131'),
    createBoardroomMarketInflectionThesisSlide('slide-132'),
    createAsymmetricThreatDefenseMatrixSlide('slide-133'),
    createHardwareAcceleratorDieTopologySlide('slide-134'),
    createCustomerExperienceJourneyDeltaSlide('slide-135'),
    createExecutiveBoardMandateCtaSlide('slide-136'),
    createNeuralVectorSearchTopologySlide('slide-137'),
    createModelQuantizationSpeculativeDecodingSlide('slide-138'),
    createCqrsEventSourcingFabricSlide('slide-139'),
    createPostMergerIntegrationRoadmapSlide('slide-140'),
    createCspmCiemCloudEntitlementGraphSlide('slide-141'),
    createConfidentialComputingEnclaveSlide('slide-142'),
    createPredictiveAutoscalingPodMatrixSlide('slide-143'),
    createCapexOpexCapitalAllocationSlide('slide-144'),
    createTransferPricingTaxTopologySlide('slide-145'),
    createSalesQuotaCompensationMatrixSlide('slide-146'),
    createExecutiveSuccessionLeadershipBenchSlide('slide-147'),
    createInteractiveBranchingCloseSlide('slide-148'),
    createBeforeAfterShowcasePanSlide('slide-149'),
    createSearchSerpProofLightboxSlide('slide-150'),
    createCognitiveInversionPunchlineSlide('slide-151'),
    createTalentPyramidFunnelSvgSlide('slide-152'),
    createHexagonalTechClusterSlide('slide-153'),
    createConnectedRoadmapRailPulseSlide('slide-154'),
    createCampaignPerformanceLightboxSlide('slide-155'),
    createExecutiveRosterKeypadSlide('slide-156'),
    createFlatStepProcessFlowSlide('slide-157'),
    createFlatSplitNarrativeStepperSlide('slide-158'),
    createFlatTimelineMilestoneRailSlide('slide-159'),
    createFlatRevealBentoGridSlide('slide-160'),
    createFlatDepthSentenceStackSlide('slide-161'),
    createFlatTypewriterCodeWalkthroughSlide('slide-162'),
    createExecutiveMandateScorecardSlide('slide-163'),
    createBoardQuorumResolutionLedgerSlide('slide-164'),
    createMacroEconomicThreatRadarSlide('slide-165'),
    createZeroTrustNetworkMeshSlide('slide-166'),
    createDistributedConsensusRaftLogSlide('slide-167'),
    createDataPipelineLineageDagSlide('slide-168'),
    createCodeWalkthroughSyntaxLensSlide('slide-169'),
    createTierComparisonFeatureMatrixSlide('slide-170'),
    createArrGrowthBridgeWaterfallSlide('slide-171'),
    createMultiTierSaasPackagingTableSlide('slide-172'),
    createFlywheelGrowthMomentumOrbitSlide('slide-173'),
    createEnterpriseCaseStudyHeroSlide('slide-174'),
    createClientWallSocialProofGridSlide('slide-175'),
    createIncidentRetrospectiveTimelineSlide('slide-176'),
    createInteractiveFaqTabbedDeckSlide('slide-177'),
    createAudienceDecisionForkMatrixSlide('slide-178'),
    createGpuClusterFabricSlide('slide-179'),
    createRagNeedleHaystackSlide('slide-180'),
    createEbpfKernelTelemetrySlide('slide-181'),
    createSaasNetRevenueRetentionSlide('slide-182'),
    createBoardroomMaSynergySlide('slide-183'),
    createLlmAgenticWorkflowSlide('slide-184'),
    createZeroDowntimeBlueGreenSlide('slide-185'),
    createPostQuantumPqcKemSlide('slide-186'),
    createDeveloperPlatformBackstageSlide('slide-187'),
    createSoc2Type2EvidenceStreamSlide('slide-188'),
    createAiModelDistillationSlide('slide-189'),
    createExecutiveCompensationClawbackSlide('slide-190'),
    createEnterpriseLlmFineTuningSlide('slide-191'),
    createDistributedVectorIndexSlide('slide-192'),
    createRealtimeFinancialFraudSlide('slide-193'),
    createAutonomousCloudCostSlide('slide-194'),
    createLakehouseIcebergAcidSlide('slide-195'),
    createMultiRegionActiveActiveSlide('slide-196'),
    createSupplyChainCarbonCbamSlide('slide-197'),
    createChaosMeshNetworkPartitionSlide('slide-198'),
    createAgenticEvalRedTeamSlide('slide-199'),
    createGitOpsArgoCdSyncSlide('slide-200'),
    createNvmeFabricsRdmaSlide('slide-201'),
    createConfidentialGpuAttestSlide('slide-202'),
    createEbpfDdosXdpSlide('slide-203'),
    createActiveInferenceMemorySlide('slide-204'),
    createSovereignAiCleanRoomSlide('slide-205'),
    createIncidentCommandPlaybookSlide('slide-206'),
    createGpuHbmInterconnectSlide('slide-207'),
    createRealtimeFeatureStoreSlide('slide-208'),
    createDistributedWalRaftSlide('slide-209'),
    createFinopsUnitEconomicsSlide('slide-210'),
    createCrossBorderDataResidencySlide('slide-211'),
    createZeroTrustSpiffeSlide('slide-212'),
    createBoardCapitalAllocationSlide('slide-213'),
    createPqcMigrationFlowSlide('slide-214'),
    createAgentHierarchicalMemorySlide('slide-215'),
    createActiveActiveShardingSlide('slide-216'),
    createZeroTrustApiMeshSlide('slide-217'),
    createAutonomousVulnerabilityLoopSlide('slide-218'),
    createEdgeComputeOrchestratorSlide('slide-219'),
    createCloudFinopsLadderSlide('slide-220'),
    createBoardAiRiskOversightSlide('slide-221'),
    createSovereignQkdBackboneSlide('slide-222'),
    createAgentSwarmMemoryRegistrySlide('slide-223'),
    createHyperscaleShardingTopologySlide('slide-224'),
    createMicroservicesZeroTrustPolicySlide('slide-225'),
    createAutonomousSiemTriageSlide('slide-226'),
    createEdgeFleetDensitySlide('slide-227'),
    createBoardFiduciaryEsgHorizonSlide('slide-228'),
    createExecutivePnlWaterfallTableSlide('slide-229'),
    createCompetitiveFeatureHeatmapSlide('slide-230'),
    createCustomerPersonaArchetypeSplitSlide('slide-231'),
    createGlobalDataJurisdictionBoundarySlide('slide-232'),
    createHardwareInterfaceBlueprintSlide('slide-233'),
    createMultiHorizonValueRealizationBridgeSlide('slide-234'),
    createTwoSidedEcosystemFlywheelSlide('slide-235'),
    createIshikawaRootCauseFishboneSlide('slide-236'),
    createModularConsumptionPricingCalculatorSlide('slide-237'),
    createLiveProductViewportWalkthroughSlide('slide-238'),
    createEnterpriseRiskTaxonomyHeatmapSlide('slide-239'),
    createGlobalPartnerTieringLadderSlide('slide-240'),
    createTalentCompetencyGapHeatmapSlide('slide-241'),
    createSloErrorBudgetBurnWaterfallSlide('slide-242'),
    createWeightedDecisionTradeoffMatrixSlide('slide-243'),
    createCustomerChurnInterventionLadderSlide('slide-244'),
    createAiInferenceCostTokenWaterfallSlide('slide-245'),
    createCrossFunctionalRaciMatrixSlide('slide-246'),
    createZeroTrustMicrosegmentationMapSlide('slide-247'),
    createSaasMagicNumberEfficiencyGaugeSlide('slide-248'),
    createSupplyChainGeopoliticalChokepointSlide('slide-249'),
    createIncidentSev1CommandTimelineSlide('slide-250'),
    createCloudFinopsUnitRateOptimizationSlide('slide-251'),
    createProductMarketFitCohortTrianglesSlide('slide-252'),
    createEnterpriseAiGovernanceGuardrailsSlide('slide-253'),
    createDataLakehouseMedallionPipelineSlide('slide-254'),
    createMergerAcquisitionSynergyBridgeSlide('slide-255'),
    createDeveloperProductivitySpaceFrameworkSlide('slide-256'),
    createHybridCloudDrFailoverTopologySlide('slide-257'),
    createCustomerHealthScorecardMatrixSlide('slide-258'),
    createValueStreamBottleneckFlowSlide('slide-259'),
    createSyntheticDataCurationPipelineSlide('slide-260'),
    createCloudNativeWasmMicroserviceMeshSlide('slide-261'),
    createSovereignAiDatacenterPowerGridSlide('slide-262'),
    createAutonomousCodeSecurityPatchingLoopSlide('slide-263'),
    createCrossCloudMeshLatencyRoutingSlide('slide-264'),
    createEnterpriseGenaiAppObservabilitySlide('slide-265'),
    createZeroDowntimeSchemaEvolutionStepperSlide('slide-266'),
    createEnterpriseSoftwareSupplyChainChokepointSlide('slide-267'),
    createAiAgentMultiTurnOrchestrationDagSlide('slide-268'),
    createEnterpriseDataCleanRoomAuditSlide('slide-269'),
    createHyperscaleK8sCostAllocatorMatrixSlide('slide-270'),
    createCyberResilienceRansomwareReadinessRadarSlide('slide-271'),
    createSaasExpansionRetentionWaterfallGaugeSlide('slide-272'),
    createDeveloperExperienceFrictionIndexHeatmapSlide('slide-273'),
    createGeopoliticalSovereignCloudComplianceCompassSlide('slide-274'),
    ...createSuite2029Slides(275),
    ...createSuite2030Slides(290),
  ],
};

export const initialSlides = INITIAL_DECK.slides;
