import { PresentationDeck } from '../types/presentation';
import {
  createMetricGridSlide,
  createProblemSolutionSlide,
  createQuadrantMatrixSlide,
  createMarketOpportunitySlide,
  createTimelineRoadmapSlide,
  createFeatureGridSlide,
  createArchitectureDiagramSlide,
  createQuoteCalloutSlide,
  createStatsCalloutSlide,
  createTeamGridSlide,
  createCaseStudySlide,
  createComparisonColumnsSlide,
  createProcessCycleSlide,
  createCodeTerminalSlide,
  createCallToActionSlide,
  createGrowthEngineSlide,
  createTalentPyramidSlide,
  createCostComparisonSlide,
  createDepthStackSlide,
  createRevealGridSlide,
  createBeforeAfterShowcaseSlide,
} from '../utils/slideArchetypeFactories';
import {
  createAuthenticityHookSlide,
  createAvoidCommoditySlide,
  createSwotAnalysisSlide,
  createCompetitorMatrixSlide,
  createExecutiveContactSlide,
} from '../utils/expandedSlideFactories';
import {
  createExecutiveSummarySlide,
  createSystemArchitectureFlowSlide,
  createRoiMetricCalculatorSlide,
  createCustomerJourneyMapSlide,
  createMatrixComparisonGridSlide,
  createTechStackGridSlide,
  createTeamHierarchyOrgSlide,
  createSecurityComplianceMatrixSlide,
  createProductRoadmapTimelineSlide,
  createInteractiveFaqFlowSlide,
  createKeyMetricScorecardSlide,
  createCaseStudyImpactSlide,
  createDualColumnProsConsSlide,
  createInteractiveCodePlaygroundSlide,
  createClosingCtaShowcaseSlide,
  createTimelineRailSlide,
} from '../utils/enterpriseSlideFactories';
import {
  createPersonalVpnSlide,
  createMeetingTranscriptSlide,
  createLlmBenchmarkSlide,
  createServicesGravitySlide,
  createSeoDominanceSlide,
  createStaffAugPipelineSlide,
  createCraftsmanshipBenchmarkSlide,
  createWeeklyCadenceSlide,
  createCompetitiveMoatSlide,
  createRapidFeedbackSlide,
  createInteractivePollSlide,
  createLiveQaSlide,
  createEmbedStageSlide,
  createCountdownLaunchSlide,
  createExecutiveTakeawaysSlide,
} from '../utils/extendedSlideFactories';
import {
  createCodeDiffComparisonSlide,
  createGlobalCloudEdgeMeshSlide,
  createApiEndpointInspectorSlide,
  createDatabaseSchemaErdSlide,
  createSecurityThreatModelSlide,
  createAiAgentSwarmDagSlide,
  createFinancialBurnRunwaySlide,
  createBentoKpiMosaicSlide,
  createCanaryReleaseGaugeSlide,
  createIncidentRcaPostmortemSlide,
  createSlasAndUptimeStatusSlide,
  createAudioWaveformStudioSlide,
  createHardwareSiliconSpecSlide,
  createCohortRetentionHeatmapSlide,
  createVerifiableAuditLedgerSlide,
} from '../utils/kineticSuiteSlideFactories';
import {
  createExecutiveGovernanceMatrixSlide,
  createOkrCascadeAlignmentSlide,
  createCloudCostFinopsOptimizerSlide as createCloudCostFinOpsOptimizerSlide,
  createCustomerSentimentRadarSlide,
  createCompetitiveBattlecardSlide,
  createLaunchReadinessChecklistSlide,
  createDeveloperGatewaySandboxSlide,
  createRagPipelineTopologySlide,
  createSocIncidentWarRoomSlide,
  createMerkleTreeStateLedgerSlide,
  createInvestorCapTableWaterfallSlide,
  createRealtimeEventStreamFabricSlide,
  createSupplyChainRiskMatrixSlide,
  createTalentCompetencyRadarSlide,
  createSustainabilityEsgScorecardSlide,
} from '../utils/globalPptSlideFactories';

export const INITIAL_DECK: PresentationDeck = {
  id: 'white-presentation-v1',
  title: 'White Presentation System - Executive Keynote',
  version: '1.3.1',
  author: 'Riseup Asia Architectural Team',
  defaultThemeId: 'white-brand',
  canvas: {
    width: 1920,
    height: 1080,
    aspectRatio: '16:9',
  },
  slides: [
    {
      id: 'slide-01',
      type: 'white-master',
      title: 'Stories Are Emotional Bridges',
      headline: 'Stories Are Emotional Bridges',
      subtitle: 'Transform raw data and technical architecture into unforgettable enterprise impact.',
      kicker: 'STRATEGIC NARRATIVE',
      bulletPoints: [
        {
          id: 'bp-1',
          icon: 'heart',
          title: 'Emotional Resonance',
          description: 'Facts inform, but emotional connections drive multimillion-dollar decisions and leadership alignment.',
        },
        {
          id: 'bp-2',
          icon: 'users',
          title: 'Human-Centered Context',
          description: 'Bridge executive vision with operational reality through clear, empathetic engineering narratives.',
        },
        {
          id: 'bp-3',
          icon: 'chat',
          title: 'Catalyst for Action',
          description: 'A well-crafted story breaks through executive inertia, galvanizing teams toward swift execution.',
        },
      ],
      heroImage: {
        src: '/assets/screenshots/hero-speaker-clean.png',
        alt: 'Speaker sharing emotional narrative with audience',
        featherDirection: 'left',
      },
      neonGlow: {
        color: '#F43F5E',
        shape: 'heart',
        pulseRateSeconds: 2.2,
      },
      logo: {
        src: '/assets/logos/6 - Riseup Asia Logo Transparent Only BK.png',
        alt: 'Riseup Asia Logo',
        heightPx: 42,
      },
    },
    {
      id: 'slide-02',
      type: 'title',
      title: 'Autonomous Presentation Architecture',
      subtitle: 'The Next-Generation Declarative Slide Platform for High-Stakes Tech Keynotes',
      kicker: 'KEYNOTE PRESENTATION',
      presenter: {
        name: 'Alim Ul Karim',
        role: 'Chief Software Engineer',
        company: 'Riseup Asia LLC',
      },
      date: 'September 2026',
    },
    {
      id: 'slide-03',
      type: 'persona',
      title: 'Technical Leadership',
      name: 'Alim Ul Karim',
      role: 'Chief Software Engineer',
      quote: 'We engineer sovereign, high-leverage software architectures with zero defect tolerance.',
      avatarUrl: '/assets/screenshots/hero-speaker-clean.png',
      metrics: [
        { value: '15+ Yrs', label: 'Enterprise Systems' },
        { value: '40M+', label: 'Active End Users' },
      ],
      bioBullets: [
        'Direct architect of multi-tenant enterprise cloud systems across North America & Asia.',
        'Pioneer of deterministic AI workflows, autonomous loop orchestration, and zero-defect QA.',
        'Senior enterprise software consultant for scalable cloud architectures.',
      ],
    },
    createBeforeAfterShowcaseSlide('slide-04'),
    {
      id: 'slide-05',
      type: 'steps',
      title: 'Autonomous Delivery Lifecycle',
      kicker: 'AUTONOMOUS WORKFLOW',
      heading: 'Three phases, one week each',
      steps: [
        { label: 'Discover', title: 'Talk to 5 users', detail: 'Interview five real users. Extract architectural pain points and write specifications within 24 hours.' },
        { label: 'Prototype', title: 'One click, one screen', detail: 'Build the thinnest sovereign slice that solves the mission. Zero fluff, pure DOM performance.' },
        { label: 'Ship', title: 'Behind a flag', detail: 'Continuous production deployment every Friday. Immediate real-time validation across active teams.' },
      ],
    },
    createGrowthEngineSlide('slide-06'),
    createTalentPyramidSlide('slide-07'),
    createCostComparisonSlide('slide-08'),
    createMetricGridSlide('slide-09'),
    createProblemSolutionSlide('slide-10'),
    createQuadrantMatrixSlide('slide-11'),
    createMarketOpportunitySlide('slide-12'),
    createTimelineRoadmapSlide('slide-13'),
    createFeatureGridSlide('slide-14'),
    createArchitectureDiagramSlide('slide-15'),
    createDepthStackSlide('slide-16'),
    createRevealGridSlide('slide-17'),
    createProcessCycleSlide('slide-18'),
    createStatsCalloutSlide('slide-19'),
    createCodeTerminalSlide('slide-20'),
    createTeamGridSlide('slide-21'),
    createCaseStudySlide('slide-22'),
    createQuoteCalloutSlide('slide-23'),
    createComparisonColumnsSlide('slide-24'),
    createCallToActionSlide('slide-25'),
    createAuthenticityHookSlide('slide-26'),
    createAvoidCommoditySlide('slide-27'),
    createSwotAnalysisSlide('slide-28'),
    createCompetitorMatrixSlide('slide-29'),
    createExecutiveContactSlide('slide-30'),
    createExecutiveSummarySlide('slide-31'),
    createSystemArchitectureFlowSlide('slide-32'),
    createRoiMetricCalculatorSlide('slide-33'),
    createCustomerJourneyMapSlide('slide-34'),
    createMatrixComparisonGridSlide('slide-35'),
    createTechStackGridSlide('slide-36'),
    createTeamHierarchyOrgSlide('slide-37'),
    createSecurityComplianceMatrixSlide('slide-38'),
    createProductRoadmapTimelineSlide('slide-39'),
    createInteractiveFaqFlowSlide('slide-40'),
    createKeyMetricScorecardSlide('slide-41'),
    createCaseStudyImpactSlide('slide-42'),
    createDualColumnProsConsSlide('slide-43'),
    createInteractiveCodePlaygroundSlide('slide-44'),
    createClosingCtaShowcaseSlide('slide-45'),
    createTimelineRailSlide('slide-46'),
    createPersonalVpnSlide('slide-47'),
    createMeetingTranscriptSlide('slide-48'),
    createLlmBenchmarkSlide('slide-49'),
    createServicesGravitySlide('slide-50'),
    createSeoDominanceSlide('slide-51'),
    createStaffAugPipelineSlide('slide-52'),
    createCraftsmanshipBenchmarkSlide('slide-53'),
    createWeeklyCadenceSlide('slide-54'),
    createCompetitiveMoatSlide('slide-55'),
    createRapidFeedbackSlide('slide-56'),
    createInteractivePollSlide('slide-57'),
    createLiveQaSlide('slide-58'),
    createEmbedStageSlide('slide-59'),
    createCountdownLaunchSlide('slide-60'),
    createExecutiveTakeawaysSlide('slide-61'),
    createCodeDiffComparisonSlide('slide-62'),
    createGlobalCloudEdgeMeshSlide('slide-63'),
    createApiEndpointInspectorSlide('slide-64'),
    createDatabaseSchemaErdSlide('slide-65'),
    createSecurityThreatModelSlide('slide-66'),
    createAiAgentSwarmDagSlide('slide-67'),
    createFinancialBurnRunwaySlide('slide-68'),
    createBentoKpiMosaicSlide('slide-69'),
    createCanaryReleaseGaugeSlide('slide-70'),
    createIncidentRcaPostmortemSlide('slide-71'),
    createSlasAndUptimeStatusSlide('slide-72'),
    createAudioWaveformStudioSlide('slide-73'),
    createHardwareSiliconSpecSlide('slide-74'),
    createCohortRetentionHeatmapSlide('slide-75'),
    createVerifiableAuditLedgerSlide('slide-76'),
    createExecutiveGovernanceMatrixSlide('slide-77'),
    createOkrCascadeAlignmentSlide('slide-78'),
    createCloudCostFinOpsOptimizerSlide('slide-79'),
    createCustomerSentimentRadarSlide('slide-80'),
    createCompetitiveBattlecardSlide('slide-81'),
    createLaunchReadinessChecklistSlide('slide-82'),
    createDeveloperGatewaySandboxSlide('slide-83'),
    createRagPipelineTopologySlide('slide-84'),
    createSocIncidentWarRoomSlide('slide-85'),
    createMerkleTreeStateLedgerSlide('slide-86'),
    createInvestorCapTableWaterfallSlide('slide-87'),
    createRealtimeEventStreamFabricSlide('slide-88'),
    createSupplyChainRiskMatrixSlide('slide-89'),
    createTalentCompetencyRadarSlide('slide-90'),
    createSustainabilityEsgScorecardSlide('slide-91'),
  ],
};
