// lint-allow: file-size reason="customization slide default factories for 15 enterprise archetypes" max=500
import type {
  NeuralVectorSearchTopologySlideData,
  ModelQuantizationSpeculativeDecodingSlideData,
  LlmFirewallRedTeamMatrixSlideData,
  GlobalAnycastTrafficDirectorSlideData,
  CqrsEventSourcingFabricSlideData,
  SbomSlsaProvenanceAttestationSlideData,
  PostMergerIntegrationRoadmapSlideData,
  Scope3CarbonSupplyChainAuditSlideData,
  CspmCiemCloudEntitlementGraphSlideData,
  ConfidentialComputingEnclaveSlideData,
  PredictiveAutoscalingPodMatrixSlideData,
  CapexOpexCapitalAllocationSlideData,
  TransferPricingTaxTopologySlideData,
  SalesQuotaCompensationMatrixSlideData,
  ExecutiveSuccessionLeadershipBenchSlideData,
  CustomizationSlideData,
  CustomizationSlideType,
} from '../types/customizationArchetypes';

export const createNeuralVectorSearchTopologySlide = (
  id = `slide-vector-search-${Date.now()}`
): NeuralVectorSearchTopologySlideData => {
  const searchPhases = [
    {
      id: 'phase-01',
      stepIndex: 1,
      phaseName: 'Dense Bi-Encoder Query Embedding',
      subsystemTitle: 'Embedding Gateway',
      latencyBudgetMs: 1.2,
      recallPercentage: 99.4,
      indexingAlgorithm: 'BGE-Large-v1.5',
      throughputQps: 12500,
      isPhaseActive: true,
      isPhaseCompleted: true,
      keyTechniques: ['FP16 TensorRT-LLM', 'Context Batching', 'Prefix Caching'],
    },
    {
      id: 'phase-02',
      stepIndex: 2,
      phaseName: 'Hierarchical Navigable Small World Search',
      subsystemTitle: 'HNSW Graph Traverse',
      latencyBudgetMs: 1.8,
      recallPercentage: 98.2,
      indexingAlgorithm: 'HNSW-M32-efSearch128',
      throughputQps: 9400,
      isPhaseActive: false,
      isPhaseCompleted: false,
      keyTechniques: ['SIMD AVX-512 Distance', 'Skip-List Pruning', 'Scalar Quantization 8-bit'],
    },
    {
      id: 'phase-03',
      stepIndex: 3,
      phaseName: 'Inverted Multi-Index Filter & Partition',
      subsystemTitle: 'Metadata Filter',
      latencyBudgetMs: 0.6,
      recallPercentage: 97.9,
      indexingAlgorithm: 'Bitset Intersect',
      throughputQps: 14200,
      isPhaseActive: false,
      isPhaseCompleted: false,
      keyTechniques: ['Roaring Bitmaps', 'Pre-filter Sharding', 'Zero Copy IPC'],
    },
    {
      id: 'phase-04',
      stepIndex: 4,
      phaseName: 'Cross-Encoder Re-Ranking & Calibration',
      subsystemTitle: 'Precision Ranker',
      latencyBudgetMs: 0.6,
      recallPercentage: 99.8,
      indexingAlgorithm: 'MiniLM-L6-v2',
      throughputQps: 8200,
      isPhaseActive: false,
      isPhaseCompleted: false,
      keyTechniques: ['Full Attention Cross-Score', 'Sigmoid Calibration', 'Top-50 Truncation'],
    },
  ];

  return {
    id,
    type: 'neural-vector-search-topology',
    title: 'Neural Vector Search Topology & HNSW Indexing',
    kicker: 'AI INFRASTRUCTURE & RETRIEVAL',
    subtitle: 'Sub-millisecond semantic retrieval across 1.2 billion high-dimensional embeddings',
    embeddingDimension: 1536,
    distanceMetric: 'Cosine Similarity',
    totalVectorsCount: '1.2 Billion',
    p99LatencyMs: 4.2,
    isGpuAccelerated: true,
    hasQuantizedVectors: true,
    isHnswIndexed: true,
    hasCrossEncoderRerank: true,
    searchPhases,
    stages: searchPhases,
    activeStep: 1,
    maxSteps: 4,
  };
};

export const createModelQuantizationSpeculativeDecodingSlide = (
  id = `slide-speculative-decoding-${Date.now()}`
): ModelQuantizationSpeculativeDecodingSlideData => {
  const decodingStages = [
    {
      id: 'stage-01',
      stepIndex: 1,
      stageName: 'Draft Model K-Token Speculation',
      modelRole: 'Draft Engine (1B FP8)',
      batchSize: 64,
      acceptanceRatePercentage: 84.5,
      speedupFactor: 2.4,
      isStageActive: true,
      isStageCompleted: true,
      optimizationTechniques: ['Paged Attention v2', 'Tree Speculation', 'Weight-Only INT4'],
    },
    {
      id: 'stage-02',
      stepIndex: 2,
      stageName: 'Target Model Parallel Verification',
      modelRole: 'Verifier (70B AWQ)',
      batchSize: 64,
      acceptanceRatePercentage: 79.2,
      speedupFactor: 2.8,
      isStageActive: false,
      isStageCompleted: false,
      optimizationTechniques: ['FlashInfer Kernels', 'KV-Cache Ring Buffer', 'Fused GEMM-AWQ'],
    },
    {
      id: 'stage-03',
      stepIndex: 3,
      stageName: 'Branch Pruning & Rejection Sampling',
      modelRole: 'Stochastic Arbiter',
      batchSize: 64,
      acceptanceRatePercentage: 91.0,
      speedupFactor: 3.1,
      isStageActive: false,
      isStageCompleted: false,
      optimizationTechniques: ['Nucleus Temperature Matching', 'Greedy Fallback', 'Entropy Gate'],
    },
    {
      id: 'stage-04',
      stepIndex: 4,
      stageName: 'Paged KV Eviction & Continuous Batching',
      modelRole: 'Memory Manager',
      batchSize: 64,
      acceptanceRatePercentage: 99.2,
      speedupFactor: 3.4,
      isStageActive: false,
      isStageCompleted: false,
      optimizationTechniques: ['Radix Cache Sharing', 'Chunked Prefill', 'Zero Host-Transfer'],
    },
  ];

  return {
    id,
    type: 'model-quantization-speculative-decoding',
    title: 'Model Quantization & Speculative Decoding Engine',
    kicker: 'LLM INFERENCE ACCELERATION',
    subtitle: '2.8x token throughput acceleration with FP8/AWQ precision and drafting verifier',
    targetModelName: 'Llama-3.3-70B-Instruct',
    draftModelName: 'Llama-3.2-1B-Draft',
    quantizationPrecision: 'AWQ-INT4 / FP8 Hybrid',
    tokensPerSecond: 168,
    isAwqQuantized: true,
    hasSpeculativeEngine: true,
    isKvCachePaged: true,
    hasZeroPerplexityLoss: true,
    decodingStages,
    stages: decodingStages,
    activeStep: 1,
    maxSteps: 4,
  };
};

export const createLlmFirewallRedTeamMatrixSlide = (
  id = `slide-llm-firewall-${Date.now()}`
): LlmFirewallRedTeamMatrixSlideData => {
  const guardrailGates = [
    {
      id: 'gate-01',
      stepIndex: 1,
      gateName: 'Input Token Sanitization & Canary Injection',
      inspectionDomain: 'Prompt Boundary Defense',
      latencyBudgetMs: 2.4,
      blockRatePercentage: 99.7,
      mitigationAction: 'Immediate Terminal Quarantining',
      isGateActive: true,
      isGatePassed: true,
      detectionRules: ['Hex Escapes', 'Invisible Unicode Truncation', 'Token Smuggling'],
    },
    {
      id: 'gate-02',
      stepIndex: 2,
      gateName: 'Semantic Intent & Indirect Jailbreak Classifier',
      inspectionDomain: 'Cognitive Policy Audit',
      latencyBudgetMs: 4.1,
      blockRatePercentage: 99.4,
      mitigationAction: 'Contextual Semantic Inversion',
      isGateActive: false,
      isGatePassed: false,
      detectionRules: ['Multi-turn Roleplay Inversion', 'Hypothetical Overrides', 'DAN Jailbreak Vectors'],
    },
    {
      id: 'gate-03',
      stepIndex: 3,
      gateName: 'Tool Sandbox Boundary & SQL/Bash Defense',
      inspectionDomain: 'Autonomous Execution Guard',
      latencyBudgetMs: 1.8,
      blockRatePercentage: 100.0,
      mitigationAction: 'Ephemeral Container Termination',
      isGateActive: false,
      isGatePassed: false,
      detectionRules: ['AST Parse Validation', 'Strict Allowlist Schema', 'Subprocess Execution Ban'],
    },
    {
      id: 'gate-04',
      stepIndex: 4,
      gateName: 'PII Scrubbing & Cryptographic Watermarking',
      inspectionDomain: 'Egress Data Governance',
      latencyBudgetMs: 1.5,
      blockRatePercentage: 99.9,
      mitigationAction: 'Deterministic Token Masking',
      isGateActive: false,
      isGatePassed: false,
      detectionRules: ['Differential Privacy Masking', 'Secret Key HMAC Watermark', 'Zero Token Leakage'],
    },
  ];

  return {
    id,
    type: 'llm-firewall-red-team-matrix',
    title: 'LLM Firewall & Red Team Matrix',
    kicker: 'ADVERSARIAL AI DEFENSE',
    subtitle: 'Real-time prompt injection mitigation, PII sanitization, and output boundary enforcement',
    adversarialSimulationsCount: 14200,
    defenseAccuracyRate: 99.8,
    complianceFramework: 'OWASP LLM Top 10 & NIST AI RMF',
    hasPiiSanitized: true,
    isJailbreakBlocked: true,
    isPolicyCompliant: true,
    hasAuditSignature: true,
    guardrailGates,
    stages: guardrailGates,
    activeStep: 1,
    maxSteps: 4,
  };
};

export const createGlobalAnycastTrafficDirectorSlide = (
  id = `slide-anycast-director-${Date.now()}`
): GlobalAnycastTrafficDirectorSlideData => {
  const routingSteps = [
    {
      id: 'route-01',
      stepIndex: 1,
      stepName: 'Global BGP Route Ingress',
      edgeLocation: 'Edge PoP Tier 1 (185 Hubs)',
      ingressProtocol: 'BGP Anycast / QUIC HTTP/3',
      latencyMs: 3.2,
      trafficWeightPercentage: 100,
      isStepActive: true,
      isStepHealthy: true,
      routingFeatures: ['AS13335 Equal-Cost Multi-Path', 'Anti-DDoS Scrubbing', 'Fast Reroute'],
    },
    {
      id: 'route-02',
      stepIndex: 2,
      stepName: 'Zero-RTT TLS Session Resumption',
      edgeLocation: 'Regional Edge Data Center',
      ingressProtocol: 'TLS 1.3 / ChaCha20',
      latencyMs: 1.1,
      trafficWeightPercentage: 100,
      isStepActive: false,
      isStepHealthy: true,
      routingFeatures: ['Session Ticket Cryptographic Caching', 'Mutual TLS Auth', 'HPKP Verification'],
    },
    {
      id: 'route-03',
      stepIndex: 3,
      stepName: 'Origin Shield Smart Cache Validation',
      edgeLocation: 'Continental Backbone Hub',
      ingressProtocol: 'HTTP/2 Multiplexed Tunnel',
      latencyMs: 4.8,
      trafficWeightPercentage: 88,
      isStepActive: false,
      isStepHealthy: true,
      routingFeatures: ['Cache Collapsing', 'Tiered Prefetch', 'Stale-While-Revalidate'],
    },
    {
      id: 'route-04',
      stepIndex: 4,
      stepName: 'Dynamic WireGuard Micro-Tunneling',
      edgeLocation: 'Core Sovereign VPC',
      ingressProtocol: 'WireGuard Kernel Module',
      latencyMs: 8.4,
      trafficWeightPercentage: 100,
      isStepActive: false,
      isStepHealthy: true,
      routingFeatures: ['ChaCha20-Poly1305 Encryption', 'Zero Hop Overheads', 'Autonomous Failover'],
    },
  ];

  return {
    id,
    type: 'global-anycast-traffic-director',
    title: 'Global Anycast Traffic Director & BGP Fabric',
    kicker: 'GLOBAL NETWORK INFRASTRUCTURE',
    subtitle: 'Autonomous edge route optimization across 185 PoPs with sub-15ms regional latency',
    edgePopCount: 185,
    globalBgpAsn: 13335,
    peakThroughputTbps: 42.5,
    healthCheckIntervalSec: 3,
    isAnycastAnnounced: true,
    hasTlsSessionResumed: true,
    isOriginShieldActive: true,
    hasDynamicFailover: true,
    routingSteps,
    stages: routingSteps,
    activeStep: 1,
    maxSteps: 4,
  };
};

export const createCqrsEventSourcingFabricSlide = (
  id = `slide-cqrs-fabric-${Date.now()}`
): CqrsEventSourcingFabricSlideData => {
  const streamStages = [
    {
      id: 'stage-01',
      stepIndex: 1,
      stageName: 'Command Validation & Optimistic Concurrency',
      componentRole: 'Command Gateway',
      throughputEventsPerSec: 145000,
      p99LagMilliseconds: 0.4,
      storageEngine: 'Distributed Ring Memory',
      isStageActive: true,
      isStageSynced: true,
      consistencyGuarantees: ['CAS Version Checks', 'Atomic Mutex Locks', 'Schema Schema Registry'],
    },
    {
      id: 'stage-02',
      stepIndex: 2,
      stageName: 'Append-Only Immutable Event Ledger',
      componentRole: 'Event Store Commit',
      throughputEventsPerSec: 450000,
      p99LagMilliseconds: 0.9,
      storageEngine: 'NVMe Append-Log Partition',
      isStageActive: false,
      isStageSynced: true,
      consistencyGuarantees: ['Cryptographic SHA-256 Chaining', 'Raft Consensus', 'Zero Mutation'],
    },
    {
      id: 'stage-03',
      stepIndex: 3,
      stageName: 'Partitioned Kafka Stream Broker',
      componentRole: 'Event Stream Bus',
      throughputEventsPerSec: 420000,
      p99LagMilliseconds: 1.2,
      storageEngine: 'Apache Kafka Raft (KRaft)',
      isStageActive: false,
      isStageSynced: true,
      consistencyGuarantees: ['Strict Key Ordering', 'At-Least-Once Delivery', 'Replica ACK = All'],
    },
    {
      id: 'stage-04',
      stepIndex: 4,
      stageName: 'Asynchronous Read-Model Materialization',
      componentRole: 'CQRS Projection Sink',
      throughputEventsPerSec: 380000,
      p99LagMilliseconds: 1.8,
      storageEngine: 'SQLite Split-DB / Elasticsearch',
      isStageActive: false,
      isStageSynced: true,
      consistencyGuarantees: ['Idempotent Upserts', 'Zero Lock Contention', 'Point-In-Time Replay'],
    },
  ];

  return {
    id,
    type: 'cqrs-event-sourcing-fabric',
    title: 'CQRS Event Sourcing & Partitioned Stream Topology',
    kicker: 'EVENT-DRIVEN ARCHITECTURE',
    subtitle: 'Zero data loss immutable ledger processing 450k events/sec with sub-millisecond lag',
    aggregateRootName: 'OrderSettlementAggregate',
    totalCommittedEvents: '4.8 Billion',
    snapshotFrequency: 500,
    replayRateEventsPerSec: 1250000,
    hasOptimisticLock: true,
    isEventCommitted: true,
    isStreamPartitioned: true,
    hasProjectionSynced: true,
    streamStages,
    stages: streamStages,
    activeStep: 1,
    maxSteps: 4,
  };
};

export const createSbomSlsaProvenanceAttestationSlide = (
  id = `slide-sbom-attestation-${Date.now()}`
): SbomSlsaProvenanceAttestationSlideData => {
  const attestationSteps = [
    {
      id: 'step-01',
      stepIndex: 1,
      stepName: 'Hermetic Build Containerization',
      attestationLayer: 'Isolated Compiler Sandbox',
      cryptographicDigest: 'sha256:7b42a98f12d8a0c...',
      verificationAgent: 'BuildKit Hermetic Isolation',
      isStepActive: true,
      isStepVerified: true,
      securityControls: ['Network Namespace Isolation', 'Pinned Toolchain Hashes', 'Zero Ambient Secrets'],
    },
    {
      id: 'step-02',
      stepIndex: 2,
      stepName: 'CycloneDX SBOM Deep Transitive Scan',
      attestationLayer: 'Dependency Dependency Graph',
      cryptographicDigest: 'sha256:4d83e1c699fa23b...',
      verificationAgent: 'Trivy & Grype CVE Engine',
      isStepActive: false,
      isStepVerified: true,
      securityControls: ['Zero Critical/High CVEs', 'License Compliance Matrix', 'VEX Statement Signed'],
    },
    {
      id: 'step-03',
      stepIndex: 3,
      stepName: 'Cosign Cryptographic Provenance Attestation',
      attestationLayer: 'Sigstore Transparency Log',
      cryptographicDigest: 'sha256:a1209fb338c91ef...',
      verificationAgent: 'Rekor Public Ledger',
      isStepActive: false,
      isStepVerified: true,
      securityControls: ['Keyless Fulcio OIDC Identity', 'Timestamp Authority Proof', 'Rekor Inclusion Proof'],
    },
    {
      id: 'step-04',
      stepIndex: 4,
      stepName: 'Kubernetes Kyverno Admission Gating',
      attestationLayer: 'Production Cluster Admission',
      cryptographicDigest: 'sha256:f02931a558bd07c...',
      verificationAgent: 'Kyverno Admission Controller',
      isStepActive: false,
      isStepVerified: true,
      securityControls: ['SLSA L4 Policy Gate', 'Cosign Signature Verification', 'Immutable Digest Enforcement'],
    },
  ];

  return {
    id,
    type: 'sbom-slsa-provenance-attestation',
    title: 'SBOM & SLSA Level 4 Provenance Attestation',
    kicker: 'SUPPLY CHAIN SECURITY',
    subtitle: 'Cryptographically signed build provenance, hermetic toolchains, and admission gates',
    targetArtifactUri: 'registry.corp.internal/bin/edge-agent:v2.4.0',
    builderIdentity: 'https://actions.github.com/google/antigravity-builder',
    provenanceStandard: 'SLSA v1.0 Level 4',
    certificateAuthority: 'Sigstore Fulcio / Rekor Transparency Ledger',
    hasSignedCommit: true,
    isHermeticBuild: true,
    isSlsaLevel4Compliant: true,
    hasAdmissionPassed: true,
    attestationSteps,
    stages: attestationSteps,
    activeStep: 1,
    maxSteps: 4,
  };
};

export const createPostMergerIntegrationRoadmapSlide = (
  id = `slide-post-merger-${Date.now()}`
): PostMergerIntegrationRoadmapSlideData => {
  const integrationMilestones = [
    {
      id: 'mna-01',
      stepIndex: 1,
      milestoneTitle: 'Day-1 Legal Close & Identity Gateway',
      targetTimeline: 'Weeks 1-4',
      workstreamOwner: 'SecOps & Identity',
      financialSynergyMln: 6.5,
      completionPercentage: 100,
      isMilestoneActive: true,
      isMilestoneAchieved: true,
      keyDeliverables: ['Single Sign-On Federation', 'Dual IAM Role Alignment', 'Corporate Email Routing'],
    },
    {
      id: 'mna-02',
      stepIndex: 2,
      milestoneTitle: 'Core ERP & Financial Consolidation',
      targetTimeline: 'Months 2-4',
      workstreamOwner: 'FinOps & Controllership',
      financialSynergyMln: 14.2,
      completionPercentage: 100,
      isMilestoneActive: false,
      isMilestoneAchieved: true,
      keyDeliverables: ['Chart of Accounts Merge', 'Vendor Ledger Consolidation', 'Unified Billing Pipeline'],
    },
    {
      id: 'mna-03',
      stepIndex: 3,
      milestoneTitle: 'Global Infrastructure Cloud Migration',
      targetTimeline: 'Months 5-8',
      workstreamOwner: 'Cloud Engineering',
      financialSynergyMln: 16.8,
      completionPercentage: 85,
      isMilestoneActive: false,
      isMilestoneAchieved: false,
      keyDeliverables: ['Kubernetes Cluster Drain', 'Zero Trust Network Interconnect', 'Database Shard Unification'],
    },
    {
      id: 'mna-04',
      stepIndex: 4,
      milestoneTitle: 'Unified GTM & Full Synergy Harvest',
      targetTimeline: 'Months 9-12',
      workstreamOwner: 'Revenue Operations',
      financialSynergyMln: 7.5,
      completionPercentage: 45,
      isMilestoneActive: false,
      isMilestoneAchieved: false,
      keyDeliverables: ['Combined Product Catalog', 'Enterprise Cross-Sell Playbook', 'Sales Compensation Harmonization'],
    },
  ];

  return {
    id,
    type: 'post-merger-integration-roadmap',
    title: 'Post-Merger Integration & Synergy Roadmap',
    kicker: 'CORPORATE STRATEGY & M&A',
    subtitle: 'Day-1 operational cutover, core ERP consolidation, and $45M EBITDA synergy realization',
    entityNameAcquired: 'Aether Networks Ltd',
    targetSynergyTotalMln: 45.0,
    integrationBudgetMln: 12.5,
    leadExecutiveSponsor: 'Alim Ul Karim, Chief Software Engineer',
    isDay1Completed: true,
    hasIdentityUnified: true,
    isErpConsolidated: true,
    hasSynergyAchieved: true,
    integrationMilestones,
    stages: integrationMilestones,
    activeStep: 1,
    maxSteps: 4,
  };
};

export const createScope3CarbonSupplyChainAuditSlide = (
  id = `slide-scope3-carbon-${Date.now()}`
): Scope3CarbonSupplyChainAuditSlideData => {
  const auditPhases = [
    {
      id: 'phase-01',
      stepIndex: 1,
      phaseName: 'Tier-1 Supplier Bill of Materials Ingestion',
      ghgProtocolScope: 'Scope 3 Category 1',
      emissionTonsCo2e: 42000,
      supplierCoveragePercentage: 96.5,
      reductionTargetPercentage: 15.0,
      isPhaseActive: true,
      isPhaseAudited: true,
      reportingStandards: ['GHG Protocol Corporate Standard', 'Automated EDI Ingestion', 'Supplier Portal'],
    },
    {
      id: 'phase-02',
      stepIndex: 2,
      phaseName: 'Activity-Based Regional Carbon Modeling',
      ghgProtocolScope: 'Scope 3 Category 3 & 4',
      emissionTonsCo2e: 38000,
      supplierCoveragePercentage: 92.0,
      reductionTargetPercentage: 20.0,
      isPhaseActive: false,
      isPhaseAudited: true,
      reportingStandards: ['DEFRA 2026 Emission Factors', 'Localized Grid Intensity', 'Real-time Telemetry'],
    },
    {
      id: 'phase-03',
      stepIndex: 3,
      phaseName: 'Decarbonization Hotspot Remediation',
      ghgProtocolScope: 'Scope 3 Category 4 & 9',
      emissionTonsCo2e: 24000,
      supplierCoveragePercentage: 88.0,
      reductionTargetPercentage: 28.0,
      isPhaseActive: false,
      isPhaseAudited: false,
      reportingStandards: ['Green Freight Transition', 'Low-Carbon Aluminum Mandate', 'Supplier Scorecards'],
    },
    {
      id: 'phase-04',
      stepIndex: 4,
      phaseName: 'CSRD Digital Product Passport Attestation',
      ghgProtocolScope: 'Scope 3 Category 11 & 12',
      emissionTonsCo2e: 14000,
      supplierCoveragePercentage: 98.0,
      reductionTargetPercentage: 35.0,
      isPhaseActive: false,
      isPhaseAudited: false,
      reportingStandards: ['EU CSRD E1 Mandate', 'Third-Party PwC Attestation', 'Immutable Blockchain Hash'],
    },
  ];

  return {
    id,
    type: 'scope3-carbon-supply-chain-audit',
    title: 'Scope 3 Carbon Supply Chain Audit & CBAM Compliance',
    kicker: 'ENTERPRISE ESG & SUSTAINABILITY',
    subtitle: 'Automated Tier-1/2 supplier emissions ledger, activity carbon modeling, and CSRD readiness',
    reportingFiscalYear: 'FY2026',
    totalBaselineCo2eTons: 145000,
    currentYearCo2eTons: 118000,
    chiefSustainabilityOfficer: 'Dr. Clara Hensley',
    hasSensorTelemetry: true,
    isScope3Audited: true,
    isCbamCompliant: true,
    hasOffsetsVerified: true,
    auditPhases,
    stages: auditPhases,
    activeStep: 1,
    maxSteps: 4,
  };
};

export const createCspmCiemCloudEntitlementGraphSlide = (
  id = `slide-cspm-ciem-${Date.now()}`
): CspmCiemCloudEntitlementGraphSlideData => {
  return {
    id,
    type: 'cspm-ciem-cloud-entitlement-graph',
    title: 'CSPM & CIEM Cloud Entitlement Graph',
    kicker: 'CLOUD IDENTITY TELEMETRY',
    subtitle: 'Multi-cloud identity governance and least-privilege risk topology',
    cloudAccountsMonitored: 128,
    totalIdentitiesAnalyzed: 14820,
    effectivePermissionsEvaluated: '2.4M',
    chiefInformationSecurityOfficer: 'Dr. Elena Rostova',
    isLeastPrivilegeEnforced: true,
    hasZeroCriticalPaths: true,
    isAutomatedRemediationActive: true,
    entitlementMetrics: [
      {
        id: 'IAM-ROLE-901',
        metricLabel: 'Over-Privileged Prod Roles',
        metricValue: '18 Roles',
        deltaPercentage: -42.5,
        riskTier: 'CRITICAL',
        affectedIdentitiesCount: 142,
        isCompliant: false,
        hasOverPrivilegeWarning: true,
      },
      {
        id: 'STS-TOKEN-402',
        metricLabel: 'Ephemeral Token Drift',
        metricValue: '0.04%',
        deltaPercentage: -88.0,
        riskTier: 'LOW',
        affectedIdentitiesCount: 4,
        isCompliant: true,
        hasOverPrivilegeWarning: false,
      },
      {
        id: 'SVC-ACCT-115',
        metricLabel: 'Dormant Service Accounts',
        metricValue: '6 Keys',
        deltaPercentage: -65.0,
        riskTier: 'HIGH',
        affectedIdentitiesCount: 6,
        isCompliant: false,
        hasOverPrivilegeWarning: true,
      },
      {
        id: 'TOXIC-PATH-08',
        metricLabel: 'Toxic Privilege Escalation Paths',
        metricValue: '0 Paths',
        deltaPercentage: -100.0,
        riskTier: 'LOW',
        affectedIdentitiesCount: 0,
        isCompliant: true,
        hasOverPrivilegeWarning: false,
      },
    ],
    activeStep: 1,
    maxSteps: 1,
  };
};

export const createConfidentialComputingEnclaveSlide = (
  id = `slide-confidential-enclave-${Date.now()}`
): ConfidentialComputingEnclaveSlideData => {
  return {
    id,
    type: 'confidential-computing-enclave',
    title: 'Confidential Computing Enclave Attestation',
    kicker: 'HARDWARE CONFIDENTIAL COMPUTING',
    subtitle: 'Cryptographic memory isolation and zero-trust silicon attestation topology',
    hardwareArchitecture: 'x86-64 / AMD EPYC 9654',
    chipsetVendor: 'AMD SEV-SNP Gen3',
    trustedExecutionEnvironment: 'Sovereign Enclave Fabric',
    firmwareVersion: 'v1.48.0-SEV',
    isMemoryEncrypted: true,
    hasHardwareRootOfTrust: true,
    isAttestationVerified: true,
    hasSecureKeyReleased: true,
    enclaveMetrics: [
      {
        id: 'ENC-01',
        enclaveName: 'AI Model Weights Vault',
        isolationProtocol: 'AMD SEV-SNP',
        memoryEncryptedGb: 256,
        pkiAttestationHash: '0x9fa48c2b1e47d90f38b4e7a1',
        cpuOverheadPercentage: 2.1,
        isEnclaveActive: true,
        isHardwareProtected: true,
      },
      {
        id: 'ENC-02',
        enclaveName: 'Healthcare Telemetry Core',
        isolationProtocol: 'Intel TDX',
        memoryEncryptedGb: 128,
        pkiAttestationHash: '0x7e83d1c92a64b58f01e2a9b4',
        cpuOverheadPercentage: 1.8,
        isEnclaveActive: true,
        isHardwareProtected: true,
      },
      {
        id: 'ENC-03',
        enclaveName: 'Ledger Settlement Core',
        isolationProtocol: 'AWS Nitro Enclaves',
        memoryEncryptedGb: 64,
        pkiAttestationHash: '0x3c91a7e4b2d8f60a91e5c2b7',
        cpuOverheadPercentage: 1.2,
        isEnclaveActive: true,
        isHardwareProtected: true,
      },
      {
        id: 'ENC-04',
        enclaveName: 'Biometric Hash Key Store',
        isolationProtocol: 'AMD SEV-SNP',
        memoryEncryptedGb: 32,
        pkiAttestationHash: '0x5b29f0e1c8d7a46b93e1a8f2',
        cpuOverheadPercentage: 0.9,
        isEnclaveActive: true,
        isHardwareProtected: true,
      },
    ],
    activeStep: 1,
    maxSteps: 1,
  };
};

export const createPredictiveAutoscalingPodMatrixSlide = (
  id = `slide-predictive-autoscaling-${Date.now()}`
): PredictiveAutoscalingPodMatrixSlideData => {
  return {
    id,
    type: 'predictive-autoscaling-pod-matrix',
    title: 'Predictive Autoscaling Pod Matrix',
    kicker: 'KUBERNETES FLEET OPTIMIZATION',
    subtitle: 'Real-time machine learning workload forecasting and proactive pod scaling',
    forecastHorizonHours: 24,
    totalManagedPods: 8400,
    mlInferenceIntervalSec: 15,
    spotInstanceRatioPercentage: 78,
    isPredictiveModelActive: true,
    hasSpotFallback: true,
    isZeroColdStartGuaranteed: true,
    autoscalingMetrics: [
      {
        id: 'POD-CLUSTER-01',
        workloadCluster: 'Ingress API Gateway Tier',
        currentReplicas: 340,
        predictedReplicas: 520,
        leadTimeMinutes: 12,
        costEfficiencyPercentage: 44.8,
        isScalingActive: true,
        isPredictionAccurate: true,
      },
      {
        id: 'POD-CLUSTER-02',
        workloadCluster: 'Neural Vector Embedding Mesh',
        currentReplicas: 180,
        predictedReplicas: 290,
        leadTimeMinutes: 15,
        costEfficiencyPercentage: 52.1,
        isScalingActive: true,
        isPredictionAccurate: true,
      },
      {
        id: 'POD-CLUSTER-03',
        workloadCluster: 'Checkout & Settlement Core',
        currentReplicas: 120,
        predictedReplicas: 180,
        leadTimeMinutes: 8,
        costEfficiencyPercentage: 38.6,
        isScalingActive: true,
        isPredictionAccurate: true,
      },
      {
        id: 'POD-CLUSTER-04',
        workloadCluster: 'Async Media Transcoding Swarm',
        currentReplicas: 90,
        predictedReplicas: 210,
        leadTimeMinutes: 20,
        costEfficiencyPercentage: 61.4,
        isScalingActive: true,
        isPredictionAccurate: true,
      },
    ],
    activeStep: 1,
    maxSteps: 1,
  };
};

export const createCapexOpexCapitalAllocationSlide = (
  id = `slide-capex-opex-${Date.now()}`
): CapexOpexCapitalAllocationSlideData => {
  return {
    id,
    type: 'capex-opex-capital-allocation',
    title: 'Capex vs Opex Capital Allocation Tranches',
    kicker: 'STRATEGIC CAPITAL DEPLOYMENT',
    subtitle: 'Multi-tranche enterprise investment hurdle rates and depreciation governance',
    fiscalYear: 'FY2027',
    totalCapitalEnvelopeMln: 850,
    hurdleRatePercentage: 14.5,
    chiefFinancialOfficer: 'Marcus Sterling',
    isHurdleRateExceeded: true,
    hasPositiveFreeCashFlow: true,
    isDepreciationScheduleOnTrack: true,
    allocationTranches: [
      {
        id: 'TRANCHE-01',
        trancheName: 'Sovereign GPU Cluster Expansion',
        allocationCategory: 'CAPEX',
        allocatedAmountMln: 320.0,
        projectedIrrPercentage: 28.5,
        paybackPeriodYears: 2.4,
        isTrancheFunded: true,
        hasBoardApproval: true,
      },
      {
        id: 'TRANCHE-02',
        trancheName: 'Global Edge PoP Fiber Backhaul',
        allocationCategory: 'CAPEX',
        allocatedAmountMln: 180.0,
        projectedIrrPercentage: 21.4,
        paybackPeriodYears: 3.1,
        isTrancheFunded: true,
        hasBoardApproval: true,
      },
      {
        id: 'TRANCHE-03',
        trancheName: 'Core Platform R&D Modernization',
        allocationCategory: 'R&D',
        allocatedAmountMln: 210.0,
        projectedIrrPercentage: 34.0,
        paybackPeriodYears: 1.8,
        isTrancheFunded: true,
        hasBoardApproval: true,
      },
      {
        id: 'TRANCHE-04',
        trancheName: 'Strategic AI Talent & M&A Reserve',
        allocationCategory: 'M&A',
        allocatedAmountMln: 140.0,
        projectedIrrPercentage: 24.8,
        paybackPeriodYears: 2.8,
        isTrancheFunded: true,
        hasBoardApproval: true,
      },
    ],
    activeStep: 1,
    maxSteps: 1,
  };
};

export const createTransferPricingTaxTopologySlide = (
  id = `slide-transfer-pricing-${Date.now()}`
): TransferPricingTaxTopologySlideData => {
  return {
    id,
    type: 'transfer-pricing-tax-topology',
    title: 'Transfer Pricing Tax Topology',
    kicker: 'GLOBAL TRANSFER PRICING LEDGER',
    subtitle: 'OECD BEPS Pillar 2 statutory tax harmonization and cross-border IP valuation',
    headquartersJurisdiction: 'Dublin, Ireland',
    globalEffectiveTaxRatePercentage: 16.2,
    statutoryPillar2MinRatePercentage: 15.0,
    taxCounselPartner: 'Clifford Chance LLP',
    isBepsPillar2Compliant: true,
    hasArmsLengthPricing: true,
    isAuditDefensible: true,
    jurisdictionTaxNodes: [
      {
        id: 'TAX-NODE-IRL',
        jurisdictionCountry: 'Ireland (Core IP HoldCo)',
        countryCode: 'IRL',
        effectiveTaxRatePercentage: 15.0,
        intercompanyVolumeMln: 420.0,
        pricingMethodology: 'TNMM (Transactional Net Margin)',
        isOecdCompliant: true,
        hasLocalSubstance: true,
      },
      {
        id: 'TAX-NODE-USA',
        jurisdictionCountry: 'United States (Commercial Hub)',
        countryCode: 'USA',
        effectiveTaxRatePercentage: 21.0,
        intercompanyVolumeMln: 280.0,
        pricingMethodology: 'CUP (Comparable Uncontrolled)',
        isOecdCompliant: true,
        hasLocalSubstance: true,
      },
      {
        id: 'TAX-NODE-SGP',
        jurisdictionCountry: 'Singapore (APAC Regional HQ)',
        countryCode: 'SGP',
        effectiveTaxRatePercentage: 15.0,
        intercompanyVolumeMln: 195.0,
        pricingMethodology: 'Cost Plus Method (Markup 12%)',
        isOecdCompliant: true,
        hasLocalSubstance: true,
      },
      {
        id: 'TAX-NODE-DEU',
        jurisdictionCountry: 'Germany (Engineering Center)',
        countryCode: 'DEU',
        effectiveTaxRatePercentage: 29.8,
        intercompanyVolumeMln: 140.0,
        pricingMethodology: 'Profit Split Method',
        isOecdCompliant: true,
        hasLocalSubstance: true,
      },
    ],
    activeStep: 1,
    maxSteps: 1,
  };
};

export const createSalesQuotaCompensationMatrixSlide = (
  id = `slide-sales-quota-${Date.now()}`
): SalesQuotaCompensationMatrixSlideData => {
  return {
    id,
    type: 'sales-quota-compensation-matrix',
    title: 'Sales Quota & Compensation Attainment Matrix',
    kicker: 'ENTERPRISE REVENUE ENGINE',
    subtitle: 'Individual quota attainment tiers, accelerator triggers, and commission distributions',
    fiscalQuarter: 'Q3 FY2026',
    totalTeamQuotaMln: 45.0,
    blendedAttainmentPercentage: 118.5,
    chiefRevenueOfficer: 'Sarah Jenkins',
    isTeamQuotaAttained: true,
    hasAcceleratorsActive: true,
    isPipelineCoverageHealthy: true,
    salesReps: [
      {
        id: 'REP-01',
        repName: 'Alex Rivera',
        salesRegion: 'North America Enterprise',
        annualQuotaMln: 14.0,
        attainmentPercentage: 142,
        closedWonMln: 19.8,
        pipelineCoverageRatio: 4.2,
        isPresidentClubQualified: true,
        hasOverageAccelerator: true,
      },
      {
        id: 'REP-02',
        repName: 'Mei-Ling Chen',
        salesRegion: 'APAC Strategic Accounts',
        annualQuotaMln: 12.0,
        attainmentPercentage: 128,
        closedWonMln: 15.3,
        pipelineCoverageRatio: 3.8,
        isPresidentClubQualified: true,
        hasOverageAccelerator: true,
      },
      {
        id: 'REP-03',
        repName: 'Liam Gallagher',
        salesRegion: 'EMEA Sovereign Sector',
        annualQuotaMln: 11.0,
        attainmentPercentage: 115,
        closedWonMln: 12.6,
        pipelineCoverageRatio: 3.5,
        isPresidentClubQualified: true,
        hasOverageAccelerator: false,
      },
      {
        id: 'REP-04',
        repName: 'Sofia Rossi',
        salesRegion: 'LATAM Emerging Tech',
        annualQuotaMln: 8.0,
        attainmentPercentage: 98,
        closedWonMln: 7.8,
        pipelineCoverageRatio: 3.1,
        isPresidentClubQualified: false,
        hasOverageAccelerator: false,
      },
    ],
    activeStep: 1,
    maxSteps: 1,
  };
};

export const createExecutiveSuccessionLeadershipBenchSlide = (
  id = `slide-executive-succession-${Date.now()}`
): ExecutiveSuccessionLeadershipBenchSlideData => {
  return {
    id,
    type: 'executive-succession-leadership-bench',
    title: 'Executive Succession & Leadership Bench',
    kicker: 'BOARDROOM GOVERNANCE & TALENT',
    subtitle: 'Nine-box grid leadership readiness, emergency transition protocols, and talent retention',
    governanceReviewDate: 'Q4 2026',
    emergencySuccessionCoveragePercentage: 100,
    retentionBudgetMln: 18.0,
    chairCompensationCommittee: 'Lord Alistair Vance',
    isImmediateSuccessorIdentified: true,
    hasRetentionPlanActive: true,
    isQuorumApproved: true,
    successionRoles: [
      {
        id: 'ROLE-01',
        executiveRole: 'Chief Software Engineer',
        incumbentName: 'Alim Ul Karim',
        readyNowCandidateName: 'Tariq Al-Mansoor',
        readinessHorizonMonths: 0,
        benchDepthCount: 3,
        isSuccessorReady: true,
        hasRetentionIncentive: true,
      },
      {
        id: 'ROLE-02',
        executiveRole: 'Chief Information Security Officer',
        incumbentName: 'Dr. Elena Rostova',
        readyNowCandidateName: 'Kavita Raman',
        readinessHorizonMonths: 6,
        benchDepthCount: 2,
        isSuccessorReady: true,
        hasRetentionIncentive: true,
      },
      {
        id: 'ROLE-03',
        executiveRole: 'Chief Financial Officer',
        incumbentName: 'Marcus Sterling',
        readyNowCandidateName: 'David H. Brooks',
        readinessHorizonMonths: 0,
        benchDepthCount: 3,
        isSuccessorReady: true,
        hasRetentionIncentive: true,
      },
      {
        id: 'ROLE-04',
        executiveRole: 'Chief Revenue Officer',
        incumbentName: 'Sarah Jenkins',
        readyNowCandidateName: 'Camilla Vasquez',
        readinessHorizonMonths: 12,
        benchDepthCount: 2,
        isSuccessorReady: false,
        hasRetentionIncentive: true,
      },
    ],
    activeStep: 1,
    maxSteps: 1,
  };
};

export const CUSTOMIZATION_FACTORIES: Record<string, (id?: string) => CustomizationSlideData> = {
  'neural-vector-search-topology': createNeuralVectorSearchTopologySlide,
  'model-quantization-speculative-decoding': createModelQuantizationSpeculativeDecodingSlide,
  'llm-firewall-red-team-matrix': createLlmFirewallRedTeamMatrixSlide,
  'global-anycast-traffic-director': createGlobalAnycastTrafficDirectorSlide,
  'cqrs-event-sourcing-fabric': createCqrsEventSourcingFabricSlide,
  'sbom-slsa-provenance-attestation': createSbomSlsaProvenanceAttestationSlide,
  'post-merger-integration-roadmap': createPostMergerIntegrationRoadmapSlide,
  'scope3-carbon-supply-chain-audit': createScope3CarbonSupplyChainAuditSlide,
  'cspm-ciem-cloud-entitlement-graph': createCspmCiemCloudEntitlementGraphSlide,
  'confidential-computing-enclave': createConfidentialComputingEnclaveSlide,
  'predictive-autoscaling-pod-matrix': createPredictiveAutoscalingPodMatrixSlide,
  'capex-opex-capital-allocation': createCapexOpexCapitalAllocationSlide,
  'transfer-pricing-tax-topology': createTransferPricingTaxTopologySlide,
  'sales-quota-compensation-matrix': createSalesQuotaCompensationMatrixSlide,
  'executive-succession-leadership-bench': createExecutiveSuccessionLeadershipBenchSlide,
};

export const createCustomizationSlide = (
  type: CustomizationSlideType,
  id = `slide-${type}-${Date.now()}`
): CustomizationSlideData => {
  const factory = CUSTOMIZATION_FACTORIES[type];
  if (factory) {
    return factory(id);
  }
  return createNeuralVectorSearchTopologySlide(id);
};
