// lint-allow: file-size reason="Production default templates 1 to 8 for flat global suite slide archetypes" max=450
import type {
  InteractiveBranchingCloseSlideData,
  BeforeAfterShowcasePanSlideData,
  SearchSerpProofLightboxSlideData,
  CognitiveInversionPunchlineSlideData,
  TalentPyramidFunnelSvgSlideData,
  HexagonalTechClusterSlideData,
  ConnectedRoadmapRailPulseSlideData,
  CampaignPerformanceLightboxSlideData,
} from '../types/flatGlobalSuiteTypes';

export const DEFAULT_BRANCHING_CLOSE_DATA: Omit<InteractiveBranchingCloseSlideData, 'id'> = {
  type: 'interactive-branching-close',
  title: 'Strategic Inflection Point: Two Divergent Architectures',
  kicker: 'EXECUTIVE DECISION GATEWAY',
  subtitle: 'Evaluate the high-scale distributed path versus legacy containment',
  headline: 'Will You Authorize Global Autonomous Deployment?',
  promptQuestion: 'Select an execution trajectory to proceed with deployment verification',
  decisionContext: 'Autonomous rollback is active across all regional clusters with sub-10ms failover.',
  yesOption: {
    label: 'Authorize Autonomous Global Rollout',
    description: 'Deploy real-time mesh with multi-region zero-trust consensus and sub-10ms routing.',
    targetSlideId: 'slide-rollout-success',
    badge: 'RECOMMENDED (Y)',
  },
  noOption: {
    label: 'Retain Monolithic Quarantine',
    description: 'Defer sovereign edge deployment and maintain existing centralized database locks.',
    targetSlideId: 'slide-monolith-scarcity',
    badge: 'CONSERVATIVE (N)',
  },
  yesTargetSlideId: 'slide-rollout-success',
  noTargetSlideId: 'slide-monolith-scarcity',
  branches: [
    {
      id: 'branch-y',
      keyTrigger: 'y',
      choiceLabel: 'Authorize Autonomous Mesh',
      actionSummary: 'Triggers global canary promotion across 24 edge nodes',
      targetSlideId: 'slide-rollout-success',
      isRecommendedOption: true,
    },
    {
      id: 'branch-n',
      keyTrigger: 'n',
      choiceLabel: 'Retain Monolith Lockdown',
      actionSummary: 'Freezes deployment pipeline and schedules security review',
      targetSlideId: 'slide-monolith-scarcity',
      isRecommendedOption: false,
    },
  ],
  scarcityWarning: 'Quarantine window closes in 48 hours before automated resource re-allocation.',
  isBranchingEnabled: true,
  hasKeyboardHints: true,
  executivePresenter: 'Alim Ul Karim, Chief Software Engineer',
  activeStep: 0,
  maxSteps: 2,
};

export const DEFAULT_BEFORE_AFTER_PAN_DATA: Omit<BeforeAfterShowcasePanSlideData, 'id'> = {
  type: 'before-after-showcase-pan',
  title: 'Architecture Evolution: Legacy Monolith vs Sovereign Mesh',
  kicker: 'TRANSFORMATION COMPARISON',
  subtitle: 'Direct operational telemetry comparing synchronous locks with distributed event fabric',
  beforeHeadline: 'Synchronous Legacy Bottleneck',
  afterHeadline: 'Autonomous Event Mesh',
  beforeMetricSummary: '1,420ms p99 Latency | 34% Failure Cascade Rate',
  afterMetricSummary: '4.2ms p99 Latency | 99.999% Fault Containment',
  panItems: [
    {
      id: 'pan-1',
      featureTitle: 'Database Sharding & Locks',
      beforeStateText: 'Global write locks blocking cross-region transactions',
      afterStateText: 'Distributed Raft state engine with zero write contention',
      deltaMetric: '330x faster writes',
      isHighlighted: true,
    },
    {
      id: 'pan-2',
      featureTitle: 'API Gateway Ingress',
      beforeStateText: 'Single ingress bottleneck causing cascading HTTP 504 timeouts',
      afterStateText: 'Anycast BGP edge routing resolving at nearest metro PoP',
      deltaMetric: '99.4% latency drop',
      isHighlighted: true,
    },
    {
      id: 'pan-3',
      featureTitle: 'Deployment Cadence',
      beforeStateText: 'Bi-weekly high-risk midnight deployments with manual rollbacks',
      afterStateText: 'Continuous automated canary releases with autonomous rollback',
      deltaMetric: '48 deployments / day',
      isHighlighted: false,
    },
  ],
  splitPercentage: 50,
  hasLivePanControl: true,
  isComparisonActive: true,
  activeStep: 0,
  maxSteps: 3,
};

export const DEFAULT_SEARCH_SERP_LIGHTBOX_DATA: Omit<SearchSerpProofLightboxSlideData, 'id'> = {
  type: 'search-serp-proof-lightbox',
  title: 'Global Organic Visibility & SERP Authority Proof',
  kicker: 'MARKET DOMINANCE VERIFICATION',
  subtitle: 'Live search engine validation and verifiable top-tier ranking positions',
  searchQueryPhrase: 'enterprise autonomous presentation engine architecture',
  searchEngineName: 'Google Search Enterprise Index',
  totalResultsIndexed: '4,820,000',
  searchExecutionDurationMs: 180,
  proofItems: [
    {
      id: 'serp-1',
      searchRank: 1,
      resultTitle: 'White Presentation Engine - High Authority 60FPS Presentation Stack',
      destinationUrl: 'https://presentation.enterprise.io/white-engine',
      snippetText: 'The canonical zero-dependency presentation framework featuring 16:9 DOM rendering, tactile audio engine, and 60+ enterprise archetypes.',
      verificationBadge: 'RANK #1 - VERIFIED KNOWLEDGE GRAPH',
      previewImageUrl: '/assets/screenshots/serp-rank1.png',
      isVerifiedAuthority: true,
      hasLightboxPreview: true,
    },
    {
      id: 'serp-2',
      searchRank: 2,
      resultTitle: 'Autonomous Presentation Architecture - Alim Ul Karim, Chief Software Engineer',
      destinationUrl: 'https://architecture.enterprise.io/autonomous-deck',
      snippetText: 'Engineering whitepaper detailing state management, step progression math, and tactile web audio synthesis.',
      verificationBadge: 'FEATURED CITATION',
      previewImageUrl: '/assets/screenshots/serp-rank2.png',
      isVerifiedAuthority: true,
      hasLightboxPreview: true,
    },
    {
      id: 'serp-3',
      searchRank: 3,
      resultTitle: 'Enterprise Kinetic Slide Suite Benchmark Report',
      destinationUrl: 'https://benchmarks.enterprise.io/presentation-kinetic',
      snippetText: 'Independent benchmark analyzing rendering speed, GPU compositing pipelines, and memory footprints.',
      verificationBadge: 'INDEPENDENT AUDIT',
      isVerifiedAuthority: true,
      hasLightboxPreview: false,
    },
  ],
  isLightboxActive: false,
  hasOrganicDominance: true,
  isVerificationGuaranteed: true,
  activeStep: 0,
  maxSteps: 3,
};

export const DEFAULT_COGNITIVE_INVERSION_DATA: Omit<CognitiveInversionPunchlineSlideData, 'id'> = {
  type: 'cognitive-inversion-punchline',
  title: 'Cognitive Inversion: Why More Slides Accelerate Decisions',
  kicker: 'STRATEGIC INTELLECTUAL FRAMEWORK',
  subtitle: 'Inverting conventional presentation assumptions to unlock executive consensus',
  conventionalWisdom: 'Presentations must be compressed into 5 generic summary slides to respect executive attention.',
  counterIntuitiveThesis: 'Compression increases ambiguity, slows decisions, and conceals architectural debt.',
  punchlineStatement: 'High-density, modular flat slides eliminate follow-up meetings by delivering immediate empirical clarity.',
  authorAttribution: 'Alim Ul Karim, Chief Software Engineer',
  inversionPillars: [
    {
      id: 'pillar-1',
      conventionalPremise: 'Fewer slides save executive time',
      invertedReality: 'Sparse slides generate 4 additional review meetings to clarify ambiguity',
      breakthroughMetric: '75% reduction in meeting cycles',
      isPillarRevealed: true,
    },
    {
      id: 'pillar-2',
      conventionalPremise: 'High-level abstracts suffice for signoff',
      invertedReality: 'Absence of verifiable architecture leads to post-launch governance rejections',
      breakthroughMetric: '100% first-pass executive signoff',
      isPillarRevealed: true,
    },
    {
      id: 'pillar-3',
      conventionalPremise: 'Bullet points communicate effectively',
      invertedReality: 'Structured semantic data cards provide 4x faster cognitive absorption',
      breakthroughMetric: '4.2x cognitive retention',
      isPillarRevealed: true,
    },
  ],
  hasDramaticReveal: true,
  isPunchlineHighlighted: true,
  activeStep: 0,
  maxSteps: 3,
};

export const DEFAULT_TALENT_PYRAMID_FUNNEL_SVG_DATA: Omit<TalentPyramidFunnelSvgSlideData, 'id'> = {
  type: 'talent-pyramid-funnel-svg',
  title: 'Engineering Talent Pyramid & Extreme Vetting Funnel',
  kicker: 'ORGANIZATIONAL CRAFTSMANSHIP',
  subtitle: 'Mathematically rigorous hiring criteria selecting the top 0.4% of engineering talent',
  totalCandidatesEvaluated: '14,200 Applicants',
  finalHiredCount: '58 Staff Engineers',
  acceptanceRatePercentage: 0.41,
  chiefSoftwareEngineer: 'Alim Ul Karim',
  funnelTiers: [
    {
      id: 'tier-1',
      tierLevel: 1,
      tierName: 'Algorithmic & Systems Pre-Screen',
      candidateVolume: '14,200 candidates',
      passRatePercentage: 18.2,
      vettingGateSummary: 'Autonomous coding evaluation covering concurrent data structures and cache locality.',
      isApexTier: false,
    },
    {
      id: 'tier-2',
      tierLevel: 2,
      tierName: 'Distributed Systems Deep Architecture',
      candidateVolume: '2,580 candidates',
      passRatePercentage: 12.5,
      vettingGateSummary: 'Live architecture defense on split-brain recovery and Raft consensus protocols.',
      isApexTier: false,
    },
    {
      id: 'tier-3',
      tierLevel: 3,
      tierName: 'Zero-Allocation Code Craftsmanship',
      candidateVolume: '322 candidates',
      passRatePercentage: 24.8,
      vettingGateSummary: 'Hands-on kernel telemetry, SIMD profiling, and strict memory leak diagnostics.',
      isApexTier: false,
    },
    {
      id: 'tier-4',
      tierLevel: 4,
      tierName: 'Chief Software Engineer Executive Review',
      candidateVolume: '80 finalists',
      passRatePercentage: 72.5,
      vettingGateSummary: 'Final bar-raiser defense with Alim Ul Karim on leadership principles and system ownership.',
      isApexTier: true,
    },
  ],
  isSvgRendered: true,
  hasPrecisionFiltering: true,
  activeStep: 0,
  maxSteps: 4,
};

export const DEFAULT_HEXAGONAL_TECH_CLUSTER_DATA: Omit<HexagonalTechClusterSlideData, 'id'> = {
  type: 'hexagonal-tech-cluster',
  title: 'Hexagonal Microservices Fabric & Capability Mesh',
  kicker: 'TECHNICAL TOPOLOGY',
  subtitle: 'Decoupled bounded contexts communicating over zero-trust mutual TLS links',
  clusterCenterTitle: 'Core Nexus Orchestrator',
  clusterSubtitle: 'Sub-millisecond event routing and policy validation',
  totalNodesCount: 7,
  clusterNodes: [
    { id: 'hex-1', nodeName: 'Event Bus', stackCategory: 'Messaging', nodeIcon: 'Zap', connectivityScore: 98, isCoreHub: true, isNodeActive: true },
    { id: 'hex-2', nodeName: 'Auth Gateway', stackCategory: 'Security', nodeIcon: 'Shield', connectivityScore: 95, isCoreHub: false, isNodeActive: true },
    { id: 'hex-3', nodeName: 'State Ledger', stackCategory: 'Database', nodeIcon: 'Database', connectivityScore: 92, isCoreHub: false, isNodeActive: true },
    { id: 'hex-4', nodeName: 'Inference Pod', stackCategory: 'Compute', nodeIcon: 'Cpu', connectivityScore: 94, isCoreHub: false, isNodeActive: true },
    { id: 'hex-5', nodeName: 'Audio Synth', stackCategory: 'Media', nodeIcon: 'Volume2', connectivityScore: 88, isCoreHub: false, isNodeActive: true },
    { id: 'hex-6', nodeName: 'Telemetry Sink', stackCategory: 'Observability', nodeIcon: 'Activity', connectivityScore: 91, isCoreHub: false, isNodeActive: true },
    { id: 'hex-7', nodeName: 'Edge CDN', stackCategory: 'Network', nodeIcon: 'Globe', connectivityScore: 96, isCoreHub: false, isNodeActive: true },
  ],
  clusterConnections: [
    { sourceNodeId: 'hex-1', targetNodeId: 'hex-2', protocolName: 'gRPC mTLS', isEncryptedChannel: true },
    { sourceNodeId: 'hex-1', targetNodeId: 'hex-3', protocolName: 'ZeroMQ IPC', isEncryptedChannel: true },
    { sourceNodeId: 'hex-1', targetNodeId: 'hex-4', protocolName: 'QUIC Stream', isEncryptedChannel: true },
    { sourceNodeId: 'hex-1', targetNodeId: 'hex-5', protocolName: 'WebAudio SharedArray', isEncryptedChannel: true },
    { sourceNodeId: 'hex-1', targetNodeId: 'hex-6', protocolName: 'Kafka MirrorMaker', isEncryptedChannel: true },
    { sourceNodeId: 'hex-1', targetNodeId: 'hex-7', protocolName: 'BGP Anycast', isEncryptedChannel: true },
  ],
  isHoneycombRendered: true,
  hasPulsingConnections: true,
  activeStep: 0,
  maxSteps: 4,
};

export const DEFAULT_CONNECTED_ROADMAP_RAIL_PULSE_DATA: Omit<ConnectedRoadmapRailPulseSlideData, 'id'> = {
  type: 'connected-roadmap-rail-pulse',
  title: 'Connected Engineering Roadmap & Active Pulse Rail',
  kicker: 'STRATEGIC EXECUTION HORIZON',
  subtitle: 'Telemetry-linked delivery milestones with real-time sprint pulse indicators',
  currentActiveQuarter: 'Q3 2026',
  overallVelocityScore: '98.4% On Schedule',
  railNodes: [
    {
      id: 'rail-1',
      stepIndex: 1,
      milestoneTitle: 'Foundation Architecture & Core Shims',
      targetQuarter: 'Q1 2026',
      operationalStatus: 'completed',
      pulseIntensity: 'low',
      keyDeliverables: ['Split-DB SQLite Engine', 'Base Presentation Types', 'Synthesized WebAudio Sound Engine'],
      isNodePulsing: false,
    },
    {
      id: 'rail-2',
      stepIndex: 2,
      milestoneTitle: 'Enterprise Kinetic & Global Suites',
      targetQuarter: 'Q2 2026',
      operationalStatus: 'completed',
      pulseIntensity: 'medium',
      keyDeliverables: ['34 Extended Slide Archetypes', 'Spring Motion Physics Engine', 'Dark/Light Contrast Token System'],
      isNodePulsing: false,
    },
    {
      id: 'rail-3',
      stepIndex: 3,
      milestoneTitle: 'Flat Customization & Decision Branching',
      targetQuarter: 'Q3 2026',
      operationalStatus: 'in-progress',
      pulseIntensity: 'high',
      keyDeliverables: ['15 Flat Global Suite Archetypes', 'Interactive Keyboard Branching', 'Zero-Allocation Step Progression Engine'],
      isNodePulsing: true,
    },
    {
      id: 'rail-4',
      stepIndex: 4,
      milestoneTitle: 'Autonomous Multi-Agent AI Presenter',
      targetQuarter: 'Q4 2026',
      operationalStatus: 'upcoming',
      pulseIntensity: 'low',
      keyDeliverables: ['Voice-Driven Hotkey Orchestrator', 'Dynamic Audience Telemetry', 'Zero-Latency Live Slide Synthesis'],
      isNodePulsing: false,
    },
  ],
  hasActivePulseRail: true,
  isProgressionConnected: true,
  activeStep: 2,
  maxSteps: 4,
};

export const DEFAULT_CAMPAIGN_PERFORMANCE_LIGHTBOX_DATA: Omit<CampaignPerformanceLightboxSlideData, 'id'> = {
  type: 'campaign-performance-lightbox',
  title: 'Global Go-To-Market Campaign & Acquisition Lightbox',
  kicker: 'COMMERCIAL ACCELERATION',
  subtitle: 'Attribution modeling, creative conversion performance, and omnichannel CAC returns',
  campaignName: 'Q3 Enterprise Autonomous Platform Launch',
  campaignDuration: '90-Day Global Ingress Window',
  totalAdSpend: '$480,000',
  totalGeneratedRevenue: '$3,840,000',
  performanceChannels: [
    { id: 'ch-1', channelName: 'Developer Documentation Sponsorship', budgetAllocation: '$140,000', conversionsCount: 1420, roasMultiplier: '9.4x', isTopPerformer: true },
    { id: 'ch-2', channelName: 'Technical Keynote Live Stream', budgetAllocation: '$180,000', conversionsCount: 2840, roasMultiplier: '8.8x', isTopPerformer: true },
    { id: 'ch-3', channelName: 'Direct Enterprise Executive Briefings', budgetAllocation: '$160,000', conversionsCount: 68, roasMultiplier: '7.2x', isTopPerformer: false },
  ],
  lightboxCreatives: [
    { id: 'cr-1', creativeTitle: 'Interactive Architecture Live Demo', mediaAssetUrl: '/assets/screenshots/campaign-demo.png', conversionRatePercentage: 14.8, isFeaturedAsset: true },
    { id: 'cr-2', creativeTitle: 'Chief Software Engineer Keynote Cut', mediaAssetUrl: '/assets/screenshots/hero-speaker-clean.png', conversionRatePercentage: 18.2, isFeaturedAsset: true },
    { id: 'cr-3', creativeTitle: 'Technical Benchmark Comparison Chart', mediaAssetUrl: '/assets/screenshots/benchmark-card.png', conversionRatePercentage: 11.4, isFeaturedAsset: false },
  ],
  hasLightboxPreview: true,
  isCampaignActive: true,
  activeStep: 0,
  maxSteps: 3,
};
