// lint-allow: file-size reason="Production default templates 9 to 15 for flat global suite slide archetypes" max=450
import type {
  ExecutiveRosterKeypadSlideData,
  FlatStepProcessFlowSlideData,
  FlatSplitNarrativeStepperSlideData,
  FlatTimelineMilestoneRailSlideData,
  FlatRevealBentoGridSlideData,
  FlatDepthSentenceStackSlideData,
  FlatTypewriterCodeWalkthroughSlideData,
} from '../types/flatGlobalSuiteTypes';

export const DEFAULT_EXECUTIVE_ROSTER_KEYPAD_DATA: Omit<ExecutiveRosterKeypadSlideData, 'id'> = {
  type: 'executive-roster-keypad',
  title: 'Executive Engineering Leadership Roster',
  kicker: 'EXECUTIVE GOVERNANCE',
  subtitle: 'Direct keypad access to executive bios, domain ownership, and technical credentials',
  activeMemberIndex: 0,
  hasKeypadNavigation: true,
  isRosterInteractive: true,
  rosterMembers: [
    {
      id: 'exec-1',
      keypadIndex: 1,
      name: 'Alim Ul Karim',
      executiveTitle: 'Chief Software Engineer',
      divisionScope: 'Core Systems, Presentation Engine & Autonomous Architecture',
      avatarImageUrl: '/assets/screenshots/hero-speaker-clean.png',
      bioSynopsis: 'Pioneered zero-allocation presentation engines, tactile sound synthesis, and multi-agent coordination protocols across high-scale distributed systems.',
      executiveCredentials: ['Chief Software Engineer', 'Distributed Systems Specialist', 'Autonomous Agent Architect'],
      isLeadPersona: true,
    },
    {
      id: 'exec-2',
      keypadIndex: 2,
      name: 'Elena Rostova',
      executiveTitle: 'Principal Platform Architect',
      divisionScope: 'Edge Network Mesh & Zero-Trust Cloud Infrastructure',
      avatarImageUrl: '/assets/screenshots/roster-platform.png',
      bioSynopsis: 'Directs global anycast ingress, multi-cloud failover matrices, and cryptographic provenance attestation pipelines.',
      executiveCredentials: ['Ph.D. Computer Systems', 'SLSA Level 4 Maintainer', 'Cloud FinOps Fellow'],
      isLeadPersona: false,
    },
    {
      id: 'exec-3',
      keypadIndex: 3,
      name: 'Marcus Vance',
      executiveTitle: 'VP of Product Engineering',
      divisionScope: 'Developer Experience, SDKs & Client Runtime Engines',
      avatarImageUrl: '/assets/screenshots/roster-product.png',
      bioSynopsis: 'Leads customer-facing runtime performance, ergonomic TypeScript typings, and enterprise SLA delivery programs.',
      executiveCredentials: ['15+ Yrs Enterprise DX', 'Open-Source Lead', 'IEEE Fellow'],
      isLeadPersona: false,
    },
    {
      id: 'exec-4',
      keypadIndex: 4,
      name: 'Sophia Chen',
      executiveTitle: 'Chief Information Security Officer',
      divisionScope: 'Cryptographic Enclaves & Autonomous SOC Operations',
      avatarImageUrl: '/assets/screenshots/roster-security.png',
      bioSynopsis: 'Oversees post-quantum migration protocols, automated red teaming harnesses, and confidential computing enclaves.',
      executiveCredentials: ['CISSP Master', 'NIST Cybersecurity Advisor', 'Zero-Trust Architect'],
      isLeadPersona: false,
    },
  ],
  activeStep: 0,
  maxSteps: 4,
};

export const DEFAULT_FLAT_STEP_PROCESS_FLOW_DATA: Omit<FlatStepProcessFlowSlideData, 'id'> = {
  type: 'flat-step-process-flow',
  title: 'Four-Phase Continuous Deployment Process Flow',
  kicker: 'OPERATIONAL METHODOLOGY',
  subtitle: 'Step-by-step sequential verification ensuring zero downtime releases',
  cadenceDescription: 'End-to-end execution window: 4 minutes 30 seconds',
  totalStepsCount: 4,
  processSteps: [
    {
      id: 'step-1',
      stepNumber: 1,
      stepTitle: 'Hermetic Build & Static Analysis',
      stepDescription: 'Compile TypeScript sources and verify strict coding guidelines with zero dependencies.',
      executionDuration: '28s',
      keyDeliverables: ['Zero Lint Violations', 'Strict Positive Booleans', 'Sub-15-line functions'],
      isStepActive: true,
      isStepCompleted: true,
    },
    {
      id: 'step-2',
      stepNumber: 2,
      stepTitle: 'Cryptographic Provenance Attestation',
      stepDescription: 'Sign artifacts using hardware tokens and record Merkle digest to immutable state ledger.',
      executionDuration: '42s',
      keyDeliverables: ['SLSA Provenance Hash', 'SBOM Generation', 'Key Signing Attestation'],
      isStepActive: false,
      isStepCompleted: false,
    },
    {
      id: 'step-3',
      stepNumber: 3,
      stepTitle: 'Canary Deployment & Synthetic Telemetry',
      stepDescription: 'Route 5% of production traffic to isolated edge pods while monitoring error budgets.',
      executionDuration: '90s',
      keyDeliverables: ['0.00% Error Rate', '4.2ms P99 Latency', 'Zero Memory Drift'],
      isStepActive: false,
      isStepCompleted: false,
    },
    {
      id: 'step-4',
      stepNumber: 4,
      stepTitle: 'Global Promotion & Traffic Convergence',
      stepDescription: 'Promote container image across all 24 regional edge clusters and retire previous revision.',
      executionDuration: '110s',
      keyDeliverables: ['100% Traffic Promoted', 'Graceful Socket Draining', 'Audit Log Complete'],
      isStepActive: false,
      isStepCompleted: false,
    },
  ],
  isStepByStepProgression: true,
  hasFlatAesthetics: true,
  activeStep: 0,
  maxSteps: 4,
};

export const DEFAULT_FLAT_SPLIT_NARRATIVE_STEPPER_DATA: Omit<FlatSplitNarrativeStepperSlideData, 'id'> = {
  type: 'flat-split-narrative-stepper',
  title: 'Sovereign Architecture: Split Narrative & Technical Proof',
  kicker: 'STRATEGIC ALIGNMENT',
  subtitle: 'Executive storytelling harmonized with concrete technical verification milestones',
  narrativeHeading: 'Why Distributed Autonomy Wins the Enterprise',
  narrativeBodyParagraphs: [
    'Centralized cloud dependencies create catastrophic single points of failure that jeopardize enterprise continuity.',
    'By distributing state across sovereign edge nodes with local SQLite caching, presentations render at 60 FPS offline with zero external network lag.',
    'This architectural shift reduces cloud compute costs by 84% while providing mathematical guarantees of confidentiality.',
  ],
  strategicCallout: 'Chief Software Engineer Directive: Never allow network latency to block human communication.',
  stepperSteps: [
    {
      id: 'split-1',
      stageNumber: 1,
      stageTitle: 'Local-First Data Storage',
      technicalVerification: 'SQLite split-database running in memory with WAL journaling',
      metricBadge: '0ms Disk Contention',
      isStageActive: true,
      isStageCompleted: true,
    },
    {
      id: 'split-2',
      stageNumber: 2,
      stageTitle: 'Hardware Accelerated DOM Canvas',
      technicalVerification: 'Direct CSS transform matrix mapping on 1920x1080 fixed virtual canvas',
      metricBadge: '60 FPS Solid',
      isStageActive: false,
      isStageCompleted: false,
    },
    {
      id: 'split-3',
      stageNumber: 3,
      stageTitle: 'Synthesized WebAudio Feedback',
      technicalVerification: 'Zero-asset synthesized oscillator click with low-pass dampening',
      metricBadge: '0kb Asset Weight',
      isStageActive: false,
      isStageCompleted: false,
    },
  ],
  hasSynchronizedSteps: true,
  isNarrativeHighlighted: true,
  activeStep: 0,
  maxSteps: 3,
};

export const DEFAULT_FLAT_TIMELINE_MILESTONE_RAIL_DATA: Omit<FlatTimelineMilestoneRailSlideData, 'id'> = {
  type: 'flat-timeline-milestone-rail',
  title: 'Global PPT Platform Roadmap & Delivery Milestones',
  kicker: 'PROJECT TIMELINE',
  subtitle: 'High-density milestone rail displaying progress checkpoints, owners, and deliverables',
  targetCompletionDate: 'November 30, 2026',
  overallProgressPercentage: 78,
  milestones: [
    {
      id: 'mile-1',
      milestoneIndex: 1,
      dateRangeLabel: 'Sprint 1 - 4',
      milestoneTitle: 'Engine Scaffolding & State Foundations',
      strategicObjective: 'Establish baseline presentation canvas and audio system.',
      actionItems: ['Zustand store architecture', 'Keyboard shortcut engine', 'Theme contrast tokens'],
      completionStatus: 'completed',
      isMilestoneActive: false,
    },
    {
      id: 'mile-2',
      milestoneIndex: 2,
      dateRangeLabel: 'Sprint 5 - 8',
      milestoneTitle: 'Slide Archetypes Expansion (1–45)',
      strategicObjective: 'Deliver 45 core, expanded, and kinetic slide archetypes.',
      actionItems: ['Kinetic physics springs', 'Bento grid layouts', 'Enterprise scorecards'],
      completionStatus: 'completed',
      isMilestoneActive: false,
    },
    {
      id: 'mile-3',
      milestoneIndex: 3,
      dateRangeLabel: 'Sprint 9 - 12',
      milestoneTitle: 'Flat Global Suite Integration (46–60)',
      strategicObjective: 'Ship 15 flat global archetypes with interactive branching.',
      actionItems: ['Keyboard branching shortcuts', 'Factory default manifests', 'Step progression calculations'],
      completionStatus: 'in-progress',
      isMilestoneActive: true,
    },
    {
      id: 'mile-4',
      milestoneIndex: 4,
      dateRangeLabel: 'Sprint 13 - 16',
      milestoneTitle: 'Autonomous Presenter HUD & Live SDK',
      strategicObjective: 'Final release ceremony and full platform documentation.',
      actionItems: ['Executive persona HUD', 'Zero-leak memory audit', 'Multi-tenant presentation cloud'],
      completionStatus: 'upcoming',
      isMilestoneActive: false,
    },
  ],
  hasMilestoneConnectors: true,
  isFlatTimelineActive: true,
  activeStep: 2,
  maxSteps: 4,
};

export const DEFAULT_FLAT_REVEAL_BENTO_GRID_DATA: Omit<FlatRevealBentoGridSlideData, 'id'> = {
  type: 'flat-reveal-bento-grid',
  title: 'Autonomous Capabilities Bento Grid',
  kicker: 'FEATURE MATRIX',
  subtitle: 'Four modular capability cards with progressive reveal animations and metric callouts',
  gridColumnCount: 3,
  bentoCards: [
    {
      id: 'bento-1',
      gridSpan: 'col-2',
      tileTitle: 'Tactile Audio Feedback Engine',
      tileDescription: 'Synthesizes clean audio clicks, taps, and whooshes on the fly using the Web Audio API without downloading external MP3/WAV assets.',
      highlightMetric: '0ms Latency',
      statusBadge: 'ACTIVE',
      iconIdentifier: 'Volume2',
      isTileRevealed: true,
      isTileFeatured: true,
    },
    {
      id: 'bento-2',
      gridSpan: 'col-1',
      tileTitle: 'Zero-Allocation Typings',
      tileDescription: 'Strict TypeScript interfaces enforcing positive booleans and rigorous compile-time contracts.',
      highlightMetric: '100% Typed',
      statusBadge: 'VERIFIED',
      iconIdentifier: 'Code',
      isTileRevealed: true,
      isTileFeatured: false,
    },
    {
      id: 'bento-3',
      gridSpan: 'col-1',
      tileTitle: '13 Contrast-Verified Palettes',
      tileDescription: 'WCAG AAA contrast compliant color palettes designed for ultra-bright boardroom displays.',
      highlightMetric: '7:1 Contrast',
      statusBadge: 'CERTIFIED',
      iconIdentifier: 'Palette',
      isTileRevealed: false,
      isTileFeatured: false,
    },
    {
      id: 'bento-4',
      gridSpan: 'col-2',
      tileTitle: 'Interactive Keyboard Branching',
      tileDescription: 'Non-linear slide deck traversal allowing presenters to pivot based on live audience feedback with single-key shortcuts.',
      highlightMetric: 'Instant Branching',
      statusBadge: 'PROD READY',
      iconIdentifier: 'GitBranch',
      isTileRevealed: false,
      isTileFeatured: true,
    },
  ],
  isProgressiveReveal: true,
  hasBorderHighlight: true,
  activeStep: 0,
  maxSteps: 4,
};

export const DEFAULT_FLAT_DEPTH_SENTENCE_STACK_DATA: Omit<FlatDepthSentenceStackSlideData, 'id'> = {
  type: 'flat-depth-sentence-stack',
  title: 'Core Principles of Autonomous Software Craftsmanship',
  kicker: 'ENGINEERING MANIFESTO',
  subtitle: 'Three foundational tenets governing system design, architecture, and code hygiene',
  stackDepthLevel: 3,
  sentenceCards: [
    {
      id: 'stack-1',
      cardIndex: 1,
      coreSentence: 'Simplicity is the prerequisite for reliability.',
      contextNarrative: 'Complex distributed architectures collapse under unexpected operational stress. Small, decoupled systems with minimal dependencies survive.',
      authorSignature: 'Alim Ul Karim, Chief Software Engineer',
      isCardActive: true,
      isSentenceEmphasized: true,
    },
    {
      id: 'stack-2',
      cardIndex: 2,
      coreSentence: 'Fast software respects human cognitive bandwidth.',
      contextNarrative: 'Every millisecond of latency is cognitive overhead. Zero-allocation data structures and 60FPS UI feedback create effortless clarity.',
      authorSignature: 'Engineering Governance Council',
      isCardActive: false,
      isSentenceEmphasized: false,
    },
    {
      id: 'stack-3',
      cardIndex: 3,
      coreSentence: 'Verifiable proof supersedes speculative consensus.',
      contextNarrative: 'Never deploy software based on assumptions. Require automated test evidence, immutable audit ledgers, and zero-trust verification.',
      authorSignature: 'Architecture Review Board',
      isCardActive: false,
      isSentenceEmphasized: false,
    },
  ],
  isLayeredDepthEnabled: true,
  hasCardShuffling: true,
  activeStep: 0,
  maxSteps: 3,
};

export const DEFAULT_FLAT_TYPEWRITER_CODE_WALKTHROUGH_DATA: Omit<FlatTypewriterCodeWalkthroughSlideData, 'id'> = {
  type: 'flat-typewriter-code-walkthrough',
  title: 'Interactive Code Walkthrough: Zero-Allocation Step Engine',
  kicker: 'SOURCE CODE INSPECTION',
  subtitle: 'Line-by-line mechanical breakdown of high-speed step calculation without garbage collection pressure',
  codeLanguage: 'typescript',
  terminalHeaderTitle: 'src/utils/stepProgression.ts - Line 210',
  codeSnippet: `export function calculateFlatGlobalSuiteSlideSteps(slide: any): number {
  if (!slide || typeof slide !== 'object') return 1;
  switch (slide.type) {
    case 'interactive-branching-close':
      return Math.max(slide.branches?.length || 2, 1);
    case 'before-after-showcase-pan':
      return Math.max(slide.panItems?.length || 2, 1);
    case 'talent-pyramid-funnel-svg':
      return Math.max(slide.funnelTiers?.length || 4, 1);
    default:
      return 1;
  }
}`,
  walkthroughSteps: [
    {
      id: 'code-1',
      stepNumber: 1,
      stepTitle: 'Defensive Object Guard',
      stepExplanation: 'Validates input object existence and type without throwing runtime null reference exceptions.',
      highlightedLineNumbers: [1, 2],
      isStepActive: true,
    },
    {
      id: 'code-2',
      stepNumber: 2,
      stepTitle: 'Exhaustive Archetype Switch',
      stepExplanation: 'Dispatches directly to precomputed item lengths, avoiding dynamic function allocations.',
      highlightedLineNumbers: [3, 4, 5, 6, 7],
      isStepActive: false,
    },
    {
      id: 'code-3',
      stepNumber: 3,
      stepTitle: 'Fallback Floor Guarantee',
      stepExplanation: 'Guarantees a positive integer return value of at least 1, preventing navigation division-by-zero errors.',
      highlightedLineNumbers: [8, 9, 10, 11],
      isStepActive: false,
    },
  ],
  isTypewriterAnimated: true,
  hasSyntaxHighlighting: true,
  isMonospaceTerminal: true,
  activeStep: 0,
  maxSteps: 3,
};
