// lint-allow: file-size reason="Global PPT Mastery slide default factories for 15 archetypes" max=600
import type {
  GlobalPptMasterySlideData,
  LlmAgenticWorkflowDagSlideData,
  ZeroDowntimeBlueGreenMeshSlideData,
  PostQuantumPqcKemHandshakeSlideData,
  DeveloperPlatformBackstagePortalSlideData,
  Soc2Type2ContinuousEvidenceStreamSlideData,
  AiModelDistillationPipelineSlideData,
  ExecutiveCompensationClawbackMatrixSlideData,
  EnterpriseLlmFineTuningLossSlideData,
  DistributedVectorIndexShardingSlideData,
  RealtimeFinancialFraudGraphSlideData,
  AutonomousCloudCostAnomaliesSlideData,
  LakehouseIcebergAcidLineageSlideData,
  MultiRegionActiveActiveCockroachSlideData,
  SupplyChainCarbonLedgerCbamSlideData,
  ChaosMeshNetworkPartitionDrillSlideData,
} from '../types/globalPptMasteryArchetypes';
import type { ArchetypeOption } from './extendedSlideFactories';

export const createLlmAgenticWorkflowSlide = (id = `slide-${Date.now()}`): LlmAgenticWorkflowDagSlideData => ({
  id,
  type: 'llm-agentic-workflow-dag',
  title: 'LLM Agentic Workflow DAG: Autonomous Orchestration & Human Consensus',
  subtitle: 'Deterministic subtask decomposition, isolated sandboxed tool dispatch, and verification gates',
  kicker: 'AUTONOMOUS AGENT GOVERNANCE',
  themeId: 'corporate-clean',
  activeStep: 0,
  maxSteps: 4,
  isPublished: true,
  hasPresenterNotes: true,
  workflowTitle: 'Enterprise Multi-Agent Production Orchestration',
  orchestratorFramework: 'LangGraph Core Enterprise',
  consensusThresholdPercent: 95,
  maxExecutionSteps: 8,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  hasHumanApprovalGate: true,
  hasSandboxIsolationActive: true,
  hasTelemetryGlow: true,
  agentStages: [
    {
      stepIndex: 0,
      stageName: 'Goal Decomposition',
      stageSubtitle: 'Natural language prompt parsing and subtask graph generation',
      focusAgent: 'Lead Planner Agent (Claude-3.7-Sonnet)',
      verificationGate: 'DAG acyclic structural validation & prompt dependency sanity',
      toolIntegrations: ['PromptTokenizer', 'DependencyResolver'],
      isActive: true,
      isCompleted: false,
    },
    {
      stepIndex: 1,
      stageName: 'Tool Dispatch & Sandbox Exec',
      stageSubtitle: 'Sandboxed Python execution, SQL querying, and vector retrieval',
      focusAgent: 'Worker Execution Agent',
      verificationGate: 'gVisor memory cgroup containment and timeout limit (15s)',
      toolIntegrations: ['PythonSandbox', 'PostgresRO', 'MilvusClient'],
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 2,
      stageName: 'Reflection & Guardrail Eval',
      stageSubtitle: 'Cross-agent reflection, hallucination checks, and policy compliance',
      focusAgent: 'Adversarial Critic Agent',
      verificationGate: 'Guardrails AI hallucination score > 0.95 and PII mask verification',
      toolIntegrations: ['GuardrailsValidator', 'ToxicityClassifier'],
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 3,
      stageName: 'Human-in-the-Loop Signoff',
      stageSubtitle: 'Cryptographic signoff and consensus ledger commit',
      focusAgent: 'Governance Supervisor',
      verificationGate: 'Dual-key authorized officer approval token',
      toolIntegrations: ['AuditVaultClient', 'SlackApprovalWebhook'],
      isActive: false,
      isCompleted: false,
    },
  ],
  taskNodes: [
    {
      id: 'node-planner-01',
      nodeIndex: 1,
      agentRole: 'Lead Planner',
      statusBadge: 'DISPATCHED',
      executionLatencyMs: 142,
      confidenceScorePercent: 98.4,
      outputPayloadSummary: 'Decomposed 1 parent intent into 4 parallel acyclic executable subtasks',
      isActive: true,
      isVerified: true,
      hasFallbackTriggered: false,
    },
    {
      id: 'node-executor-02',
      nodeIndex: 2,
      agentRole: 'Sandbox Executor',
      statusBadge: 'PENDING',
      executionLatencyMs: 840,
      confidenceScorePercent: 99.1,
      outputPayloadSummary: 'Executing vectorized query against Milvus cluster and sandboxed Python transformation',
      isActive: false,
      isVerified: false,
      hasFallbackTriggered: false,
    },
    {
      id: 'node-critic-03',
      nodeIndex: 3,
      agentRole: 'Adversarial Critic',
      statusBadge: 'QUEUED',
      executionLatencyMs: 310,
      confidenceScorePercent: 96.8,
      outputPayloadSummary: 'Evaluated ground truth citation matching against source documents',
      isActive: false,
      isVerified: false,
      hasFallbackTriggered: false,
    },
    {
      id: 'node-hitl-04',
      nodeIndex: 4,
      agentRole: 'Governance Supervisor',
      statusBadge: 'WAITING_APPROVAL',
      executionLatencyMs: 22,
      confidenceScorePercent: 100.0,
      outputPayloadSummary: 'Awaiting final biometric/authorized officer token for database persistence',
      isActive: false,
      isVerified: false,
      hasFallbackTriggered: false,
    },
  ],
});

export const createZeroDowntimeBlueGreenSlide = (id = `slide-${Date.now()}`): ZeroDowntimeBlueGreenMeshSlideData => ({
  id,
  type: 'zero-downtime-blue-green-mesh',
  title: 'Zero-Downtime Blue-Green Mesh: Continuous Automated Cutover',
  subtitle: 'Progressive Envoy route reassignment, real-time error budget tracking, and instant rollback',
  kicker: 'CLOUD INFRASTRUCTURE AUTOMATION',
  themeId: 'corporate-clean',
  activeStep: 1,
  maxSteps: 4,
  isPublished: true,
  hasPresenterNotes: true,
  serviceName: 'PaymentGatewayRouter',
  meshIngressController: 'Istio Ingress Gateway + Envoy 1.30',
  clusterRegion: 'us-east-1 (Multi-AZ)',
  totalActiveConnections: 48290,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  hasAutomaticRollbackEnabled: true,
  hasMutualTlsActive: true,
  hasZeroDowntimeCertified: true,
  deploymentStages: [
    {
      stepIndex: 0,
      stageName: 'Green Health Verification',
      trafficAllocationPercent: 0,
      errorBudgetBurnRate: 0.0,
      rollbackSloThresholdMs: 15,
      isActive: false,
      isCompleted: true,
    },
    {
      stepIndex: 1,
      stageName: 'Canary Traffic Ramp (10%)',
      trafficAllocationPercent: 10,
      errorBudgetBurnRate: 0.02,
      rollbackSloThresholdMs: 15,
      isActive: true,
      isCompleted: false,
    },
    {
      stepIndex: 2,
      stageName: 'Full Traffic Cutover (100%)',
      trafficAllocationPercent: 100,
      errorBudgetBurnRate: 0.01,
      rollbackSloThresholdMs: 15,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 3,
      stageName: 'Blue Fleet Drain & Standby',
      trafficAllocationPercent: 100,
      errorBudgetBurnRate: 0.0,
      rollbackSloThresholdMs: 15,
      isActive: false,
      isCompleted: false,
    },
  ],
  podReplicas: [
    {
      id: 'pod-blue-01',
      podName: 'payment-blue-7f89d',
      fleetColor: 'blue',
      versionTag: 'v2.1.4',
      trafficSharePercent: 45,
      cpuUtilizationPercent: 54,
      p99LatencyMs: 4.2,
      isHealthy: true,
      isDraining: false,
    },
    {
      id: 'pod-blue-02',
      podName: 'payment-blue-2b44c',
      fleetColor: 'blue',
      versionTag: 'v2.1.4',
      trafficSharePercent: 45,
      cpuUtilizationPercent: 52,
      p99LatencyMs: 4.1,
      isHealthy: true,
      isDraining: false,
    },
    {
      id: 'pod-green-01',
      podName: 'payment-green-9e11a',
      fleetColor: 'green',
      versionTag: 'v2.2.0',
      trafficSharePercent: 5,
      cpuUtilizationPercent: 18,
      p99LatencyMs: 2.8,
      isHealthy: true,
      isDraining: false,
    },
    {
      id: 'pod-green-02',
      podName: 'payment-green-6d88f',
      fleetColor: 'green',
      versionTag: 'v2.2.0',
      trafficSharePercent: 5,
      cpuUtilizationPercent: 19,
      p99LatencyMs: 2.7,
      isHealthy: true,
      isDraining: false,
    },
  ],
});

export const createPostQuantumPqcKemSlide = (id = `slide-${Date.now()}`): PostQuantumPqcKemHandshakeSlideData => ({
  id,
  type: 'post-quantum-pqc-kem-handshake',
  title: 'Post-Quantum PQC-KEM Handshake: NIST FIPS 203 Hybrid Security',
  subtitle: 'Hybrid classical X25519 + ML-KEM-768 key encapsulation safeguarding against store-now-decrypt-later',
  kicker: 'QUANTUM-RESISTANT CRYPTOGRAPHY',
  themeId: 'corporate-clean',
  activeStep: 0,
  maxSteps: 4,
  isPublished: true,
  hasPresenterNotes: true,
  handshakeStandard: 'NIST FIPS 203 / IETF Hybrid TLS 1.3',
  classicalAlgorithm: 'X25519 ECDH',
  quantumSafeAlgorithm: 'ML-KEM-768 (Kyber)',
  handshakeLatencyFormatted: '1.42 ms',
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  hasHybridModeActive: true,
  hasSideChannelProtection: true,
  hasHardwareAccelerationActive: true,
  handshakeStages: [
    {
      stepIndex: 0,
      stageName: 'ClientHello + Kyber Public Key',
      protocolDirection: 'Client -> Server',
      payloadSizeFormatted: '1,216 Bytes',
      executionDurationMicroseconds: 380,
      isActive: true,
      isCompleted: false,
    },
    {
      stepIndex: 1,
      stageName: 'Server Key Encapsulation & Ciphertext',
      protocolDirection: 'Server -> Client',
      payloadSizeFormatted: '1,088 Bytes',
      executionDurationMicroseconds: 420,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 2,
      stageName: 'Dual Shared Secret Derivation',
      protocolDirection: 'Local Bilateral Enclave',
      payloadSizeFormatted: '64 Bytes Master Key',
      executionDurationMicroseconds: 180,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 3,
      stageName: 'Encrypted Quantum-Safe Traffic Stream',
      protocolDirection: 'Bi-directional AES-256-GCM',
      payloadSizeFormatted: 'Full Line Rate (10 Gbps)',
      executionDurationMicroseconds: 12,
      isActive: false,
      isCompleted: false,
    },
  ],
  cryptoPrimitives: [
    {
      algorithmName: 'ML-KEM-768 (CRYSTALS-Kyber)',
      nistSecurityCategory: 3,
      keySizeBits: 6144,
      ciphertextSizeBytes: 1088,
      isNistStandardized: true,
    },
    {
      algorithmName: 'X25519 (Elliptic Curve Diffie-Hellman)',
      nistSecurityCategory: 1,
      keySizeBits: 256,
      ciphertextSizeBytes: 32,
      isNistStandardized: true,
    },
  ],
});

export const createDeveloperPlatformBackstageSlide = (id = `slide-${Date.now()}`): DeveloperPlatformBackstagePortalSlideData => ({
  id,
  type: 'developer-platform-backstage-portal',
  title: 'Developer Platform Backstage Portal: Golden Path Automation',
  subtitle: 'Scaffolding enterprise-grade microservices from template selection to production scorecard',
  kicker: 'PLATFORM ENGINEERING & DX',
  themeId: 'corporate-clean',
  activeStep: 0,
  maxSteps: 4,
  isPublished: true,
  hasPresenterNotes: true,
  portalName: 'Apex Internal Developer Portal',
  timeToFirstCommitMinutes: 6.2,
  catalogServiceCount: 348,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  hasGoldenPathEnforced: true,
  hasCatalogSyncActive: true,
  hasSecurityScorecardPassing: true,
  portalStages: [
    {
      stepIndex: 0,
      stageName: 'Software Template Selection',
      actionSummary: 'Choose approved architectural pattern with embedded security policies',
      automationEngine: 'Backstage Software Scaffolder v1.8',
      isActive: true,
      isCompleted: false,
    },
    {
      stepIndex: 1,
      stageName: 'Infrastructure as Code Provisioning',
      actionSummary: 'Automated VPC, RDS PostgreSQL, and EKS namespace provisioning',
      automationEngine: 'Terraform Cloud Workspace Pipeline',
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 2,
      stageName: 'Golden Path CI/CD Synthesis',
      actionSummary: 'Synthesis of container builds, security scans, and preview deployments',
      automationEngine: 'GitHub Actions + ArgoCD GitOps',
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 3,
      stageName: 'Production Scorecard Onboarding',
      actionSummary: 'Automated catalog registration, DORA metrics dashboard, and PagerDuty rotation',
      automationEngine: 'Backstage Entity Provider & Datadog',
      isActive: false,
      isCompleted: false,
    },
  ],
  goldenPathTemplates: [
    {
      templateId: 'tmpl-go-grpc',
      templateName: 'Go Enterprise Microservice (gRPC)',
      stackRuntime: 'Go 1.23 + gRPC + TimescaleDB',
      provisioningDurationSeconds: 45,
      isCompliantWithSecurityBaseline: true,
    },
    {
      templateId: 'tmpl-node-bff',
      templateName: 'TypeScript GraphQL BFF',
      stackRuntime: 'Node.js 22 + Apollo + Redis',
      provisioningDurationSeconds: 38,
      isCompliantWithSecurityBaseline: true,
    },
  ],
  scorecardMetrics: [
    {
      metricName: 'Deployment Frequency',
      currentScoreFormatted: 'Elite (12 deploys/day)',
      targetThresholdFormatted: '> 1 deploy/day',
      isPassed: true,
    },
    {
      metricName: 'Lead Time for Changes',
      currentScoreFormatted: '42 Minutes',
      targetThresholdFormatted: '< 1 Hour',
      isPassed: true,
    },
  ],
});

export const createSoc2Type2EvidenceStreamSlide = (id = `slide-${Date.now()}`): Soc2Type2ContinuousEvidenceStreamSlideData => ({
  id,
  type: 'soc2-type2-continuous-evidence-stream',
  title: 'SOC 2 Type II Continuous Evidence Stream: Real-Time Audit Ledger',
  subtitle: 'Cryptographic Merkle tree anchoring of cloud telemetry eliminating periodic audit friction',
  kicker: 'ENTERPRISE ASSURANCE & GOVERNANCE',
  themeId: 'corporate-clean',
  activeStep: 0,
  maxSteps: 4,
  isPublished: true,
  hasPresenterNotes: true,
  auditFirmName: 'Schellman & Company (Independent CPA)',
  reportingPeriodFormatted: 'Continuous Real-Time (2026)',
  complianceScorePercent: 100.0,
  totalControlsMonitored: 112,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  hasContinuousAuditCertified: true,
  hasZeroFindingsReported: true,
  hasCryptographicImmutability: true,
  complianceStages: [
    {
      stepIndex: 0,
      stageName: 'Trust Criteria Ingestion (CC6.1-CC8.1)',
      controlDomain: 'Security, Availability & Confidentiality',
      evidenceThroughputFormatted: '1,420 events/sec',
      verificationLatencyFormatted: '12 ms',
      isActive: true,
      isCompleted: false,
    },
    {
      stepIndex: 1,
      stageName: 'Telemetry Hash Generation',
      controlDomain: 'Multi-Cloud Event Streams (AWS, GitHub, Okta)',
      evidenceThroughputFormatted: '1,420 hashes/sec',
      verificationLatencyFormatted: '8 ms',
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 2,
      stageName: 'Merkle Proof Ledger Logging',
      controlDomain: 'WORM Object Storage & Merkle Trees',
      evidenceThroughputFormatted: '1 Block / 60 seconds',
      verificationLatencyFormatted: '42 ms',
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 3,
      stageName: 'Auditor Trust Center Attestation',
      controlDomain: 'External Independent Assurance',
      evidenceThroughputFormatted: 'Instant Query API',
      verificationLatencyFormatted: '2 ms',
      isActive: false,
      isCompleted: false,
    },
  ],
  trustRules: [
    {
      ruleCode: 'CC6.1',
      description: 'Logical access permissions restricted to authorized roles with mandatory MFA',
      sourceSystem: 'Okta + AWS IAM',
      samplingIntervalMinutes: 1,
      isCompliant: true,
    },
    {
      ruleCode: 'CC8.1',
      description: 'Code changes require peer review, automated SAST scan, and green CI gate',
      sourceSystem: 'GitHub Enterprise',
      samplingIntervalMinutes: 1,
      isCompliant: true,
    },
  ],
  merkleBlocks: [
    {
      blockHeight: 84912,
      blockHash: '0x7a9c8b3f2e1d0c4a',
      evidenceItemCount: 85200,
      rootMerkleTreeHash: '0x4b789ef01a23cd45',
      timestampUtc: '2026-10-04T02:00:00Z',
      isAnchored: true,
    },
  ],
});

export const createAiModelDistillationSlide = (id = `slide-${Date.now()}`): AiModelDistillationPipelineSlideData => ({
  id,
  type: 'ai-model-distillation-pipeline',
  title: 'AI Model Distillation Pipeline: 70B Frontier to 3.8B Edge Model',
  subtitle: 'Knowledge transfer, structured pruning, and INT4 quantization achieving 94.2% reasoning retention',
  kicker: 'EDGE AI INFRASTRUCTURE',
  themeId: 'corporate-clean',
  activeStep: 0,
  maxSteps: 4,
  isPublished: true,
  hasPresenterNotes: true,
  teacherModelName: 'Llama-3.3-70B-Instruct',
  studentModelName: 'Apex-Edge-3.8B-Mobile',
  compressionRatioFormatted: '18.4x Reduction',
  accuracyRetentionPercent: 94.2,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  hasEdgeDeploymentReady: true,
  hasAwqQuantizationCertified: true,
  hasOnDeviceGpuAccelerated: true,
  distillationStages: [
    {
      stepIndex: 0,
      stageName: '70B Teacher Logit Extraction',
      lossFunctionSummary: 'High-temperature soft probabilities (T=2.5) harvested across reasoning traces',
      hardwareCluster: '32x NVIDIA H100 SXM5 80GB',
      isActive: true,
      isCompleted: false,
    },
    {
      stepIndex: 1,
      stageName: 'Soft Cross-Entropy Loss Optimization',
      lossFunctionSummary: 'Kullback-Leibler divergence combined with hard cross-entropy tokens',
      hardwareCluster: '32x NVIDIA H100 SXM5 80GB',
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 2,
      stageName: 'Structured Pruning & INT4 AWQ',
      lossFunctionSummary: 'Activation-aware Weight Quantization (AWQ) preserving salient weight outliers',
      hardwareCluster: '4x H100 Validation Nodes',
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 3,
      stageName: 'On-Device Edge Validation',
      lossFunctionSummary: 'Benchmark validation against GSM8K, HumanEval, and MMLU on Apple M4 and Snapdragon X',
      hardwareCluster: 'Apple Silicon M4 Neural Engine',
      isActive: false,
      isCompleted: false,
    },
  ],
  modelLayers: [
    {
      layerIndex: 1,
      layerType: 'Grouped-Query Attention (GQA)',
      teacherParameterCount: '70B (80 Layers)',
      studentParameterCount: '3.8B (32 Layers)',
      prunedHeadPercentage: 60,
      isPreserved: true,
    },
    {
      layerIndex: 2,
      layerType: 'SwiGLU Feed-Forward Network',
      teacherParameterCount: '28,672 Intermediate Dim',
      studentParameterCount: '8,192 Intermediate Dim',
      prunedHeadPercentage: 71,
      isPreserved: true,
    },
  ],
  quantizationBenchmarks: [
    {
      quantizationPrecision: 'FP16 Baseline (Teacher)',
      memoryFootprintGb: 140.0,
      gsm8kAccuracyPercent: 89.8,
      inferenceSpeedTokensPerSec: 24,
      isOptimal: false,
    },
    {
      quantizationPrecision: 'AWQ INT4 (Apex Edge Student)',
      memoryFootprintGb: 2.1,
      gsm8kAccuracyPercent: 84.6,
      inferenceSpeedTokensPerSec: 98,
      isOptimal: true,
    },
  ],
});

export const createExecutiveCompensationClawbackSlide = (id = `slide-${Date.now()}`): ExecutiveCompensationClawbackMatrixSlideData => ({
  id,
  type: 'executive-compensation-clawback-matrix',
  title: 'Executive Compensation Clawback Matrix: SEC Rule 10D-1 Compliance',
  subtitle: 'Performance hurdles, relative TSR rankings, vesting multipliers, and no-fault recovery covenants',
  kicker: 'BOARDROOM GOVERNANCE & SEC COMPLIANCE',
  themeId: 'corporate-clean',
  activeStep: 0,
  maxSteps: 4,
  isPublished: true,
  hasPresenterNotes: true,
  companyTicker: 'NASDAQ: APEX',
  planFiscalYear: 'FY2026 Long-Term Incentive Plan',
  relativeTsrPercentile: 88,
  totalExecutivePoolFormatted: '$38.5M PSU Pool',
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  hasSecRule10D1Compliant: true,
  hasNoFaultEnforcement: true,
  hasBoardCommitteeCertified: true,
  clawbackStages: [
    {
      stepIndex: 0,
      stageName: 'Board Performance Hurdle Assessment',
      governanceAction: 'Audit of GAAP revenue, operating margin, and recurring cash flow targets',
      auditSignoffBody: 'Independent Compensation Committee',
      isActive: true,
      isCompleted: false,
    },
    {
      stepIndex: 1,
      stageName: 'Relative TSR Percentile Ranking',
      governanceAction: 'Calculation of 36-month compounded TSR vs S&P North American Technology Index',
      auditSignoffBody: 'Aon Hewitt Equity Valuation Group',
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 2,
      stageName: 'Vesting Waterfall & ESG Multipliers',
      governanceAction: 'Application of 1.25x financial multiplier and Scope-1/2 carbon reduction gate',
      auditSignoffBody: 'Principal Independent Actuary',
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 3,
      stageName: 'SEC Rule 10D-1 Covenant Certification',
      governanceAction: 'Irrevocable execution of mandatory no-fault recovery agreement on restatements',
      auditSignoffBody: 'Board of Directors & General Counsel',
      isActive: false,
      isCompleted: false,
    },
  ],
  hurdleMetrics: [
    {
      metricName: 'Free Cash Flow Margin',
      targetThresholdFormatted: '>= 32.0%',
      actualAchievedFormatted: '35.4%',
      payoutMultiplierPercent: 125,
      isHurdleAchieved: true,
    },
    {
      metricName: 'Rule of 40 (Growth + Margin)',
      targetThresholdFormatted: '>= 40.0%',
      actualAchievedFormatted: '48.2%',
      payoutMultiplierPercent: 140,
      isHurdleAchieved: true,
    },
  ],
  clawbackCovenants: [
    {
      covenantTitle: 'SEC Rule 10D-1 / NYSE Listed Rule 303A.14',
      governingBody: 'Securities and Exchange Commission',
      lookbackPeriodYears: 3,
      isRecoveryEnforcedNoFault: true,
    },
  ],
});

export const createEnterpriseLlmFineTuningSlide = (id = `slide-${Date.now()}`): EnterpriseLlmFineTuningLossSlideData => ({
  id,
  type: 'enterprise-llm-fine-tuning-loss',
  title: 'Enterprise LLM Fine-Tuning Loss: LoRA Convergence & Perplexity',
  subtitle: 'Parameter-efficient domain adaptation across 12.8B tokens with sub-2.5 validation perplexity',
  kicker: 'FOUNDATION MODEL ADAPTATION',
  themeId: 'corporate-clean',
  activeStep: 0,
  maxSteps: 4,
  isPublished: true,
  hasPresenterNotes: true,
  foundationModelName: 'Llama-3.3-70B-Base',
  corpusTokenCountFormatted: '12.8 Billion Tokens',
  finalEvalPerplexity: 2.41,
  gpuClusterConfig: '64x NVIDIA H100 SXM5 (FSDP + FlashAttention-3)',
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  hasConvergenceAchieved: true,
  hasZeroCatastrophicForgetting: true,
  hasFlashAttentionEnabled: true,
  tuningStages: [
    {
      stepIndex: 0,
      stageName: 'Domain Corpus Tokenization & Packing',
      stageMetricSummary: '12.8B tokens packed into 8k context sequences with zero padding waste',
      gradientNorm: 0.0,
      isActive: true,
      isCompleted: false,
    },
    {
      stepIndex: 1,
      stageName: 'Forward Pass Cross-Entropy Tracking',
      stageMetricSummary: 'Cross-entropy loss descends steadily from 3.84 to 1.12 without spike anomalies',
      gradientNorm: 0.84,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 2,
      stageName: 'LoRA Rank-r Adapter Descent',
      stageMetricSummary: 'Rank-32 adapter weights updated with cosine decay learning rate schedule',
      gradientNorm: 0.72,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 3,
      stageName: 'Eval Perplexity Validation & Checkpoint',
      stageMetricSummary: 'Domain perplexity confirmed at 2.41; general reasoning retention benchmark passed',
      gradientNorm: 0.45,
      isActive: false,
      isCompleted: false,
    },
  ],
  checkpoints: [
    {
      checkpointStep: 2500,
      trainingLoss: 2.45,
      validationPerplexity: 4.8,
      learningRate: 0.0002,
      gpuMemoryUsageGb: 58.2,
      isSavedCheckpoint: false,
    },
    {
      checkpointStep: 5000,
      trainingLoss: 1.82,
      validationPerplexity: 3.2,
      learningRate: 0.00018,
      gpuMemoryUsageGb: 58.4,
      isSavedCheckpoint: false,
    },
    {
      checkpointStep: 10000,
      trainingLoss: 1.12,
      validationPerplexity: 2.41,
      learningRate: 0.00005,
      gpuMemoryUsageGb: 58.4,
      isSavedCheckpoint: true,
    },
  ],
  loraParams: {
    loraRank: 32,
    loraAlpha: 64,
    targetModules: ['q_proj', 'k_proj', 'v_proj', 'o_proj'],
    trainableParameterRatioPercent: 0.18,
  },
});

export const createDistributedVectorIndexSlide = (id = `slide-${Date.now()}`): DistributedVectorIndexShardingSlideData => ({
  id,
  type: 'distributed-vector-index-sharding',
  title: 'Distributed Vector Index Sharding: Sub-4ms Retrieval Over 500M Embeddings',
  subtitle: 'Memory-mapped NVMe partitions, Voronoi centroid routing, and HNSW graphs maintaining 99.4% recall',
  kicker: 'VECTOR SEARCH ARCHITECTURE',
  themeId: 'corporate-clean',
  activeStep: 0,
  maxSteps: 1,
  isPublished: true,
  hasPresenterNotes: true,
  clusterSpec: {
    clusterName: 'ApexVector-Production-Fleet',
    totalVectorsIndexed: 500000000,
    vectorDimensionality: 1536,
    totalIndexStorageTb: 1.52,
    hasNvmeDirectActive: true,
  },
  routingAlgorithm: 'Centroid Voronoi gRPC Dispatch (16,384 centroids)',
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  hasSubMillisecondCentroidRouting: true,
  hasNvmeDirectIoEnabled: true,
  hasReplicationSyncActive: true,
  shards: [
    {
      shardId: 'shard-east-01',
      nodeHost: 'vec-node-01.us-east.corp',
      vectorCapacityFormatted: '125M Vectors',
      indexType: 'HNSW (M=32, ef=200)',
      memoryTier: 'DRAM',
      p99LatencyMs: 3.2,
      recallAccuracyPercent: 99.6,
      isLeader: true,
      isHealthy: true,
    },
    {
      shardId: 'shard-east-02',
      nodeHost: 'vec-node-02.us-east.corp',
      vectorCapacityFormatted: '125M Vectors',
      indexType: 'HNSW (M=32, ef=200)',
      memoryTier: 'MemoryMappedNVMe',
      p99LatencyMs: 3.4,
      recallAccuracyPercent: 99.4,
      isLeader: false,
      isHealthy: true,
    },
    {
      shardId: 'shard-east-03',
      nodeHost: 'vec-node-03.us-east.corp',
      vectorCapacityFormatted: '125M Vectors',
      indexType: 'HNSW (M=32, ef=200)',
      memoryTier: 'MemoryMappedNVMe',
      p99LatencyMs: 3.5,
      recallAccuracyPercent: 99.3,
      isLeader: false,
      isHealthy: true,
    },
    {
      shardId: 'shard-east-04',
      nodeHost: 'vec-node-04.us-east.corp',
      vectorCapacityFormatted: '125M Vectors',
      indexType: 'HNSW (M=32, ef=200)',
      memoryTier: 'CXL',
      p99LatencyMs: 3.3,
      recallAccuracyPercent: 99.5,
      isLeader: false,
      isHealthy: true,
    },
  ],
});

export const createRealtimeFinancialFraudSlide = (id = `slide-${Date.now()}`): RealtimeFinancialFraudGraphSlideData => ({
  id,
  type: 'realtime-financial-fraud-graph',
  title: 'Real-Time Financial Fraud Graph: GNN Multi-Hop Layering Detection',
  subtitle: 'Heterogeneous Graph Neural Networks uncovering shell company circular fund laundering within 9.8ms',
  kicker: 'FINANCIAL CRIME INTELLIGENCE',
  themeId: 'corporate-clean',
  activeStep: 0,
  maxSteps: 1,
  isPublished: true,
  hasPresenterNotes: true,
  scorecard: {
    modelArchitecture: 'Relational Graph Convolutional Network (R-GCN)',
    inferenceLatencyMs: 9.8,
    falsePositiveReductionPercent: 78.4,
    detectedFraudRingValue: '$14.2M',
  },
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  hasAmlComplianceCertified: true,
  hasRealtimeBlockingActive: true,
  hasCircularRoutingDetected: true,
  entities: [
    {
      entityId: 'ent-acc-01',
      entityType: 'ACCOUNT',
      label: 'Origination Account #8491',
      riskScore: 24,
      flaggedReason: 'Normal consumer deposit profile',
      jurisdictionCountry: 'US',
      isFlaggedSuspicious: false,
    },
    {
      entityId: 'ent-shell-01',
      entityType: 'SHELL_CORP',
      label: 'Apex International Ltd',
      riskScore: 94,
      flaggedReason: 'Rapid fund pass-through with no payroll activity',
      jurisdictionCountry: 'CY',
      isFlaggedSuspicious: true,
    },
    {
      entityId: 'ent-shell-02',
      entityType: 'SHELL_CORP',
      label: 'Borealis Holding SARL',
      riskScore: 96,
      flaggedReason: 'Cross-jurisdiction high-frequency layering',
      jurisdictionCountry: 'LU',
      isFlaggedSuspicious: true,
    },
  ],
  edges: [
    {
      sourceEntityId: 'ent-acc-01',
      targetEntityId: 'ent-shell-01',
      amountFormatted: '$450,000 USD',
      hopIndex: 1,
      timeElapsedSeconds: 18,
      isRapidLayering: true,
    },
    {
      sourceEntityId: 'ent-shell-01',
      targetEntityId: 'ent-shell-02',
      amountFormatted: '$448,000 USD',
      hopIndex: 2,
      timeElapsedSeconds: 42,
      isRapidLayering: true,
    },
  ],
});

export const createAutonomousCloudCostSlide = (id = `slide-${Date.now()}`): AutonomousCloudCostAnomaliesSlideData => ({
  id,
  type: 'autonomous-cloud-cost-anomalies',
  title: 'Autonomous Cloud Cost Anomalies: eBPF Pod-to-Dollar Attribution',
  subtitle: 'Linux kernel cgroup v2 accounting intercepting runaway compute spend in sub-15 seconds',
  kicker: 'FINOPS KERNEL AUTOMATION',
  themeId: 'corporate-clean',
  activeStep: 0,
  maxSteps: 1,
  isPublished: true,
  hasPresenterNotes: true,
  clusterSpendRunRateFormatted: '$1.24M/yr',
  totalMonthlySavingsFormatted: '$186,000/mo Saved',
  activeEbpfProbesCount: 256,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  hasEbpfKernelAccounting: true,
  hasAutonomousThrottlingActive: true,
  hasBudgetGovernanceCertified: true,
  anomalies: [
    {
      podNamespace: 'analytics-prod',
      workloadName: 'batch-etl-spark-worker',
      projectedMonthlyCostFormatted: '$48,200/mo',
      baselineCostFormatted: '$3,400/mo',
      anomalyMultiplierFormatted: '14.2x Spike',
      ebpfThrottleApplied: true,
      hasEbpfThrottleApplied: true,
      isRunawayDetected: true,
    },
    {
      podNamespace: 'ai-sandbox',
      workloadName: 'llm-inference-test-pod',
      projectedMonthlyCostFormatted: '$18,400/mo',
      baselineCostFormatted: '$1,200/mo',
      anomalyMultiplierFormatted: '15.3x Spike',
      ebpfThrottleApplied: true,
      hasEbpfThrottleApplied: true,
      isRunawayDetected: true,
    },
    {
      podNamespace: 'telemetry-infra',
      workloadName: 'telemetry-es-indexing',
      projectedMonthlyCostFormatted: '$12,900/mo',
      baselineCostFormatted: '$4,800/mo',
      anomalyMultiplierFormatted: '2.7x Spike',
      ebpfThrottleApplied: true,
      hasEbpfThrottleApplied: true,
      isRunawayDetected: true,
    },
  ],
  cgroupAllocations: [
    {
      clusterNodeId: 'node-k8s-c5-4xlarge-08',
      cgroupV2Path: '/sys/fs/cgroup/kubepods/burstable/pod-spark-01',
      cpuQuotaPercentage: 50,
      memoryLimitGb: 32,
      isThrottled: true,
    },
  ],
});

export const createLakehouseIcebergAcidSlide = (id = `slide-${Date.now()}`): LakehouseIcebergAcidLineageSlideData => ({
  id,
  type: 'lakehouse-iceberg-acid-lineage',
  title: 'Lakehouse Iceberg ACID Lineage: Snapshot Metadata Hierarchy',
  subtitle: 'Immutable manifest tree, file-level pruning, and zero-copy branching on commodity object storage',
  kicker: 'ENTERPRISE DATA ARCHITECTURE',
  themeId: 'corporate-clean',
  activeStep: 0,
  maxSteps: 1,
  isPublished: true,
  hasPresenterNotes: true,
  tableName: 'telemetry.corporate_events',
  lakehouseStorageFormat: 'Apache Iceberg v2 Format',
  storageEngine: 'S3 / MinIO WORM Object Storage',
  totalTableSizeBytes: '14.8 TB',
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  hasAcidIsolationCertified: true,
  hasTimeTravelQueryEnabled: true,
  hasCopyOnWriteActive: true,
  snapshots: [
    {
      snapshotId: 'snap-9812-initial',
      parentSnapshotId: 'null',
      commitTimestampUtc: '2026-10-01T00:00:00Z',
      operationType: 'APPEND',
      addedRecordsFormatted: '+144.4M Records',
      totalRecordsFormatted: '144.4M Records',
      isCurrentSnapshot: false,
    },
    {
      snapshotId: 'snap-9813-live',
      parentSnapshotId: 'snap-9812-initial',
      commitTimestampUtc: '2026-10-04T02:00:00Z',
      operationType: 'APPEND',
      addedRecordsFormatted: '+4.2M Records',
      totalRecordsFormatted: '148.6M Records',
      isCurrentSnapshot: true,
    },
  ],
  manifests: [
    {
      manifestPath: 's3://lakehouse/telemetry/metadata/manifest-01.avro',
      partitionRangeFormatted: 'date >= 2026-10-01 AND date <= 2026-10-04',
      dataFileCount: 240,
      fileSizeBytesFormatted: '48.2 GB',
      hasDeletedFiles: false,
    },
  ],
});

export const createMultiRegionActiveActiveSlide = (id = `slide-${Date.now()}`): MultiRegionActiveActiveCockroachSlideData => ({
  id,
  type: 'multi-region-active-active-cockroach',
  title: 'Multi-Region Active-Active Cockroach: Global Relational Consensus',
  subtitle: 'Distributed Raft consensus, local read leases across 3 continents, and zero RPO recovery',
  kicker: 'DISTRIBUTED SYSTEMS ARCHITECTURE',
  themeId: 'corporate-clean',
  activeStep: 0,
  maxSteps: 1,
  isPublished: true,
  hasPresenterNotes: true,
  clusterDatabaseName: 'GlobalFinancialLedger',
  consensusProtocol: 'Multi-Raft Consensus + Hybrid Logical Clocks (HLC)',
  hasZeroRpoCertified: true,
  zeroRpoCertified: true,
  mttrFailoverSeconds: 2.4,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  hasLocalReadLeasesActive: true,
  hasHybridLogicalClocksSync: true,
  hasZeroDataLossRpo: true,
  regionNodes: [
    {
      regionCode: 'us-east-1',
      datacenterCity: 'N. Virginia (Americas)',
      nodeCount: 6,
      readLeaseCount: 1420,
      localReadLatencyMs: 1.8,
      crossRegionWriteLatencyMs: 68.0,
      isLeaseholder: true,
      isConsensusQuorumAchieved: true,
    },
    {
      regionCode: 'eu-central-1',
      datacenterCity: 'Frankfurt (Europe)',
      nodeCount: 6,
      readLeaseCount: 980,
      localReadLatencyMs: 2.1,
      crossRegionWriteLatencyMs: 72.0,
      isLeaseholder: false,
      isConsensusQuorumAchieved: true,
    },
    {
      regionCode: 'ap-northeast-1',
      datacenterCity: 'Tokyo (Asia-Pacific)',
      nodeCount: 6,
      readLeaseCount: 750,
      localReadLatencyMs: 2.4,
      crossRegionWriteLatencyMs: 94.0,
      isLeaseholder: false,
      isConsensusQuorumAchieved: true,
    },
  ],
});

export const createSupplyChainCarbonCbamSlide = (id = `slide-${Date.now()}`): SupplyChainCarbonLedgerCbamSlideData => ({
  id,
  type: 'supply-chain-carbon-ledger-cbam',
  title: 'Supply Chain Carbon Ledger CBAM: EU Regulatory Tariff Audit',
  subtitle: 'Scope 1, 2, and 3 embedded emissions tracking across tiered suppliers with cryptographic certification',
  kicker: 'SUSTAINABILITY & INTERNATIONAL TRADE',
  themeId: 'corporate-clean',
  activeStep: 0,
  maxSteps: 1,
  isPublished: true,
  hasPresenterNotes: true,
  reportingFiscalQuarter: 'Q4 2026 CBAM Filing',
  totalEmbeddedEmissionsTonnesCo2e: 142800,
  totalEstimatedTariffExposureEur: '€4.82M',
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  hasEuRegistryConnected: true,
  hasScope3TelemetryAudited: true,
  hasCryptographicCertValidation: true,
  tierItems: [
    {
      tierNumber: 1,
      supplierName: 'Apex Nordic Advanced Assembly',
      countryOriginIso: 'SE',
      embeddedEmissionsKgCo2ePerTon: 142,
      cbamBenchmarkKgCo2ePerTon: 280,
      tariffLiabilityPerTonEur: 0.0,
      hasCryptographicCarbonCert: true,
      isCompliantWithEuThreshold: true,
    },
    {
      tierNumber: 2,
      supplierName: 'Borealis Semiconductor Foundry',
      countryOriginIso: 'TW',
      embeddedEmissionsKgCo2ePerTon: 480,
      cbamBenchmarkKgCo2ePerTon: 350,
      tariffLiabilityPerTonEur: 12.4,
      hasCryptographicCarbonCert: true,
      isCompliantWithEuThreshold: false,
    },
    {
      tierNumber: 3,
      supplierName: 'Global Smelting Corporation',
      countryOriginIso: 'IN',
      embeddedEmissionsKgCo2ePerTon: 1840,
      cbamBenchmarkKgCo2ePerTon: 1200,
      tariffLiabilityPerTonEur: 48.5,
      hasCryptographicCarbonCert: true,
      isCompliantWithEuThreshold: false,
    },
  ],
});

export const createChaosMeshNetworkPartitionSlide = (id = `slide-${Date.now()}`): ChaosMeshNetworkPartitionDrillSlideData => ({
  id,
  type: 'chaos-mesh-network-partition-drill',
  title: 'Chaos Mesh Network Partition Drill: Split-Brain Prevention',
  subtitle: 'Simulated trans-oceanic network split proving majority quorum resilience and 3.8s MTTR',
  kicker: 'CHAOS ENGINEERING & SRE RESILIENCE',
  themeId: 'corporate-clean',
  activeStep: 0,
  maxSteps: 1,
  isPublished: true,
  hasPresenterNotes: true,
  drillExperimentName: 'Operation SplitShield: Trans-Oceanic Partition',
  targetDatabaseCluster: 'Distributed Consensus Database (5 Nodes)',
  mttrSeconds: 3.8,
  quorumRule: 'Majority Quorum: ceil((n+1)/2) = 3 Nodes',
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  hasSplitBrainPrevented: true,
  hasAutomatedFailoverValidated: true,
  hasZeroDataLossGuaranteed: true,
  nodes: [
    {
      nodeId: 'node-db-01',
      nodeRole: 'Raft Leader',
      injectedFailureType: 'None (Majority Partition)',
      heartbeatLossMilliseconds: 0,
      isPartitioned: false,
      hasQuorumMaintained: true,
    },
    {
      nodeId: 'node-db-02',
      nodeRole: 'Consensus Follower',
      injectedFailureType: 'None (Majority Partition)',
      heartbeatLossMilliseconds: 0,
      isPartitioned: false,
      hasQuorumMaintained: true,
    },
    {
      nodeId: 'node-db-03',
      nodeRole: 'Consensus Follower',
      injectedFailureType: 'None (Majority Partition)',
      heartbeatLossMilliseconds: 0,
      isPartitioned: false,
      hasQuorumMaintained: true,
    },
    {
      nodeId: 'node-db-04',
      nodeRole: 'Isolated Follower',
      injectedFailureType: '100% Network Partition',
      heartbeatLossMilliseconds: 4200,
      isPartitioned: true,
      hasQuorumMaintained: false,
    },
    {
      nodeId: 'node-db-05',
      nodeRole: 'Isolated Follower',
      injectedFailureType: '100% Network Partition',
      heartbeatLossMilliseconds: 4200,
      isPartitioned: true,
      hasQuorumMaintained: false,
    },
  ],
  recoveryPhases: [
    {
      drillPhase: 'Fault Injected (Partition 2 Nodes)',
      elapsedSeconds: 0.0,
      clusterAvailabilityPercent: 100.0,
      circuitBreakerTripped: false,
      hasCircuitBreakerTripped: false,
    },
    {
      drillPhase: 'Leader Re-Election Triggered',
      elapsedSeconds: 1.8,
      clusterAvailabilityPercent: 99.4,
      circuitBreakerTripped: true,
      hasCircuitBreakerTripped: true,
    },
    {
      drillPhase: 'Steady-State Quorum Restored',
      elapsedSeconds: 3.8,
      clusterAvailabilityPercent: 100.0,
      circuitBreakerTripped: false,
      hasCircuitBreakerTripped: false,
    },
  ],
});

export const GLOBAL_PPT_MASTERY_FACTORIES: Record<string, (id?: string) => GlobalPptMasterySlideData> = {
  'llm-agentic-workflow-dag': createLlmAgenticWorkflowSlide,
  'zero-downtime-blue-green-mesh': createZeroDowntimeBlueGreenSlide,
  'post-quantum-pqc-kem-handshake': createPostQuantumPqcKemSlide,
  'developer-platform-backstage-portal': createDeveloperPlatformBackstageSlide,
  'soc2-type2-continuous-evidence-stream': createSoc2Type2EvidenceStreamSlide,
  'ai-model-distillation-pipeline': createAiModelDistillationSlide,
  'executive-compensation-clawback-matrix': createExecutiveCompensationClawbackSlide,
  'enterprise-llm-fine-tuning-loss': createEnterpriseLlmFineTuningSlide,
  'distributed-vector-index-sharding': createDistributedVectorIndexSlide,
  'realtime-financial-fraud-graph': createRealtimeFinancialFraudSlide,
  'autonomous-cloud-cost-anomalies': createAutonomousCloudCostSlide,
  'lakehouse-iceberg-acid-lineage': createLakehouseIcebergAcidSlide,
  'multi-region-active-active-cockroach': createMultiRegionActiveActiveSlide,
  'supply-chain-carbon-ledger-cbam': createSupplyChainCarbonCbamSlide,
  'chaos-mesh-network-partition-drill': createChaosMeshNetworkPartitionSlide,
};

export const GLOBAL_PPT_MASTERY_ARCHETYPE_OPTIONS: ArchetypeOption[] = [
  {
    type: 'llm-agentic-workflow-dag',
    label: 'LLM Agentic Workflow DAG',
    category: 'AI Infrastructure',
    desc: 'Autonomous multi-agent reasoning, sandboxed tool execution & human consensus signoff',
    icon: 'Workflow',
  },
  {
    type: 'zero-downtime-blue-green-mesh',
    label: 'Zero-Downtime Blue-Green Mesh',
    category: 'Product & Architecture',
    desc: 'Progressive Envoy route reassignment, real-time error budget tracking & instant rollback',
    icon: 'Server',
  },
  {
    type: 'post-quantum-pqc-kem-handshake',
    label: 'Post-Quantum PQC-KEM Handshake',
    category: 'Platform & Network',
    desc: 'NIST FIPS 203 hybrid ML-KEM-768 + X25519 post-quantum key encapsulation',
    icon: 'Lock',
  },
  {
    type: 'developer-platform-backstage-portal',
    label: 'Developer Platform Backstage Portal',
    category: 'Product & Architecture',
    desc: 'Golden path microservice scaffolding, Terraform IaC & production DORA scorecard',
    icon: 'Terminal',
  },
  {
    type: 'soc2-type2-continuous-evidence-stream',
    label: 'SOC 2 Continuous Evidence Stream',
    category: 'Team & Credibility',
    desc: 'Cryptographic Merkle tree anchoring of cloud telemetry eliminating periodic audit friction',
    icon: 'FileCheck',
  },
  {
    type: 'ai-model-distillation-pipeline',
    label: 'AI Model Distillation Pipeline',
    category: 'AI Infrastructure',
    desc: '70B frontier teacher to 3.8B edge student distillation, pruning & INT4 AWQ',
    icon: 'Cpu',
  },
  {
    type: 'executive-compensation-clawback-matrix',
    label: 'Executive Compensation Clawback Matrix',
    category: 'Corporate Strategy',
    desc: 'SEC Rule 10D-1 compliance, performance hurdles, rTSR & no-fault recovery',
    icon: 'Scale',
  },
  {
    type: 'enterprise-llm-fine-tuning-loss',
    label: 'Enterprise LLM Fine-Tuning Loss',
    category: 'AI Infrastructure',
    desc: 'LoRA rank-32 parameter-efficient domain adaptation across 12.8B tokens',
    icon: 'TrendingUp',
  },
  {
    type: 'distributed-vector-index-sharding',
    label: 'Distributed Vector Index Sharding',
    category: 'AI Infrastructure',
    desc: 'Sub-4ms retrieval over 500M vectors across memory-mapped NVMe & Voronoi routing',
    icon: 'Database',
  },
  {
    type: 'realtime-financial-fraud-graph',
    label: 'Real-Time Financial Fraud Graph',
    category: 'Platform & Network',
    desc: 'Heterogeneous GNN multi-hop layering detection uncovering shell companies in 9.8ms',
    icon: 'Network',
  },
  {
    type: 'autonomous-cloud-cost-anomalies',
    label: 'Autonomous Cloud Cost Anomalies',
    category: 'Product & Architecture',
    desc: 'Linux kernel eBPF cgroup v2 accounting intercepting runaway compute spend',
    icon: 'Gauge',
  },
  {
    type: 'lakehouse-iceberg-acid-lineage',
    label: 'Lakehouse Iceberg ACID Lineage',
    category: 'Product & Architecture',
    desc: 'Apache Iceberg v2 snapshot tree, manifest pruning & zero-copy branching',
    icon: 'Layers',
  },
  {
    type: 'multi-region-active-active-cockroach',
    label: 'Multi-Region Active-Active Cockroach',
    category: 'Product & Architecture',
    desc: 'Distributed Raft consensus, local read leases across 3 continents & zero RPO',
    icon: 'Globe',
  },
  {
    type: 'supply-chain-carbon-ledger-cbam',
    label: 'Supply Chain Carbon Ledger CBAM',
    category: 'Corporate Strategy',
    desc: 'EU CBAM Scope 1-3 embedded emissions ledger with cryptographic carbon certificates',
    icon: 'Leaf',
  },
  {
    type: 'chaos-mesh-network-partition-drill',
    label: 'Chaos Mesh Network Partition Drill',
    category: 'Product & Architecture',
    desc: 'Simulated trans-oceanic network split proving majority quorum & 3.8s MTTR',
    icon: 'Radar',
  },
];
