// lint-allow: file-size reason="Chapter 42 Global PPT NextGen slide default factories for 15 archetypes" max=600
import type {
  AgenticEvalRedTeamSlideData,
  GitOpsArgoCdSyncSlideData,
  NvmeFabricsRdmaSlideData,
  ConfidentialGpuAttestSlideData,
  EbpfDdosXdpSlideData,
  ActiveInferenceMemorySlideData,
  SovereignAiCleanRoomSlideData,
  IncidentCommandPlaybookSlideData,
  GpuHbmInterconnectSlideData,
  RealtimeFeatureStoreSlideData,
  DistributedWalRaftSlideData,
  FinopsUnitEconomicsSlideData,
  CrossBorderDataResidencySlideData,
  ZeroTrustSpiffeSlideData,
  BoardCapitalAllocationSlideData,
  GlobalPptNextGenSlideData,
} from '../types/globalPptNextGenArchetypes';
import type { ArchetypeOption } from './extendedSlideFactories';

export const createAgenticEvalRedTeamSlide = (id = `slide-${Date.now()}`): AgenticEvalRedTeamSlideData => ({
  id,
  type: 'agentic-eval-red-team-harness',
  title: 'Agentic Eval Red-Team Harness: Autonomous Jailbreak Containment',
  subtitle: 'Continuous automated adversarial probing, sandboxed model execution, and real-time guardrail synthesis',
  kicker: 'AUTONOMOUS AI SAFETY & RED-TEAM HARNESS',
  themeId: 'corporate-clean',
  activeStep: 1,
  maxSteps: 4,
  isPublished: true,
  hasPresenterNotes: true,
  harnessName: 'SpectreOps Autonomous Red-Team Suite',
  targetModelFamily: 'Enterprise Frontier Swarm v4',
  overallRobustnessScorePercent: 99.4,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  hasAutomatedPatchingEnabled: true,
  hasSandboxIsolationActive: true,
  hasAttestationSeal: true,
  hasTelemetryGlow: true,
  evalStages: [
    {
      stepIndex: 1,
      stageName: 'Adversarial Probing',
      stageSubtitle: 'Polyglot jailbreak mutation and adversarial suffix generation',
      evaluatorEngine: 'DeepMutation Engine v2',
      targetBenchmark: 'OWASP LLM Top 10 + NIST AI RMF',
      syntheticProbeCount: 4200,
      isActive: true,
      isCompleted: false,
    },
    {
      stepIndex: 2,
      stageName: 'Execution Isolation',
      stageSubtitle: 'Sandboxed inference with zero-trust egress firewalls',
      evaluatorEngine: 'gVisor MicroVM Sandbox',
      targetBenchmark: 'Kernel Syscall Isolation Level 4',
      syntheticProbeCount: 4200,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 3,
      stageName: 'Scoring & Policy Eval',
      stageSubtitle: 'Multi-agent reflection, hallucination scoring, and toxic classification',
      evaluatorEngine: 'Constitutional AI Critic Agent',
      targetBenchmark: 'Hallucination Benchmark < 0.2%',
      syntheticProbeCount: 2040,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 4,
      stageName: 'Hardened Patch Seal',
      stageSubtitle: 'Automated runtime policy compilation and cryptographic attestation',
      evaluatorEngine: 'Wasm Guardrail Synthesizer',
      targetBenchmark: 'Zero-Day Regression Guard',
      syntheticProbeCount: 2040,
      isActive: false,
      isCompleted: false,
    },
  ],
  attackVectors: [
    {
      id: 'vector-01',
      vectorIndex: 1,
      attackCategory: 'Jailbreak Inversion',
      severityBadge: 'CRITICAL',
      successRatePercent: 0.2,
      mitigationStatus: 'CONTAINED',
      isContained: true,
      hasActiveMitigation: true,
      isVerified: true,
    },
    {
      id: 'vector-02',
      vectorIndex: 2,
      attackCategory: 'Indirect Prompt Injection',
      severityBadge: 'HIGH',
      successRatePercent: 0.4,
      mitigationStatus: 'PATCHED',
      isContained: true,
      hasActiveMitigation: true,
      isVerified: true,
    },
    {
      id: 'vector-03',
      vectorIndex: 3,
      attackCategory: 'PII Extraction',
      severityBadge: 'HIGH',
      successRatePercent: 0.0,
      mitigationStatus: 'CONTAINED',
      isContained: true,
      hasActiveMitigation: true,
      isVerified: true,
    },
    {
      id: 'vector-04',
      vectorIndex: 4,
      attackCategory: 'System Prompt Override',
      severityBadge: 'MEDIUM',
      successRatePercent: 0.1,
      mitigationStatus: 'MITIGATED',
      isContained: true,
      hasActiveMitigation: true,
      isVerified: true,
    },
  ],
});

export const createGitOpsArgoCdSyncSlide = (id = `slide-${Date.now()}`): GitOpsArgoCdSyncSlideData => ({
  id,
  type: 'gitops-argocd-sync-reconciliation',
  title: 'GitOps ArgoCD Sync Reconciliation: Declarative Drift Correction',
  subtitle: 'Continuous Git-to-cluster synchronization with automated drift detection and multi-wave application',
  kicker: 'DECLARATIVE CLUSTER INFRASTRUCTURE',
  themeId: 'corporate-clean',
  activeStep: 1,
  maxSteps: 4,
  isPublished: true,
  hasPresenterNotes: true,
  applicationName: 'core-checkout-service',
  clusterTarget: 'k8s-prod-us-east-1',
  gitRevisionSha: '9f4a8b2c1d3e',
  syncDurationSeconds: 4.2,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  hasAutoPruneEnabled: true,
  hasSelfHealingActive: true,
  hasZeroDowntimeEnforced: true,
  hasTelemetryGlow: true,
  reconciliationStages: [
    {
      stepIndex: 1,
      stageName: 'Git Ingestion',
      stageSubtitle: 'Cryptographic signature validation and Kustomize overlay build',
      actionSummary: 'Verified PGP commit signature and fetched OCI chart bundle',
      elapsedTimeMs: 280,
      isActive: true,
      isCompleted: false,
    },
    {
      stepIndex: 2,
      stageName: 'Drift Detection',
      stageSubtitle: 'Deep three-way JSON patch diff against live etcd state',
      actionSummary: 'Identified 4 replica delta and 1 environment variable mismatch',
      elapsedTimeMs: 640,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 3,
      stageName: 'Wave Application',
      stageSubtitle: 'Ordered sync waves applying CRDs, networking, and deployment',
      actionSummary: 'Triggered rolling update with zero dropped ingress connections',
      elapsedTimeMs: 2400,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 4,
      stageName: 'Steady-State Sync',
      stageSubtitle: 'Readiness probe satisfaction and health status green seal',
      actionSummary: 'All 12 pods healthy with zero error budget burn rate',
      elapsedTimeMs: 880,
      isActive: false,
      isCompleted: false,
    },
  ],
  resources: [
    {
      id: 'res-01',
      resourceKind: 'CustomResourceDefinition',
      resourceName: 'virtualservices.networking.istio.io',
      targetNamespace: 'istio-system',
      syncWave: 1,
      syncStatus: 'Synced',
      isSynced: true,
      isHealthy: true,
      hasDriftDetected: false,
    },
    {
      id: 'res-02',
      resourceKind: 'ConfigMap',
      resourceName: 'checkout-feature-flags',
      targetNamespace: 'production-checkout',
      syncWave: 2,
      syncStatus: 'Synced',
      isSynced: true,
      isHealthy: true,
      hasDriftDetected: false,
    },
    {
      id: 'res-03',
      resourceKind: 'Deployment',
      resourceName: 'checkout-api-server',
      targetNamespace: 'production-checkout',
      syncWave: 3,
      syncStatus: 'Progressing',
      isSynced: false,
      isHealthy: true,
      hasDriftDetected: true,
    },
    {
      id: 'res-04',
      resourceKind: 'HorizontalPodAutoscaler',
      resourceName: 'checkout-api-hpa',
      targetNamespace: 'production-checkout',
      syncWave: 4,
      syncStatus: 'Synced',
      isSynced: true,
      isHealthy: true,
      hasDriftDetected: false,
    },
  ],
});

export const createNvmeFabricsRdmaSlide = (id = `slide-${Date.now()}`): NvmeFabricsRdmaSlideData => ({
  id,
  type: 'nvme-over-fabrics-rdma-storage',
  title: 'NVMe-over-Fabrics RDMA Storage: Sub-Microsecond Memory Pooling',
  subtitle: 'High-bandwidth zero-copy storage disaggregation leveraging RoCEv2 and hardware kernel bypass',
  kicker: 'HIGH-PERFORMANCE FABRIC STORAGE',
  themeId: 'corporate-clean',
  activeStep: 1,
  maxSteps: 4,
  isPublished: true,
  hasPresenterNotes: true,
  storageClusterName: 'ApexFlash NVMe-oF Tier 0',
  fabricProtocol: 'RoCEv2 NVMe-oF over 400GbE',
  aggregateIopsMillion: 10.2,
  p99LatencyMicros: 7.8,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  hasKernelBypassEnabled: true,
  hasMultipathActive: true,
  hasHardwareChecksumEnforced: true,
  hasTelemetryGlow: true,
  fabricStages: [
    {
      stepIndex: 1,
      stageName: 'Queue Pair Setup',
      stageSubtitle: 'Reliable Connected QP handshake with virtual address pinning',
      protocolLayer: 'RoCEv2 Transport Protocol',
      bandwidthGbps: 400,
      isActive: true,
      isCompleted: false,
    },
    {
      stepIndex: 2,
      stageName: 'RDMA Direct DMA',
      stageSubtitle: 'Kernel-bypass memory injection straight into GPU HBM space',
      protocolLayer: 'InfiniBand Verbs / IBV_WR_RDMA_WRITE',
      bandwidthGbps: 400,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 3,
      stageName: 'NVMe Submission',
      stageSubtitle: 'Hardware doorbell ring and lockless controller arbitration',
      protocolLayer: 'NVMe 2.0 Command Set',
      bandwidthGbps: 400,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 4,
      stageName: 'IOPS Attestation',
      stageSubtitle: 'Telemetry validation under 10.2M sustained random 4K IOPS',
      protocolLayer: 'Telemetry Sentry & Quality Gate',
      bandwidthGbps: 400,
      isActive: false,
      isCompleted: false,
    },
  ],
  queuePairs: [
    {
      id: 'qp-01',
      queuePairId: 'QP-0x8A12',
      transportProtocol: 'RoCEv2',
      bufferSizeMb: 2048,
      iopsThroughput: 2550000,
      latencyMicroseconds: 7.4,
      isEstablished: true,
      hasZeroCopyActive: true,
      isHealthy: true,
    },
    {
      id: 'qp-02',
      queuePairId: 'QP-0x8A13',
      transportProtocol: 'RoCEv2',
      bufferSizeMb: 2048,
      iopsThroughput: 2550000,
      latencyMicroseconds: 7.6,
      isEstablished: true,
      hasZeroCopyActive: true,
      isHealthy: true,
    },
    {
      id: 'qp-03',
      queuePairId: 'QP-0x8A14',
      transportProtocol: 'RoCEv2',
      bufferSizeMb: 2048,
      iopsThroughput: 2550000,
      latencyMicroseconds: 8.1,
      isEstablished: true,
      hasZeroCopyActive: true,
      isHealthy: true,
    },
    {
      id: 'qp-04',
      queuePairId: 'QP-0x8A15',
      transportProtocol: 'RoCEv2',
      bufferSizeMb: 2048,
      iopsThroughput: 2550000,
      latencyMicroseconds: 7.9,
      isEstablished: true,
      hasZeroCopyActive: true,
      isHealthy: true,
    },
  ],
});

export const createConfidentialGpuAttestSlide = (id = `slide-${Date.now()}`): ConfidentialGpuAttestSlideData => ({
  id,
  type: 'confidential-gpu-attestation-flow',
  title: 'Confidential GPU Attestation Flow: Hardware-Verified Model Weights',
  subtitle: 'Cryptographic SPDM verification of GPU firmware and enclave memory before injecting proprietary model weights',
  kicker: 'SILICON-LEVEL CONFIDENTIAL COMPUTING',
  themeId: 'corporate-clean',
  activeStep: 1,
  maxSteps: 4,
  isPublished: true,
  hasPresenterNotes: true,
  acceleratorModel: 'NVIDIA H100 Tensor Core 80GB Confidential Computing',
  attestationAuthorityUrl: 'https://attestation.sovereign.internal/v1/verify',
  enclaveSecurityLevel: 'Hardware Enclave Level 5 (SPDM 1.2)',
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  hasHardwareRootOfTrust: true,
  hasEphemeralKeyDecryptionActive: true,
  hasZeroHostAccessEnforced: true,
  hasTelemetryGlow: true,
  attestationStages: [
    {
      stepIndex: 1,
      stageName: 'Nonce Challenge',
      stageSubtitle: 'Cryptographic hardware challenge with 256-bit fresh nonce',
      cryptographicStandard: 'SPDM 1.2 / CHALLENGE_AUTH',
      attestationAuthority: 'Sovereign Key Arbiter',
      isActive: true,
      isCompleted: false,
    },
    {
      stepIndex: 2,
      stageName: 'Measurement Quote',
      stageSubtitle: 'Compilation of signed hardware registers and firmware hashes',
      cryptographicStandard: 'ECDSA P-384 / SHA-384 Measurement',
      attestationAuthority: 'On-Die Hardware Root of Trust',
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 3,
      stageName: 'Remote Attestation',
      stageSubtitle: 'Verification against silicon root certificates and golden hashes',
      cryptographicStandard: 'X.509 RFC 5280 Chain Validation',
      attestationAuthority: 'Enterprise Attestation Sentry',
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 4,
      stageName: 'Ephemeral Key Release',
      stageSubtitle: 'Decryption key injected into protected HBM3e without CPU visibility',
      cryptographicStandard: 'AES-256-GCM Ephemeral Injection',
      attestationAuthority: 'KMS Secure Enclave Tunnel',
      isActive: false,
      isCompleted: false,
    },
  ],
  evidenceNodes: [
    {
      id: 'node-01',
      componentTarget: 'NVIDIA H100 SXM5 Enclave',
      sha384MeasurementHash: '7d2a8f4c1e9b0a2d3f4e5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d',
      expectedGoldenHash: '7d2a8f4c1e9b0a2d3f4e5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d',
      verificationStatus: 'MATCHED',
      isHardwareVerified: true,
      hasTamperProofShield: true,
      isMatched: true,
    },
    {
      id: 'node-02',
      componentTarget: 'vBIOS SPI Firmware Flash',
      sha384MeasurementHash: '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7d2a8f4c1e9b0a2d3f4e5a6b7c8d9e0f',
      expectedGoldenHash: '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7d2a8f4c1e9b0a2d3f4e5a6b7c8d9e0f',
      verificationStatus: 'MATCHED',
      isHardwareVerified: true,
      hasTamperProofShield: true,
      isMatched: true,
    },
    {
      id: 'node-03',
      componentTarget: 'AMD SEV-SNP Host Enclave',
      sha384MeasurementHash: '9c0d1e2f3a4b5c6d7d2a8f4c1e9b0a2d3f4e5a6b7c8d9e0f1a2b3c4d5e6f7a8b',
      expectedGoldenHash: '9c0d1e2f3a4b5c6d7d2a8f4c1e9b0a2d3f4e5a6b7c8d9e0f1a2b3c4d5e6f7a8b',
      verificationStatus: 'MATCHED',
      isHardwareVerified: true,
      hasTamperProofShield: true,
      isMatched: true,
    },
  ],
});

export const createEbpfDdosXdpSlide = (id = `slide-${Date.now()}`): EbpfDdosXdpSlideData => ({
  id,
  type: 'ebpf-ddos-xdp-packet-mitigation',
  title: 'eBPF DDoS XDP Packet Mitigation: Sub-Microsecond Kernel Defense',
  subtitle: 'Early driver hook packet filtering dropping multi-terabit volumetric floods before kernel socket allocation',
  kicker: 'KERNEL-LEVEL PACKET SCRUBBING',
  themeId: 'corporate-clean',
  activeStep: 1,
  maxSteps: 4,
  isPublished: true,
  hasPresenterNotes: true,
  interfaceDevice: 'mlx5_core (Mellanox ConnectX-7 400GbE)',
  attackPeakBandwidthTbps: 2.8,
  droppedPacketRatePercent: 99.8,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  hasXdpDriverModeEnabled: true,
  hasKernelBypassEnforced: true,
  hasZeroCpuAllocationAchieved: true,
  hasTelemetryGlow: true,
  mitigationStages: [
    {
      stepIndex: 1,
      stageName: 'NIC Ingestion',
      stageSubtitle: 'Direct hardware DMA into driver ring buffer',
      kernelHookLocation: 'Driver RX Ring Descriptor',
      processingBudgetNanoseconds: 10,
      isActive: true,
      isCompleted: false,
    },
    {
      stepIndex: 2,
      stageName: 'XDP Hook Parse',
      stageSubtitle: 'Linear packet header decoding without sk_buff allocation',
      kernelHookLocation: 'xdp_buff Raw Frame Hook',
      processingBudgetNanoseconds: 15,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 3,
      stageName: 'BPF Map Lookup',
      stageSubtitle: 'Bloom filter lookup across 16M synchronized blacklist CIDRs',
      kernelHookLocation: 'BPF_MAP_TYPE_LPM_TRIE',
      processingBudgetNanoseconds: 20,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 4,
      stageName: 'XDP_DROP Action',
      stageSubtitle: 'Instant frame recycling back to NIC ring buffer',
      kernelHookLocation: 'NIC TX Descriptor Recycler',
      processingBudgetNanoseconds: 5,
      isActive: false,
      isCompleted: false,
    },
  ],
  filters: [
    {
      id: 'filter-01',
      filterName: 'SYN-Flood Rate Limiter',
      actionType: 'XDP_DROP',
      packetThroughputMpps: 84.2,
      droppedPacketsTotal: 1420800000,
      isFilterActive: true,
      hasHardwareOffload: true,
      isHealthy: true,
    },
    {
      id: 'filter-02',
      filterName: 'UDP Amplification Shield',
      actionType: 'XDP_DROP',
      packetThroughputMpps: 42.1,
      droppedPacketsTotal: 890400000,
      isFilterActive: true,
      hasHardwareOffload: true,
      isHealthy: true,
    },
    {
      id: 'filter-03',
      filterName: 'Legitimate API Traffic Pass',
      actionType: 'XDP_PASS',
      packetThroughputMpps: 12.8,
      droppedPacketsTotal: 0,
      isFilterActive: true,
      hasHardwareOffload: false,
      isHealthy: true,
    },
  ],
});

export const createActiveInferenceMemorySlide = (id = `slide-${Date.now()}`): ActiveInferenceMemorySlideData => ({
  id,
  type: 'active-inference-memory-tiering',
  title: 'Active Inference Memory Tiering: 1M Token Context with Zero Stall',
  subtitle: 'Intelligent PagedAttention KV cache migration balancing HBM3e, CXL pooled DRAM, and NVMe storage',
  kicker: 'HIGH-PERFORMANCE INFERENCE ARCHITECTURE',
  themeId: 'corporate-clean',
  activeStep: 1,
  maxSteps: 4,
  isPublished: true,
  hasPresenterNotes: true,
  modelContextWindowTokens: 1000000,
  inferenceEngineName: 'vLLM PagedAttention Enterprise',
  overallCacheHitRatePercent: 98.7,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  hasPrefetchPredictorActive: true,
  hasZeroStallGuaranteed: true,
  hasDynamicEvictionEnabled: true,
  hasTelemetryGlow: true,
  tieringStages: [
    {
      stepIndex: 1,
      stageName: 'Attention Profiling',
      stageSubtitle: 'Real-time attention matrix evaluation identifying active token clusters',
      memoryTierTarget: 'Profiler Telemetry Engine',
      cacheHitRatePercent: 100.0,
      isActive: true,
      isCompleted: false,
    },
    {
      stepIndex: 2,
      stageName: 'HBM3e Working Set',
      stageSubtitle: 'Immediate generation context held in 3.2 TB/s GPU High Bandwidth Memory',
      memoryTierTarget: 'Tier 0: HBM3e',
      cacheHitRatePercent: 99.4,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 3,
      stageName: 'CXL 3.0 Migration',
      stageSubtitle: 'Asynchronous eviction of warm conversational context into pooled host memory',
      memoryTierTarget: 'Tier 1: CXL 3.0 DRAM',
      cacheHitRatePercent: 97.8,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 4,
      stageName: 'NVMe Flash Prefetch',
      stageSubtitle: 'Speculative background prefetching from enterprise NVMe flash arrays',
      memoryTierTarget: 'Tier 2: NVMe Flash',
      cacheHitRatePercent: 96.2,
      isActive: false,
      isCompleted: false,
    },
  ],
  memoryTiers: [
    {
      id: 'tier-0',
      tierName: 'Tier 0: GPU HBM3e',
      bandwidthCapacityTbps: 3.2,
      storageCapacityGb: 80,
      averageAccessLatencyNs: 1.2,
      activeContextTokens: 131072,
      isTierActive: true,
      hasPagingEnabled: true,
      isSaturated: false,
    },
    {
      id: 'tier-1',
      tierName: 'Tier 1: CXL 3.0 Pooled DRAM',
      bandwidthCapacityTbps: 0.25,
      storageCapacityGb: 512,
      averageAccessLatencyNs: 32.0,
      activeContextTokens: 524288,
      isTierActive: true,
      hasPagingEnabled: true,
      isSaturated: false,
    },
    {
      id: 'tier-2',
      tierName: 'Tier 2: NVMe QLC Flash',
      bandwidthCapacityTbps: 0.028,
      storageCapacityGb: 4096,
      averageAccessLatencyNs: 4800.0,
      activeContextTokens: 344640,
      isTierActive: true,
      hasPagingEnabled: true,
      isSaturated: false,
    },
  ],
});

export const createSovereignAiCleanRoomSlide = (id = `slide-${Date.now()}`): SovereignAiCleanRoomSlideData => ({
  id,
  type: 'sovereign-ai-data-clean-room',
  title: 'Sovereign AI Data Clean Room: Zero-Trust Multi-Party Collaboration',
  subtitle: 'Cryptographically isolated confidential computing enclaves executing joint AI analytics without exposing underlying raw datasets',
  kicker: 'CONFIDENTIAL MULTI-PARTY DATA GOVERNANCE',
  themeId: 'corporate-clean',
  activeStep: 1,
  maxSteps: 4,
  isPublished: true,
  hasPresenterNotes: true,
  cleanRoomTitle: 'Trans-Atlantic Financial Intelligence Mesh',
  confidentialEnclaveProvider: 'Sovereign Enclave Platform / AMD SEV-SNP',
  complianceCertification: 'EU GDPR Article 28 + HIPAA Title II',
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  hasDifferentialPrivacyEnforced: true,
  hasHomomorphicEncryptionActive: true,
  hasMultiPartyConsensusCertified: true,
  hasTelemetryGlow: true,
  cleanRoomStages: [
    {
      stepIndex: 1,
      stageName: 'Encrypted Ingestion',
      stageSubtitle: 'Client-side encrypted payload transfer via mutual TLS',
      governanceProtocol: 'AES-256-GCM + Threshold Secret Sharing',
      differentialEpsilonUsed: 0.0,
      isActive: true,
      isCompleted: false,
    },
    {
      stepIndex: 2,
      stageName: 'Enclave Provisioning',
      stageSubtitle: 'Hardware-attested confidential virtual machine initialization',
      governanceProtocol: 'AMD SEV-SNP Memory Encryption',
      differentialEpsilonUsed: 0.0,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 3,
      stageName: 'Differential Compute',
      stageSubtitle: 'Bounded query evaluation with Laplacian noise injection',
      governanceProtocol: 'Differential Privacy (e=0.48, d=1e-6)',
      differentialEpsilonUsed: 0.48,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 4,
      stageName: 'Attested Clean Export',
      stageSubtitle: 'Cryptographically signed aggregate model weights release',
      governanceProtocol: 'Multi-Sig Officer Attestation Gate',
      differentialEpsilonUsed: 0.48,
      isActive: false,
      isCompleted: false,
    },
  ],
  participants: [
    {
      id: 'part-01',
      participantOrg: 'Zurich Financial Group',
      jurisdictionRegion: 'CH-Zurich',
      datasetName: 'Cross-Border Fraud Vector Index',
      recordCount: 14200000,
      privacyEpsilonBudget: 0.5,
      isIngestionComplete: true,
      hasAttestationConfirmed: true,
      isEncrypted: true,
    },
    {
      id: 'part-02',
      participantOrg: 'EuroMed Clinical Research',
      jurisdictionRegion: 'EU-Frankfurt',
      datasetName: 'Rare Pathology Anonymized Ledger',
      recordCount: 4800000,
      privacyEpsilonBudget: 0.5,
      isIngestionComplete: true,
      hasAttestationConfirmed: true,
      isEncrypted: true,
    },
  ],
});

export const createIncidentCommandPlaybookSlide = (id = `slide-${Date.now()}`): IncidentCommandPlaybookSlideData => ({
  id,
  type: 'incident-command-automated-playbook',
  title: 'Incident Command Automated Playbook: Sub-Minute MTTR Remediation',
  subtitle: 'Deterministic multi-signal triage, blast-radius containment, and self-healing automated playbook orchestration',
  kicker: 'AUTONOMOUS SRE INCIDENT RESPONSE',
  themeId: 'corporate-clean',
  activeStep: 1,
  maxSteps: 4,
  isPublished: true,
  hasPresenterNotes: true,
  incidentId: 'INC-2026-8914',
  incidentSeverityBadge: 'SEV-1 (CRITICAL OUTAGE)',
  meanTimeToRecoverySeconds: 42.0,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  hasAutonomousExecutionApproved: true,
  hasCircuitBreakerActive: true,
  hasPostMortemGenerated: true,
  hasTelemetryGlow: true,
  playbookStages: [
    {
      stepIndex: 1,
      stageName: 'Anomaly Triaged',
      stageSubtitle: 'Cross-correlation of P99 latency anomalies and SLO burn alerts',
      orchestratorBot: 'SRE Sentinel Bot v3',
      serviceAvailabilityPercent: 96.4,
      isActive: true,
      isCompleted: false,
    },
    {
      stepIndex: 2,
      stageName: 'Blast Radius Isolation',
      stageSubtitle: 'Graph dependency isolation preventing cascading checkout failure',
      orchestratorBot: 'Topology Sentry Engine',
      serviceAvailabilityPercent: 98.2,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 3,
      stageName: 'Automated Mitigation',
      stageSubtitle: 'Canary rollback to stable v2.3.9 and traffic shed execution',
      orchestratorBot: 'ArgoCD Rollback Orchestrator',
      serviceAvailabilityPercent: 99.9,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 4,
      stageName: 'Post-Mortem Seal',
      stageSubtitle: 'Automated 4-part RCA synthesis and executive review dispatch',
      orchestratorBot: 'RCA Intelligence Synthesizer',
      serviceAvailabilityPercent: 100.0,
      isActive: false,
      isCompleted: false,
    },
  ],
  remediationActions: [
    {
      id: 'action-01',
      actionOrder: 1,
      actionTitle: 'Trip Ingress Circuit Breaker',
      executionStatus: 'EXECUTED',
      executionLatencySeconds: 1.2,
      mitigationImpactSummary: 'Shed 40% non-critical traffic to reserve backend thread pool',
      isExecuted: true,
      isVerified: true,
      hasRollbackSucceeded: true,
    },
    {
      id: 'action-02',
      actionOrder: 2,
      actionTitle: 'Canary Rollback to v2.3.9',
      executionStatus: 'CONFIRMED',
      executionLatencySeconds: 14.8,
      mitigationImpactSummary: 'Restored 100% traffic to verified stable release deployment',
      isExecuted: true,
      isVerified: true,
      hasRollbackSucceeded: true,
    },
  ],
});

export const createGpuHbmInterconnectSlide = (id = `slide-${Date.now()}`): GpuHbmInterconnectSlideData => ({
  id,
  type: 'gpu-hbm-interconnect-mesh',
  title: 'GPU HBM Interconnect Mesh: 28.8 TB/s Bisection Bandwidth',
  subtitle: 'Non-blocking all-to-all NVLink mesh interconnecting 8x SXM5 accelerator dies with unified HBM3e memory pool',
  kicker: 'SILICON FABRIC ARCHITECTURE',
  themeId: 'corporate-clean',
  activeStep: 1,
  maxSteps: 1,
  isPublished: true,
  hasPresenterNotes: true,
  clusterFabricModel: '8x NVIDIA H100 SXM5 NVLink Mesh',
  aggregateMemoryGb: 768,
  bisectionBandwidthTbps: 28.8,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  hasDirectPeerAccessEnabled: true,
  hasHardwareWatchdogActive: true,
  hasThermalThrottlingAverted: true,
  gpus: [
    {
      gpuId: 'GPU-00',
      dieIndex: 0,
      hbmCapacityGigabytes: 96,
      hbmBandwidthTbps: 3.35,
      temperatureCelsius: 62,
      powerDrawWatts: 680,
      isOnline: true,
      hasNvLinkActive: true,
    },
    {
      gpuId: 'GPU-01',
      dieIndex: 1,
      hbmCapacityGigabytes: 96,
      hbmBandwidthTbps: 3.35,
      temperatureCelsius: 64,
      powerDrawWatts: 700,
      isOnline: true,
      hasNvLinkActive: true,
    },
    {
      gpuId: 'GPU-02',
      dieIndex: 2,
      hbmCapacityGigabytes: 96,
      hbmBandwidthTbps: 3.35,
      temperatureCelsius: 63,
      powerDrawWatts: 690,
      isOnline: true,
      hasNvLinkActive: true,
    },
    {
      gpuId: 'GPU-03',
      dieIndex: 3,
      hbmCapacityGigabytes: 96,
      hbmBandwidthTbps: 3.35,
      temperatureCelsius: 65,
      powerDrawWatts: 710,
      isOnline: true,
      hasNvLinkActive: true,
    },
    {
      gpuId: 'GPU-04',
      dieIndex: 4,
      hbmCapacityGigabytes: 96,
      hbmBandwidthTbps: 3.35,
      temperatureCelsius: 61,
      powerDrawWatts: 670,
      isOnline: true,
      hasNvLinkActive: true,
    },
    {
      gpuId: 'GPU-05',
      dieIndex: 5,
      hbmCapacityGigabytes: 96,
      hbmBandwidthTbps: 3.35,
      temperatureCelsius: 66,
      powerDrawWatts: 720,
      isOnline: true,
      hasNvLinkActive: true,
    },
    {
      gpuId: 'GPU-06',
      dieIndex: 6,
      hbmCapacityGigabytes: 96,
      hbmBandwidthTbps: 3.35,
      temperatureCelsius: 63,
      powerDrawWatts: 695,
      isOnline: true,
      hasNvLinkActive: true,
    },
    {
      gpuId: 'GPU-07',
      dieIndex: 7,
      hbmCapacityGigabytes: 96,
      hbmBandwidthTbps: 3.35,
      temperatureCelsius: 64,
      powerDrawWatts: 705,
      isOnline: true,
      hasNvLinkActive: true,
    },
  ],
  fabricMetrics: [
    {
      switchLayer: 'NVSwitch 3rd Gen Fabric',
      bisectionBandwidthTbps: 28.8,
      linkErrorRatePerMillion: 0.0,
      isFabricHealthy: true,
    },
  ],
});

export const createRealtimeFeatureStoreSlide = (id = `slide-${Date.now()}`): RealtimeFeatureStoreSlideData => ({
  id,
  type: 'realtime-feature-store-feast',
  title: 'Realtime Feature Store Feast: Sub-3ms Online Feature Serving',
  subtitle: 'Unified online-offline machine learning feature store delivering sub-3ms inference lookups and leak-free training lineage',
  kicker: 'ENTERPRISE ML FEATURE PLATFORM',
  themeId: 'corporate-clean',
  activeStep: 1,
  maxSteps: 1,
  isPublished: true,
  hasPresenterNotes: true,
  featureRegistryName: 'Feast Enterprise ML Platform',
  totalRegisteredFeatures: 1480,
  onlineReadThroughputQps: 280000,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  hasStreamingIngestionActive: true,
  hasDataDriftDetectionEnabled: true,
  hasZeroLeakageCertified: true,
  featureViews: [
    {
      entityName: 'user_instant_risk_profile',
      onlineStoreProvider: 'DragonflyDB / In-Memory KV',
      offlineWarehouse: 'Apache Iceberg Lakehouse',
      servingLatencyP99Ms: 1.8,
      freshnessSlaSeconds: 1,
      isPointInTimeCorrect: true,
      isOnlineStoreReady: true,
    },
    {
      entityName: 'merchant_velocity_10m',
      onlineStoreProvider: 'DragonflyDB / In-Memory KV',
      offlineWarehouse: 'Apache Iceberg Lakehouse',
      servingLatencyP99Ms: 2.1,
      freshnessSlaSeconds: 2,
      isPointInTimeCorrect: true,
      isOnlineStoreReady: true,
    },
  ],
  metrics: [
    {
      metricName: 'P99 Serving Latency',
      metricValue: '1.8ms',
      isHealthy: true,
    },
    {
      metricName: 'Feature Drift Rate',
      metricValue: '0.00%',
      isHealthy: true,
    },
  ],
});

export const createDistributedWalRaftSlide = (id = `slide-${Date.now()}`): DistributedWalRaftSlideData => ({
  id,
  type: 'distributed-wal-raft-consensus',
  title: 'Distributed WAL Raft Consensus: Strict Linearizable Durability',
  subtitle: 'Consensus state machine replication across a 5-node quorum ensuring zero data loss and sub-millisecond fsync commits',
  kicker: 'DISTRIBUTED CONSENSUS SYSTEMS',
  themeId: 'corporate-clean',
  activeStep: 1,
  maxSteps: 1,
  isPublished: true,
  hasPresenterNotes: true,
  clusterName: 'Consensus Raft Cluster (5 Replicas)',
  currentRaftTerm: 148,
  commitWatermarkIndex: 8421902,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  hasQuorumReplicated: true,
  hasStrictFsyncDurability: true,
  hasLinearizableReadsEnforced: true,
  raftNodes: [
    {
      nodeId: 'raft-node-01',
      role: 'Leader',
      currentTerm: 148,
      lastLogIndex: 8421902,
      commitIndex: 8421902,
      replicationLagMs: 0.0,
      isLeader: true,
      isHealthy: true,
    },
    {
      nodeId: 'raft-node-02',
      role: 'Follower',
      currentTerm: 148,
      lastLogIndex: 8421902,
      commitIndex: 8421902,
      replicationLagMs: 0.1,
      isLeader: false,
      isHealthy: true,
    },
    {
      nodeId: 'raft-node-03',
      role: 'Follower',
      currentTerm: 148,
      lastLogIndex: 8421902,
      commitIndex: 8421902,
      replicationLagMs: 0.1,
      isLeader: false,
      isHealthy: true,
    },
    {
      nodeId: 'raft-node-04',
      role: 'Follower',
      currentTerm: 148,
      lastLogIndex: 8421901,
      commitIndex: 8421901,
      replicationLagMs: 0.3,
      isLeader: false,
      isHealthy: true,
    },
    {
      nodeId: 'raft-node-05',
      role: 'Follower',
      currentTerm: 148,
      lastLogIndex: 8421902,
      commitIndex: 8421902,
      replicationLagMs: 0.2,
      isLeader: false,
      isHealthy: true,
    },
  ],
  recentLogEntries: [
    {
      logIndex: 8421902,
      term: 148,
      commandPayload: 'TX_SET(user:8912, balance:+5000)',
      isCommitted: true,
      isFsynced: true,
    },
  ],
});

export const createFinopsUnitEconomicsSlide = (id = `slide-${Date.now()}`): FinopsUnitEconomicsSlideData => ({
  id,
  type: 'finops-unit-economics-cloud-matrix',
  title: 'FinOps Unit Economics Cloud Matrix: Cost-Per-Token Efficiency',
  subtitle: 'Granular multi-cloud unit economics tracing cloud spend per inference token, commitment coverage, and spot arbitrage',
  kicker: 'CLOUD COST GOVERNANCE & FINOPS',
  themeId: 'corporate-clean',
  activeStep: 1,
  maxSteps: 1,
  isPublished: true,
  hasPresenterNotes: true,
  reportingFiscalPeriod: 'Q4 2026 Executive FinOps Audit',
  totalMonthlyCloudSpendUsd: 1420000,
  blendedCostPerTokenCent: 0.00014,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  hasMultiCloudArbitrageActive: true,
  hasReservedCapacitySecured: true,
  hasCarbonOffsetIncluded: true,
  workloads: [
    {
      workloadName: 'Frontier LLM Inference',
      cloudProvider: 'CoreWeave GPU Cluster',
      costPerMillionTokensUsd: 0.12,
      monthlySpendUsd: 620000,
      commitmentDiscountCoveragePercent: 95.0,
      isOptimized: true,
      hasBudgetAlertAverted: true,
    },
    {
      workloadName: 'Vector Embeddings Milvus',
      cloudProvider: 'GCP europe-west3',
      costPerMillionTokensUsd: 0.04,
      monthlySpendUsd: 240000,
      commitmentDiscountCoveragePercent: 90.0,
      isOptimized: true,
      hasBudgetAlertAverted: true,
    },
    {
      workloadName: 'Real-Time Feature Ingestion',
      cloudProvider: 'AWS us-east-1',
      costPerMillionTokensUsd: 0.02,
      monthlySpendUsd: 180000,
      commitmentDiscountCoveragePercent: 94.0,
      isOptimized: true,
      hasBudgetAlertAverted: true,
    },
  ],
  kpis: [
    {
      kpiTitle: 'Commitment Coverage',
      metricFormatted: '92.4%',
      isTargetMet: true,
    },
    {
      kpiTitle: 'Unit Margin Improvement',
      metricFormatted: '+42% YoY',
      isTargetMet: true,
    },
  ],
});

export const createCrossBorderDataResidencySlide = (id = `slide-${Date.now()}`): CrossBorderDataResidencySlideData => ({
  id,
  type: 'cross-border-privacy-data-residency',
  title: 'Cross-Border Privacy Data Residency: Air-Gapped Geo-Fencing',
  subtitle: 'Cryptographically enforced territorial data fences ensuring customer records never leave designated legal sovereign jurisdictions',
  kicker: 'GLOBAL REGULATORY & PRIVACY RESIDENCY',
  themeId: 'corporate-clean',
  activeStep: 1,
  maxSteps: 1,
  isPublished: true,
  hasPresenterNotes: true,
  globalComplianceFramework: 'ISO 27701 & Sovereign Privacy Standard',
  monitoredDataStoreCount: 420,
  unauthorizedEgressAttempts: 0,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  hasGeofenceEnforced: true,
  hasCryptographicShardingActive: true,
  hasRealtimeEgressFirewall: true,
  jurisdictions: [
    {
      jurisdictionCode: 'EU-GDPR',
      datacenterLocation: 'Frankfurt, Germany',
      dataRetentionDays: 90,
      encryptionStandard: 'AES-256-GCM + Hardware HSM Pinning',
      egressFenceStatus: 'ENFORCED',
      isFenced: true,
      hasZeroCrossBorderLeak: true,
      isCompliant: true,
    },
    {
      jurisdictionCode: 'CH-FINMA',
      datacenterLocation: 'Zurich, Switzerland',
      dataRetentionDays: 365,
      encryptionStandard: 'Quantum KEM Enclave Pinning',
      egressFenceStatus: 'AIR-GAPPED',
      isFenced: true,
      hasZeroCrossBorderLeak: true,
      isCompliant: true,
    },
    {
      jurisdictionCode: 'SG-MAS',
      datacenterLocation: 'Singapore, SG',
      dataRetentionDays: 180,
      encryptionStandard: 'AES-256-GCM HSM',
      egressFenceStatus: 'ENFORCED',
      isFenced: true,
      hasZeroCrossBorderLeak: true,
      isCompliant: true,
    },
  ],
  auditRecords: [
    {
      auditFramework: 'GDPR Article 44 Inspection',
      lastInspectionDate: '2026-09-30',
      isAuditPassed: true,
    },
  ],
});

export const createZeroTrustSpiffeSlide = (id = `slide-${Date.now()}`): ZeroTrustSpiffeSlideData => ({
  id,
  type: 'zero-trust-microsegmentation-spiffe',
  title: 'Zero Trust Microsegmentation SPIFFE: Short-Lived SVID Attestation',
  subtitle: 'Cryptographic workload identity mesh issuing automatic 1-hour X.509 certificates and enforcing default-deny microsegmentation',
  kicker: 'CRYPTOGRAPHIC WORKLOAD SECURITY',
  themeId: 'corporate-clean',
  activeStep: 1,
  maxSteps: 1,
  isPublished: true,
  hasPresenterNotes: true,
  trustDomain: 'prod.sovereign.internal',
  activeWorkloadIdentities: 2400,
  svidRotationFrequencyHours: 1,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  hasZeroStaticSecrets: true,
  hasHardwareTpmAttested: true,
  hasStrictDenyAllDefault: true,
  workloads: [
    {
      spiffeId: 'spiffe://prod.sovereign.internal/ns/checkout/sa/payment-api',
      workloadNamespace: 'checkout',
      svidTtlSeconds: 3600,
      certificateIssuer: 'SPIRE Server Cluster CA',
      isIdentityAttested: true,
      hasMtlsEnforced: true,
      isCompliant: true,
    },
    {
      spiffeId: 'spiffe://prod.sovereign.internal/ns/ledger/sa/ledger-vault',
      workloadNamespace: 'ledger',
      svidTtlSeconds: 3600,
      certificateIssuer: 'SPIRE Server Cluster CA',
      isIdentityAttested: true,
      hasMtlsEnforced: true,
      isCompliant: true,
    },
  ],
  securityPolicies: [
    {
      sourceWorkload: 'spiffe://prod.sovereign.internal/ns/checkout/sa/payment-api',
      destinationWorkload: 'spiffe://prod.sovereign.internal/ns/ledger/sa/ledger-vault',
      authorizedMethod: 'POST /v1/charge',
      isEnforced: true,
    },
  ],
});

export const createBoardCapitalAllocationSlide = (id = `slide-${Date.now()}`): BoardCapitalAllocationSlideData => ({
  id,
  type: 'enterprise-board-capital-allocation',
  title: 'Enterprise Board Capital Allocation: Strategic Capex Matrix',
  subtitle: 'Fiduciary governance matrix optimizing capital deployment across sovereign AI accelerators, distributed mesh networking, and cybersecurity',
  kicker: 'EXECUTIVE BOARDROOM GOVERNANCE',
  themeId: 'corporate-clean',
  activeStep: 1,
  maxSteps: 1,
  isPublished: true,
  hasPresenterNotes: true,
  fiscalYear: 'FY 2027 Capital Budget',
  totalCapitalBudgetMillionsUsd: 85.0,
  minimumHurdleRatePercent: 18.0,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  hasExecutiveSignoffCompleted: true,
  hasFiduciaryAuditApproved: true,
  hasRiskAdjustedReturnVerified: true,
  allocations: [
    {
      projectId: 'proj-01',
      projectTitle: 'Sovereign AI Compute Cluster',
      allocatedCapitalMillionsUsd: 45.0,
      projectedInternalRateOfReturnPercent: 34.2,
      paybackPeriodYears: 1.8,
      hurdleRatePassed: true,
      isBoardApproved: true,
    },
    {
      projectId: 'proj-02',
      projectTitle: 'Multi-Cloud Edge CDN Mesh',
      allocatedCapitalMillionsUsd: 22.0,
      projectedInternalRateOfReturnPercent: 24.8,
      paybackPeriodYears: 2.4,
      hurdleRatePassed: true,
      isBoardApproved: true,
    },
    {
      projectId: 'proj-03',
      projectTitle: 'Zero-Trust SPIFFE Identity Mesh',
      allocatedCapitalMillionsUsd: 18.0,
      projectedInternalRateOfReturnPercent: 28.5,
      paybackPeriodYears: 2.1,
      hurdleRatePassed: true,
      isBoardApproved: true,
    },
  ],
  governanceHurdles: [
    {
      governanceClause: 'Minimum Internal Rate of Return > 18.0%',
      hurdleThresholdPercent: 18.0,
      isHurdleSatisfied: true,
    },
  ],
});

export const GLOBAL_PPT_NEXTGEN_FACTORIES: Record<string, (id?: string) => GlobalPptNextGenSlideData> = {
  'agentic-eval-red-team-harness': createAgenticEvalRedTeamSlide,
  'gitops-argocd-sync-reconciliation': createGitOpsArgoCdSyncSlide,
  'nvme-over-fabrics-rdma-storage': createNvmeFabricsRdmaSlide,
  'confidential-gpu-attestation-flow': createConfidentialGpuAttestSlide,
  'ebpf-ddos-xdp-packet-mitigation': createEbpfDdosXdpSlide,
  'active-inference-memory-tiering': createActiveInferenceMemorySlide,
  'sovereign-ai-data-clean-room': createSovereignAiCleanRoomSlide,
  'incident-command-automated-playbook': createIncidentCommandPlaybookSlide,
  'gpu-hbm-interconnect-mesh': createGpuHbmInterconnectSlide,
  'realtime-feature-store-feast': createRealtimeFeatureStoreSlide,
  'distributed-wal-raft-consensus': createDistributedWalRaftSlide,
  'finops-unit-economics-cloud-matrix': createFinopsUnitEconomicsSlide,
  'cross-border-privacy-data-residency': createCrossBorderDataResidencySlide,
  'zero-trust-microsegmentation-spiffe': createZeroTrustSpiffeSlide,
  'enterprise-board-capital-allocation': createBoardCapitalAllocationSlide,
};

export const GLOBAL_PPT_NEXTGEN_ARCHETYPE_OPTIONS: ArchetypeOption[] = [
  {
    type: 'agentic-eval-red-team-harness',
    label: 'Agentic Eval Red-Team Harness',
    category: 'AI Infrastructure',
    desc: 'Autonomous adversarial jailbreak testing & real-time guardrail synthesis',
    icon: 'ShieldAlert',
  },
  {
    type: 'gitops-argocd-sync-reconciliation',
    label: 'GitOps ArgoCD Sync Reconciliation',
    category: 'Product & Architecture',
    desc: 'Continuous Git-to-cluster synchronization & declarative multi-wave drift repair',
    icon: 'GitMerge',
  },
  {
    type: 'nvme-over-fabrics-rdma-storage',
    label: 'NVMe-over-Fabrics RDMA Storage',
    category: 'Product & Architecture',
    desc: 'Sub-microsecond kernel-bypass memory pooling & RoCEv2 transport',
    icon: 'HardDrive',
  },
  {
    type: 'confidential-gpu-attestation-flow',
    label: 'Confidential GPU Attestation Flow',
    category: 'AI Infrastructure',
    desc: 'Silicon-level SPDM hardware verification & encrypted model weight release',
    icon: 'Lock',
  },
  {
    type: 'ebpf-ddos-xdp-packet-mitigation',
    label: 'eBPF DDoS XDP Packet Mitigation',
    category: 'Platform & Network',
    desc: 'Sub-microsecond driver hook packet filtering dropping volumetric multi-terabit attacks',
    icon: 'Shield',
  },
  {
    type: 'active-inference-memory-tiering',
    label: 'Active Inference Memory Tiering',
    category: 'AI Infrastructure',
    desc: 'Intelligent PagedAttention KV cache migration balancing HBM3e, CXL, and NVMe',
    icon: 'Cpu',
  },
  {
    type: 'sovereign-ai-data-clean-room',
    label: 'Sovereign AI Data Clean Room',
    category: 'Corporate Strategy',
    desc: 'Confidential multi-party data collaboration with differential privacy guarantees',
    icon: 'Key',
  },
  {
    type: 'incident-command-automated-playbook',
    label: 'Incident Command Automated Playbook',
    category: 'Product & Architecture',
    desc: 'Autonomous multi-signal triage, circuit breaking, and sub-minute MTTR response',
    icon: 'AlertTriangle',
  },
  {
    type: 'gpu-hbm-interconnect-mesh',
    label: 'GPU HBM Interconnect Mesh',
    category: 'AI Infrastructure',
    desc: '28.8 TB/s bisection bandwidth non-blocking all-to-all NVLink mesh',
    icon: 'Grid',
  },
  {
    type: 'realtime-feature-store-feast',
    label: 'Realtime Feature Store Feast',
    category: 'Product & Architecture',
    desc: 'Sub-3ms online feature serving with zero training-serving skew',
    icon: 'Database',
  },
  {
    type: 'distributed-wal-raft-consensus',
    label: 'Distributed WAL Raft Consensus',
    category: 'Product & Architecture',
    desc: 'Strict linearizable Raft consensus replication across a 5-node quorum',
    icon: 'Layers',
  },
  {
    type: 'finops-unit-economics-cloud-matrix',
    label: 'FinOps Unit Economics Cloud Matrix',
    category: 'Corporate Strategy',
    desc: 'Cost-per-token efficiency tracing cloud spend per inference token',
    icon: 'TrendingUp',
  },
  {
    type: 'cross-border-privacy-data-residency',
    label: 'Cross-Border Privacy Data Residency',
    category: 'Corporate Strategy',
    desc: 'Air-gapped territorial data fences preventing unauthorized cross-border egress',
    icon: 'Globe',
  },
  {
    type: 'zero-trust-microsegmentation-spiffe',
    label: 'Zero-Trust Microsegmentation SPIFFE',
    category: 'Platform & Network',
    desc: 'Short-lived SVID attestation and default-deny microsegmentation mesh',
    icon: 'CheckCircle2',
  },
  {
    type: 'enterprise-board-capital-allocation',
    label: 'Enterprise Board Capital Allocation',
    category: 'Corporate Strategy',
    desc: 'Fiduciary strategic Capex matrix optimizing multi-million dollar capital deployment',
    icon: 'DollarSign',
  },
];
