// lint-allow: file-size reason="Kinetic Revolution slide default factories for 15 archetypes" max=750
import type {
  GpuClusterFabricSlideData,
  RagNeedleHaystackSlideData,
  EbpfKernelTelemetrySlideData,
  AiInferenceTokenEconomicsSlideData,
  MicroFrontendFederationSlideData,
  ProgressiveDeliveryCanarySlideData,
  DataMeshFederatedSlideData,
  ThreatExposureCtemSlideData,
  SubseaCableGlobalBackboneSlideData,
  MultiAgentReflectionSlideData,
  SemanticCacheHitSlideData,
  SaasNetRevenueRetentionSlideData,
  ConfidentialMpcKeyVaultSlideData,
  DeveloperFrictionDxSlideData,
  BoardroomMaSynergySlideData,
  KineticRevolutionSlideData,
} from '../types/kineticRevolutionArchetypes';
import type { ArchetypeOption } from './extendedSlideFactories';

export const createGpuClusterFabricSlide = (id = `slide-${Date.now()}`): GpuClusterFabricSlideData => ({
  id,
  type: 'gpu-cluster-fabric-interconnect',
  title: 'GPU Cluster Fabric Interconnect: 3.2 Tbps NVLink & RoCEv2 Rails',
  subtitle: 'Distributed non-blocking optical switching topology orchestrating 8-node GPU acceleration across high-throughput collective primitives.',
  kicker: 'AI INFRASTRUCTURE ACCELERATION',
  fabricArchitecture: 'NVSwitch Spine-Leaf Fabric + Dual-Rail RoCEv2',
  totalFlopsFormatted: '128 PFLOPS FP8',
  totalGpuNodes: 8,
  interconnectProtocol: 'RoCEv2',
  bisectionBandwidthTbps: 51.2,
  hasAdaptiveRoutingEnabled: true,
  hasPacketTelemetry: true,
  nodes: [
    { id: 'gpu-01', name: 'GPU Node 01', nodeType: 'compute-h100', gpuCount: 8, memoryGb: 192, bandwidthGbps: 3200, temperatureCelsius: 54, isActive: true, hasGlow: true, hasRoceV2Enabled: true },
    { id: 'gpu-02', name: 'GPU Node 02', nodeType: 'compute-h100', gpuCount: 8, memoryGb: 192, bandwidthGbps: 3200, temperatureCelsius: 56, isActive: true, hasGlow: false, hasRoceV2Enabled: true },
    { id: 'gpu-03', name: 'GPU Node 03', nodeType: 'compute-h100', gpuCount: 8, memoryGb: 192, bandwidthGbps: 3200, temperatureCelsius: 53, isActive: true, hasGlow: false, hasRoceV2Enabled: true },
    { id: 'gpu-04', name: 'GPU Node 04', nodeType: 'compute-h100', gpuCount: 8, memoryGb: 192, bandwidthGbps: 3200, temperatureCelsius: 55, isActive: true, hasGlow: false, hasRoceV2Enabled: true },
    { id: 'gpu-05', name: 'GPU Node 05', nodeType: 'compute-h100', gpuCount: 8, memoryGb: 192, bandwidthGbps: 3200, temperatureCelsius: 54, isActive: true, hasGlow: false, hasRoceV2Enabled: true },
    { id: 'gpu-06', name: 'GPU Node 06', nodeType: 'compute-h100', gpuCount: 8, memoryGb: 192, bandwidthGbps: 3200, temperatureCelsius: 55, isActive: true, hasGlow: false, hasRoceV2Enabled: true },
    { id: 'gpu-07', name: 'GPU Node 07', nodeType: 'compute-h100', gpuCount: 8, memoryGb: 192, bandwidthGbps: 3200, temperatureCelsius: 57, isActive: true, hasGlow: false, hasRoceV2Enabled: true },
    { id: 'gpu-08', name: 'GPU Node 08', nodeType: 'compute-h100', gpuCount: 8, memoryGb: 192, bandwidthGbps: 3200, temperatureCelsius: 54, isActive: true, hasGlow: true, hasRoceV2Enabled: true },
  ],
  links: [
    { id: 'link-01', sourceNodeId: 'gpu-01', targetNodeId: 'spine-01', linkSpeedGbps: 800, latencyNanoseconds: 450, isActive: true, hasAdaptiveRoutingEnabled: true, utilizationPercent: 92 },
    { id: 'link-02', sourceNodeId: 'gpu-02', targetNodeId: 'spine-01', linkSpeedGbps: 800, latencyNanoseconds: 450, isActive: true, hasAdaptiveRoutingEnabled: true, utilizationPercent: 94 },
    { id: 'link-03', sourceNodeId: 'gpu-03', targetNodeId: 'spine-02', linkSpeedGbps: 800, latencyNanoseconds: 460, isActive: true, hasAdaptiveRoutingEnabled: true, utilizationPercent: 89 },
    { id: 'link-04', sourceNodeId: 'gpu-04', targetNodeId: 'spine-02', linkSpeedGbps: 800, latencyNanoseconds: 460, isActive: true, hasAdaptiveRoutingEnabled: true, utilizationPercent: 91 },
  ],
  metrics: [
    { id: 'm-01', label: 'Bisection Bandwidth', value: '51.2', unit: 'Tbps', isOptimal: true, hasAlert: false },
    { id: 'm-02', label: 'RoCEv2 P99 Latency', value: '1.25', unit: 'µs', isOptimal: true, hasAlert: false },
    { id: 'm-03', label: 'Packet Drops Rate', value: '0.000', unit: '%', isOptimal: true, hasAlert: false },
    { id: 'm-04', label: 'All-Reduce Scaling', value: '98.4', unit: '%', isOptimal: true, hasAlert: false },
  ],
});

export const createRagNeedleHaystackSlide = (id = `slide-${Date.now()}`): RagNeedleHaystackSlideData => ({
  id,
  type: 'rag-needle-haystack-benchmark',
  title: 'RAG Needle in Haystack Benchmark: 8K to 2M Token Context Frontier',
  subtitle: 'Full-depth recall evaluation measuring attention saturation, context attenuation, and precision extraction across multi-megatoken document corpora.',
  kicker: 'ATTENTION MECHANISM EVALUATION',
  testedDocumentDomain: 'Enterprise 10-K & Regulatory Risk Master Corpus',
  contextWindowRange: '8K - 2,048K Tokens',
  needleQuery: 'Specific foreign exchange hedge ratio approved by risk governance in Q3',
  overallRetrievalRate: '99.4%',
  hasLaserSweepGlow: true,
  hasSyntheticNoise: true,
  matrixResults: [
    { id: 'res-8k-10', contextLengthTokens: 8192, depthPercent: 10, retrievalScorePercent: 100, latencyMs: 14, isRetrievedSuccessfully: true, isHighlighted: false },
    { id: 'res-8k-50', contextLengthTokens: 8192, depthPercent: 50, retrievalScorePercent: 100, latencyMs: 15, isRetrievedSuccessfully: true, isHighlighted: false },
    { id: 'res-8k-90', contextLengthTokens: 8192, depthPercent: 90, retrievalScorePercent: 100, latencyMs: 16, isRetrievedSuccessfully: true, isHighlighted: false },
    { id: 'res-128k-10', contextLengthTokens: 131072, depthPercent: 10, retrievalScorePercent: 99.8, latencyMs: 42, isRetrievedSuccessfully: true, isHighlighted: false },
    { id: 'res-128k-50', contextLengthTokens: 131072, depthPercent: 50, retrievalScorePercent: 99.6, latencyMs: 48, isRetrievedSuccessfully: true, isHighlighted: false },
    { id: 'res-128k-90', contextLengthTokens: 131072, depthPercent: 90, retrievalScorePercent: 99.4, latencyMs: 51, isRetrievedSuccessfully: true, isHighlighted: false },
    { id: 'res-1m-10', contextLengthTokens: 1048576, depthPercent: 10, retrievalScorePercent: 99.5, latencyMs: 128, isRetrievedSuccessfully: true, isHighlighted: true },
    { id: 'res-1m-50', contextLengthTokens: 1048576, depthPercent: 50, retrievalScorePercent: 99.2, latencyMs: 135, isRetrievedSuccessfully: true, isHighlighted: true },
    { id: 'res-1m-90', contextLengthTokens: 1048576, depthPercent: 90, retrievalScorePercent: 98.9, latencyMs: 142, isRetrievedSuccessfully: true, isHighlighted: true },
    { id: 'res-2m-50', contextLengthTokens: 2097152, depthPercent: 50, retrievalScorePercent: 98.6, latencyMs: 245, isRetrievedSuccessfully: true, isHighlighted: true },
  ],
  models: [
    { id: 'mod-1', modelName: 'Legacy Naive Vector RAG', contextWindowLimit: '32K', averageAccuracy: 74.2, isBaseline: true, isLeadingModel: false },
    { id: 'mod-2', modelName: 'Chunked Cross-Encoder Rerank', contextWindowLimit: '128K', averageAccuracy: 88.5, isBaseline: false, isLeadingModel: false },
    { id: 'mod-3', modelName: 'Sovereign Long-Context LLM', contextWindowLimit: '2,048K', averageAccuracy: 99.4, isBaseline: false, isLeadingModel: true },
  ],
  insights: [
    { id: 'ins-1', title: 'Zero Attenuation Boundary', description: 'Maintains 99%+ recall up to 1.2M tokens without attention needle loss.', hasSignificantFinding: true },
    { id: 'ins-2', title: 'Sub-150ms P95 Latency', description: 'Hierarchical KV caching accelerates needle retrieval across multi-million token windows.', hasSignificantFinding: true },
    { id: 'ins-3', title: 'Hard Negative Rejection', description: 'Zero false positive matches on adversarial distractor paragraphs.', hasSignificantFinding: false },
  ],
});

export const createEbpfKernelTelemetrySlide = (id = `slide-${Date.now()}`): EbpfKernelTelemetrySlideData => ({
  id,
  type: 'ebpf-kernel-telemetry-observability',
  title: 'Linux eBPF Kernel Telemetry & Non-Invasive Observability',
  subtitle: 'Direct ring-buffer kernel probing delivering zero-overhead tracing, socket filtering, and microsecond syscall anomaly telemetry.',
  kicker: 'KERNEL-LEVEL TELEMETRY',
  kernelVersion: 'Linux 6.8.0-45-generic x86_64',
  totalCapturedEventsPerSecond: '1,450,000 / sec',
  averageOverheadPercent: '< 0.08%',
  hasZeroAllocationVerifier: true,
  hasSyscallTracingActive: true,
  probes: [
    { id: 'p-01', probeName: 'sys_enter_connect', probeType: 'kprobe', subsystem: 'net/socket', eventsPerSecond: 245000, overheadNanoseconds: 8.4, isActive: true, hasRingBufferGlow: true },
    { id: 'p-02', probeName: 'tcp_retransmit_skb', probeType: 'tracepoint', subsystem: 'net/ipv4', eventsPerSecond: 18400, overheadNanoseconds: 4.2, isActive: true, hasRingBufferGlow: false },
    { id: 'p-03', probeName: 'vfs_read_entry', probeType: 'kprobe', subsystem: 'fs/vfs', eventsPerSecond: 680000, overheadNanoseconds: 9.1, isActive: true, hasRingBufferGlow: true },
    { id: 'p-04', probeName: 'xdp_packet_filter', probeType: 'xdp', subsystem: 'net/driver', eventsPerSecond: 506600, overheadNanoseconds: 3.1, isActive: true, hasRingBufferGlow: true },
  ],
  recentTraceEvents: [
    { id: 'ev-1', timestampMicroseconds: 184200, syscallName: 'connect', processName: 'edge-gateway', pid: 4092, returnValue: 0, isAnomaly: false, hasStackTrace: true },
    { id: 'ev-2', timestampMicroseconds: 184224, syscallName: 'epoll_wait', processName: 'envoy-proxy', pid: 1824, returnValue: 14, isAnomaly: false, hasStackTrace: true },
    { id: 'ev-3', timestampMicroseconds: 184280, syscallName: 'tcp_retransmit', processName: 'kernel-core', pid: 0, returnValue: 0, isAnomaly: true, hasStackTrace: true },
  ],
  pillars: [
    { id: 'pil-1', title: 'Kernel Ring Buffer', metric: '64 MB Shared', delta: '0% Drops', isHealthy: true },
    { id: 'pil-2', title: 'Syscall CPU Overhead', metric: '8.4 ns / Call', delta: '-42% vs Strace', isHealthy: true },
    { id: 'pil-3', title: 'JIT Verifier Safety', metric: 'Bytecode Pass', delta: 'Zero Faults', isHealthy: true },
  ],
});

export const createAiInferenceTokenEconomicsSlide = (id = `slide-${Date.now()}`): AiInferenceTokenEconomicsSlideData => ({
  id,
  type: 'ai-inference-token-economics',
  title: 'AI Inference Token Economics: Margin Scaling & Paged KV Cache',
  subtitle: 'Granular unit economics tracking time-to-first-token (TTFT), inter-token latency (ITL), and GPU VRAM offload gross margin realization.',
  kicker: 'FOUNDATION MODEL ECONOMICS',
  primaryModel: 'Claude 3.5 Sonnet / Sovereign 70B',
  monthlyRunRateUsd: '$128,450 / mo',
  averageTtftMs: 142,
  cacheHitDiscountRate: '75% Discount',
  hasKvCacheOffloading: true,
  hasSpeculativeDecoding: true,
  tiers: [
    { id: 't-1', tierName: 'Draft Model (Small)', modelFamily: 'Speculative 8B', inputPricePerMillion: 0.15, outputPricePerMillion: 0.60, ttftP95Ms: 65, tokensPerSecond: 185, isCostLeader: true, isRecommended: false },
    { id: 't-2', tierName: 'Core Production (70B)', modelFamily: 'Sovereign 70B FP8', inputPricePerMillion: 3.00, outputPricePerMillion: 15.00, ttftP95Ms: 142, tokensPerSecond: 98, isCostLeader: false, isRecommended: true },
    { id: 't-3', tierName: 'Frontier Reasoning', modelFamily: 'Claude 3.5 Sonnet', inputPricePerMillion: 15.00, outputPricePerMillion: 75.00, ttftP95Ms: 310, tokensPerSecond: 52, isCostLeader: false, isRecommended: false },
  ],
  costBreakdowns: [
    { id: 'cb-1', category: 'Autonomous AI Agents', monthlyTokensMillion: 1240, allocatedBudgetUsd: 58200, savingsPercent: 42, isOptimized: true },
    { id: 'cb-2', category: 'Code Intelligence Service', monthlyTokensMillion: 820, allocatedBudgetUsd: 36400, savingsPercent: 38, isOptimized: true },
    { id: 'cb-3', category: 'Customer Knowledge RAG', monthlyTokensMillion: 510, allocatedBudgetUsd: 21850, savingsPercent: 55, isOptimized: true },
    { id: 'cb-4', category: 'Document Analysis Pipeline', monthlyTokensMillion: 280, allocatedBudgetUsd: 12000, savingsPercent: 62, isOptimized: true },
  ],
  efficiencyMetrics: [
    { id: 'em-1', label: 'TTFT P95 Target', value: '142 ms', target: '< 180 ms', isMet: true },
    { id: 'em-2', label: 'Inter-Token Latency', value: '10.8 ms', target: '< 15.0 ms', isMet: true },
    { id: 'em-3', label: 'Paged KV Cache Compression', value: '68.4%', target: '> 50.0%', isMet: true },
    { id: 'em-4', label: 'Gross Operating Margin', value: '84.2%', target: '> 75.0%', isMet: true },
  ],
});

export const createMicroFrontendFederationSlide = (id = `slide-${Date.now()}`): MicroFrontendFederationSlideData => ({
  id,
  type: 'micro-frontend-federation-matrix',
  title: 'Micro-Frontend Federation Matrix: Distributed Sovereign Domains',
  subtitle: 'Decoupled autonomous frontend delivery utilizing Module Federation v2, shared singleton core runtimes, and isolated boundary sandboxes.',
  kicker: 'MODERN WEB PLATFORM',
  hostAppName: 'enterprise-portal-host',
  federationFramework: 'Module Federation v2 + Vite 6',
  totalRemotesCount: 4,
  sharedLibEfficiencyRatio: '84% Shared Singletons',
  hasIsolatedRuntimes: true,
  hasZeroBundleDuplication: true,
  remotes: [
    { id: 'rem-1', remoteName: 'analytics-dashboard', teamOwner: 'Data Platform Team', exposedModulesCount: 14, bundleSizeKb: 38, runtimeStatus: 'healthy', isSharedSingleton: true, hasGlow: true },
    { id: 'rem-2', remoteName: 'billing-checkout', teamOwner: 'FinTech Team', exposedModulesCount: 8, bundleSizeKb: 42, runtimeStatus: 'healthy', isSharedSingleton: true, hasGlow: false },
    { id: 'rem-3', remoteName: 'auth-identity-portal', teamOwner: 'SecOps Team', exposedModulesCount: 6, bundleSizeKb: 28, runtimeStatus: 'healthy', isSharedSingleton: true, hasGlow: false },
    { id: 'rem-4', remoteName: 'settings-governance', teamOwner: 'Platform Team', exposedModulesCount: 11, bundleSizeKb: 34, runtimeStatus: 'healthy', isSharedSingleton: true, hasGlow: false },
  ],
  sharedDependencies: [
    { id: 'dep-1', packageName: 'react', requiredVersion: '19.0.0', isSingleton: true, hasVersionMismatch: false, isStrictVersionEnforced: true },
    { id: 'dep-2', packageName: 'zustand', requiredVersion: '5.0.3', isSingleton: true, hasVersionMismatch: false, isStrictVersionEnforced: true },
    { id: 'dep-3', packageName: 'lucide-react', requiredVersion: '1.16.0', isSingleton: true, hasVersionMismatch: false, isStrictVersionEnforced: true },
  ],
  bridgeLinks: [
    { id: 'bl-1', sourceRemoteId: 'enterprise-portal-host', targetRemoteId: 'analytics-dashboard', channelType: 'route-bridge', isActive: true },
    { id: 'bl-2', sourceRemoteId: 'analytics-dashboard', targetRemoteId: 'billing-checkout', channelType: 'event-bus', isActive: true },
    { id: 'bl-3', sourceRemoteId: 'auth-identity-portal', targetRemoteId: 'enterprise-portal-host', channelType: 'shared-store', isActive: true },
  ],
});

export const createProgressiveDeliveryCanarySlide = (id = `slide-${Date.now()}`): ProgressiveDeliveryCanarySlideData => ({
  id,
  type: 'progressive-delivery-canary-gate',
  title: 'Progressive Delivery Canary Gate: Traffic Shift & SLO Automation',
  subtitle: 'Continuous deployment confidence gates executing algorithmic canary traffic shifts from 5% to 100% with automated Prometheus SLO rollback.',
  kicker: 'DEPLOYMENT ORCHESTRATION',
  releaseVersion: 'v2.4.0 (Canary)',
  baselineVersion: 'v2.3.9 (Production Baseline)',
  canaryTrafficRampPercent: 25,
  gateEvaluationWindow: '15-Minute Rolling Prometheus Analysis',
  hasAutomatedRollback: true,
  hasLiveTrafficShift: true,
  stages: [
    { id: 'cs-1', stepIndex: 1, stageName: 'Canary Warmup (5%)', trafficPercent: 5, durationMinutes: 15, isActive: false, isCompleted: true, isVerified: true },
    { id: 'cs-2', stepIndex: 2, stageName: 'Early Traffic Ramp (25%)', trafficPercent: 25, durationMinutes: 30, isActive: true, isCompleted: false, isVerified: true },
    { id: 'cs-3', stepIndex: 3, stageName: 'Majority Soak (50%)', trafficPercent: 50, durationMinutes: 60, isActive: false, isCompleted: false, isVerified: false },
    { id: 'cs-4', stepIndex: 4, stageName: 'Full Promotion (100%)', trafficPercent: 100, durationMinutes: 120, isActive: false, isCompleted: false, isVerified: false },
  ],
  metricGates: [
    { id: 'mg-1', metricName: 'HTTP 5xx Error Rate', threshold: '< 0.05%', currentValue: '0.012%', sloStatus: 'passing', isCriticalGate: true, hasPassed: true },
    { id: 'mg-2', metricName: 'P99 Latency SLA', threshold: '< 85 ms', currentValue: '62 ms', sloStatus: 'passing', isCriticalGate: true, hasPassed: true },
    { id: 'mg-3', metricName: 'Memory Leak Delta', threshold: '< 2.0% / hr', currentValue: '0.3% / hr', sloStatus: 'passing', isCriticalGate: false, hasPassed: true },
    { id: 'mg-4', metricName: 'User Apdex Score', threshold: '> 0.99', currentValue: '0.998', sloStatus: 'passing', isCriticalGate: true, hasPassed: true },
  ],
  rollbackTriggers: [
    { id: 'rb-1', triggerCondition: '5xx Rate > 0.10% over 2 min', action: 'Immediate Traffic Drain to 0%', isArmed: true },
    { id: 'rb-2', triggerCondition: 'P99 Latency > 150 ms spike', action: 'Halt Promotion & Freeze Traffic', isArmed: true },
    { id: 'rb-3', triggerCondition: 'OOM Killed Pod > 0', action: 'Trigger GitOps Rollback PR', isArmed: true },
  ],
});

export const createDataMeshFederatedSlide = (id = `slide-${Date.now()}`): DataMeshFederatedSlideData => ({
  id,
  type: 'data-mesh-federated-governance',
  title: 'Data Mesh Federated Governance: Sovereign Domains & ODCS Contracts',
  subtitle: 'Decentralized data product architecture governed by global Open Data Contract Specifications (ODCS) and automated lineage attestations.',
  kicker: 'DATA ARCHITECTURE PLATFORM',
  enterpriseScope: 'Global Multi-Region Lakehouse Mesh',
  totalDomainsCount: 4,
  activeContractsCount: 32,
  governanceStandard: 'ODCS v2.2.0 Cryptographic Attestation',
  hasFederatedAccessControl: true,
  hasAutomatedCatalogSync: true,
  domains: [
    { id: 'dom-1', domainName: 'Customer 360 & Identity', domainLead: 'Alim Ul Karim, Chief Software Engineer', dataProductCount: 8, slasMetPercent: 99.8, governanceTier: 'sovereign', isActive: true, hasAuditCompliance: true },
    { id: 'dom-2', domainName: 'Financial Ledger & Clearing', domainLead: 'FinOps Data Lead', dataProductCount: 12, slasMetPercent: 99.9, governanceTier: 'regulated', isActive: true, hasAuditCompliance: true },
    { id: 'dom-3', domainName: 'Logistics & Supply Chain', domainLead: 'Operations Analytics Team', dataProductCount: 6, slasMetPercent: 98.9, governanceTier: 'federated', isActive: true, hasAuditCompliance: true },
    { id: 'dom-4', domainName: 'Product Telemetry Mesh', domainLead: 'Growth Data Team', dataProductCount: 6, slasMetPercent: 99.4, governanceTier: 'sovereign', isActive: true, hasAuditCompliance: true },
  ],
  contracts: [
    { id: 'dc-1', contractName: 'customer_profile_v3', consumerDomain: 'Financial Ledger', schemaVersion: '3.1.0', isVerified: true, hasBreakingChangeProtection: true },
    { id: 'dc-2', contractName: 'clearing_settlement_v2', consumerDomain: 'Customer 360', schemaVersion: '2.0.4', isVerified: true, hasBreakingChangeProtection: true },
    { id: 'dc-3', contractName: 'route_telemetry_v1', consumerDomain: 'Product Telemetry', schemaVersion: '1.4.2', isVerified: true, hasBreakingChangeProtection: true },
  ],
  policies: [
    { id: 'pol-1', policyTitle: 'Zero Uncontracted Schema Mutations', enforcementMode: 'automated-ci', isEnforced: true },
    { id: 'pol-2', policyTitle: 'Column-Level PII Differential Encryption', enforcementMode: 'runtime-guard', isEnforced: true },
    { id: 'pol-3', policyTitle: 'Cross-Domain Lineage Cryptographic Signature', enforcementMode: 'cryptographic-audit', isEnforced: true },
  ],
});

export const createThreatExposureCtemSlide = (id = `slide-${Date.now()}`): ThreatExposureCtemSlideData => ({
  id,
  type: 'threat-exposure-ctem-matrix',
  title: 'Continuous Threat Exposure Management (CTEM) & Exploit Velocity',
  subtitle: 'Continuous five-phase attack surface validation prioritizing actionable exploitability (EPSS) over raw vulnerability volumetric counts.',
  kicker: 'CYBERSECURITY OPERATIONS',
  targetEnterprisePerimeter: 'Hybrid Multi-Cloud & Edge VPC Perimeter',
  compositeRiskScore: 24,
  totalValidatedExposures: 14,
  reductionTrendPercent: '-78% MTTR Reduction',
  hasRealtimeTelemetry: true,
  hasAutomatedRemediationTicket: true,
  phases: [
    { id: 'cp-1', phaseName: 'scoping', stepIndex: 1, progressPercent: 100, isActive: false, isCompleted: true },
    { id: 'cp-2', phaseName: 'discovery', stepIndex: 2, progressPercent: 100, isActive: false, isCompleted: true },
    { id: 'cp-3', phaseName: 'prioritization', stepIndex: 3, progressPercent: 85, isActive: true, isCompleted: false },
    { id: 'cp-4', phaseName: 'validation', stepIndex: 4, progressPercent: 40, isActive: false, isCompleted: false },
    { id: 'cp-5', phaseName: 'mobilization', stepIndex: 5, progressPercent: 10, isActive: false, isCompleted: false },
  ],
  vectors: [
    { id: 'v-1', assetCategory: 'API Gateway', vectorName: 'CVE-2024-38077 Windows RPC', cveIdentifier: 'CVE-2024-38077', exploitabilityScore: 0.94, blastRadius: 'critical', isRemediated: true, isUnderActiveAttack: false, hasGlow: false },
    { id: 'v-2', assetCategory: 'SSH Bastion', vectorName: 'regreSSHion OpenSSH Race', cveIdentifier: 'CVE-2024-6387', exploitabilityScore: 0.88, blastRadius: 'high', isRemediated: true, isUnderActiveAttack: false, hasGlow: false },
    { id: 'v-3', assetCategory: 'Cloud IAM', vectorName: 'Excessive Wildcard AssumeRole', cveIdentifier: 'IAM-LEAST-PRIV', exploitabilityScore: 0.76, blastRadius: 'medium', isRemediated: true, isUnderActiveAttack: false, hasGlow: false },
    { id: 'v-4', assetCategory: 'External Edge', vectorName: 'Exposed Staging JWT Endpoint', cveIdentifier: 'API-LEAK-SEC', exploitabilityScore: 0.96, blastRadius: 'critical', isRemediated: false, isUnderActiveAttack: true, hasGlow: true },
  ],
  pillarMetrics: [
    { id: 'pm-1', pillarName: 'Identity & Access', vulnCount: 0, mttrHours: 2.4, isCompliant: true },
    { id: 'pm-2', pillarName: 'Cloud Infrastructure', vulnCount: 2, mttrHours: 4.1, isCompliant: true },
    { id: 'pm-3', pillarName: 'Application Edge', vulnCount: 1, mttrHours: 1.8, isCompliant: true },
  ],
});

export const createSubseaCableGlobalBackboneSlide = (id = `slide-${Date.now()}`): SubseaCableGlobalBackboneSlideData => ({
  id,
  type: 'subsea-cable-global-backbone',
  title: 'Subsea Cable Global Optical Backbone: 340 Tbps Cross-Ocean Fabric',
  subtitle: 'Ultra-low latency trans-oceanic DWDM fiber network interconnecting sovereign cloud compute regions across Pacific and Atlantic corridors.',
  kicker: 'GLOBAL TELECOM INFRASTRUCTURE',
  globalNetworkName: 'Trans-Oceanic Sovereign Optical Express',
  totalSubseaCapacityTbps: 340,
  activeLandingStations: 28,
  averageCrossOceanLatency: '58.4 ms RTT',
  hasGeoRedundantRouting: true,
  hasRealtimeFiberMonitoring: true,
  cableRoutes: [
    { id: 'cr-1', cableSystemName: 'Pacific Sovereign Express (PSE)', landingPairs: ['Tokyo, JP', 'Los Angeles, US'], lengthKilometers: 9600, capacityTbps: 180, fiberPairs: 16, latencyRoundTripMs: 62.4, isOperational: true, hasProtectedRing: true },
    { id: 'cr-2', cableSystemName: 'Atlantic HyperScale Rail (AHR)', landingPairs: ['London, UK', 'New York, US'], lengthKilometers: 6400, capacityTbps: 160, fiberPairs: 16, latencyRoundTripMs: 48.2, isOperational: true, hasProtectedRing: true },
  ],
  landingStations: [
    { id: 'ls-1', cityName: 'Tokyo', countryCode: 'JP', interconnectCarriers: 18, latitude: 35.6762, longitude: 139.6503, isPrimaryGateway: true, isActive: true },
    { id: 'ls-2', cityName: 'Los Angeles', countryCode: 'US', interconnectCarriers: 24, latitude: 34.0522, longitude: -118.2437, isPrimaryGateway: true, isActive: true },
    { id: 'ls-3', cityName: 'London', countryCode: 'UK', interconnectCarriers: 32, latitude: 51.5074, longitude: -0.1278, isPrimaryGateway: true, isActive: true },
    { id: 'ls-4', cityName: 'Singapore', countryCode: 'SG', interconnectCarriers: 28, latitude: 1.3521, longitude: 103.8198, isPrimaryGateway: true, isActive: true },
  ],
  healthPillars: [
    { id: 'hp-1', label: 'Optical Availability', currentValue: '99.999%', availabilityPercent: 99.999, isOptimal: true },
    { id: 'hp-2', label: 'DWDM Wavelength Utilization', currentValue: '64.2%', availabilityPercent: 64.2, isOptimal: true },
    { id: 'hp-3', label: 'Protection Switching Time', currentValue: '< 24 ms', availabilityPercent: 100, isOptimal: true },
  ],
});

export const createMultiAgentReflectionSlide = (id = `slide-${Date.now()}`): MultiAgentReflectionSlideData => ({
  id,
  type: 'multi-agent-reflection-deliberation',
  title: 'Multi-Agent Reflection & Deliberation: Consensus Reasoning Trees',
  subtitle: 'Autonomous multi-persona deliberation loop where Planner, Executor, Critic, and Verifier agents iteratively converge toward mathematically proven consensus.',
  kicker: 'AUTONOMOUS REASONING ARCHITECTURE',
  orchestrationFramework: 'Sovereign Swarm Deliberation Engine',
  taskObjective: 'Zero-Defect Architectural Code Refactor with 100% Positive Booleans',
  totalDeliberationRounds: 4,
  consensusConvergenceScore: '99.8%',
  hasReflectionLoopActive: true,
  hasMonadicResultValidation: true,
  agents: [
    { id: 'ag-plan', agentRole: 'Lead Planner', agentSpecialization: 'Objective Decomposition & DAG Orchestration', modelEngine: 'Claude 3.5 Sonnet', confidenceScorePercent: 96, critiqueIterations: 1, isActive: true, isConsensusAgreed: true, hasGlow: false },
    { id: 'ag-exec', agentRole: 'Chief Executor', agentSpecialization: 'Surgical Code Synthesis & Line-Count Hygiene', modelEngine: 'DeepSeek-Coder-V2', confidenceScorePercent: 98, critiqueIterations: 2, isActive: true, isConsensusAgreed: true, hasGlow: false },
    { id: 'ag-crit', agentRole: 'Adversarial Critic', agentSpecialization: 'Edge Case Fuzzing & Static Boundary Defense', modelEngine: 'Claude 3.5 Sonnet', confidenceScorePercent: 99, critiqueIterations: 3, isActive: true, isConsensusAgreed: true, hasGlow: true },
    { id: 'ag-verf', agentRole: 'Formal Verifier', agentSpecialization: 'Monadic Result Proofs & AST Verification', modelEngine: 'Sovereign Verifier', confidenceScorePercent: 99.8, critiqueIterations: 4, isActive: true, isConsensusAgreed: true, hasGlow: true },
  ],
  exchanges: [
    { id: 'ex-1', sourceAgentId: 'ag-plan', targetAgentId: 'ag-exec', exchangeType: 'proposal', summaryContent: 'Generated 4-step decomposition with strict <= 100 line module caps.', roundNumber: 1, isVerified: true },
    { id: 'ex-2', sourceAgentId: 'ag-crit', targetAgentId: 'ag-exec', exchangeType: 'critique', summaryContent: 'Flagged 1 potential negative boolean in props; requested positive polarity.', roundNumber: 2, isVerified: true },
    { id: 'ex-3', sourceAgentId: 'ag-exec', targetAgentId: 'ag-verf', exchangeType: 'refinement', summaryContent: 'Refactored to 100% affirmative booleans (isActive, isVerified).', roundNumber: 3, isVerified: true },
    { id: 'ex-4', sourceAgentId: 'ag-verf', targetAgentId: 'ag-plan', exchangeType: 'consensus-signoff', summaryContent: 'Formal verification complete. Zero lint violations. Unanimous consensus.', roundNumber: 4, isVerified: true },
  ],
  verdicts: [
    { id: 'vd-1', verdictClause: 'Module Boundary Compliance (<= 100 Physical Lines)', majorityRatio: '4 / 4 Unanimous', isApproved: true },
    { id: 'vd-2', verdictClause: '100% Affirmative Positive Boolean Semantics', majorityRatio: '4 / 4 Unanimous', isApproved: true },
    { id: 'vd-3', verdictClause: 'Persona Governance: Chief Software Engineer Title Verified', majorityRatio: '4 / 4 Unanimous', isApproved: true },
  ],
});

export const createSemanticCacheHitSlide = (id = `slide-${Date.now()}`): SemanticCacheHitSlideData => ({
  id,
  type: 'semantic-cache-hit-topology',
  title: 'Semantic Cache Hit Topology: L1 Exact & L2 Cosine ANN Routing',
  subtitle: 'Hierarchical query cache architecture deflecting redundant foundation model inference calls via dual-tier exact hashing and vector cosine indexing.',
  kicker: 'AI EDGE ACCELERATION',
  vectorStoreEngine: 'Qdrant / Milvus In-Memory HNSW',
  embeddingModel: 'text-embedding-3-large (3072-dim)',
  globalCacheHitRatio: '86.4%',
  medianLookupLatencyMs: 4.2,
  hasAdaptiveThresholding: true,
  hasExactMatchBypass: true,
  clusters: [
    { id: 'cl-1', clusterLabel: 'Authentication & Session Queries', embeddingDimension: 3072, centroidDistance: 0.12, hitRatePercent: 94.2, sampleQueries: ['How do I reset my API key?', 'API token regeneration guide'], isActive: true, hasNearExactMatch: true },
    { id: 'cl-2', clusterLabel: 'Billing & Invoice Breakdown', embeddingDimension: 3072, centroidDistance: 0.18, hitRatePercent: 88.6, sampleQueries: ['Download tax invoice for March', 'Where is my enterprise receipt?'], isActive: true, hasNearExactMatch: true },
    { id: 'cl-3', clusterLabel: 'Infrastructure Deployment Logs', embeddingDimension: 3072, centroidDistance: 0.24, hitRatePercent: 78.4, sampleQueries: ['Deploy commit status check', 'Kubernetes pod crashloop log'], isActive: true, hasNearExactMatch: false },
  ],
  thresholds: [
    { id: 'th-1', cosineThreshold: 0.96, recallPrecisionRatio: '99.8% Precision', falsePositiveRatePercent: 0.02, isRecommendedThreshold: false },
    { id: 'th-2', cosineThreshold: 0.92, recallPrecisionRatio: '98.5% Precision', falsePositiveRatePercent: 0.45, isRecommendedThreshold: true },
    { id: 'th-3', cosineThreshold: 0.88, recallPrecisionRatio: '94.2% Precision', falsePositiveRatePercent: 2.10, isRecommendedThreshold: false },
  ],
  telemetryCards: [
    { id: 'tc-1', metricTitle: 'L1 Exact Match Hits', displayValue: '34.2%', bandwidthSavedFormatted: '$42,800 / mo Saved', isPositivePerformance: true },
    { id: 'tc-2', metricTitle: 'L2 Semantic Cosine Hits', displayValue: '52.2%', bandwidthSavedFormatted: '$65,400 / mo Saved', isPositivePerformance: true },
    { id: 'tc-3', metricTitle: 'Cache Miss Egress to LLM', displayValue: '13.6%', bandwidthSavedFormatted: '$17,050 Spent', isPositivePerformance: true },
  ],
});

export const createSaasNetRevenueRetentionSlide = (id = `slide-${Date.now()}`): SaasNetRevenueRetentionSlideData => ({
  id,
  type: 'saas-net-revenue-retention-cohort',
  title: 'SaaS Net Revenue Retention (NRR) Cohort: 146% Compounding Orbit',
  subtitle: 'Longitudinal quarterly cohort waterfall tracking gross revenue retention, seat expansions, usage upsells, and sub-2% logo churn mechanics.',
  kicker: 'ENTERPRISE SAAS METRICS',
  reportingPeriod: 'FY2024 - FY2025 (4 Consecutive Quarters)',
  blendedNrrPercent: 146,
  grossRetentionRatePercent: 98.2,
  expansionVelocityTrend: '+18.4% YoY Expansion ARR',
  hasCohortDecomposition: true,
  hasBenchmarkOutperformance: true,
  cohorts: [
    { id: 'coh-q1', cohortQuarter: 'Q1 FY24', startingArrFormatted: '$24.0M', expansionArrFormatted: '+$4.8M', churnArrFormatted: '-$0.3M', endingArrFormatted: '$28.5M', nrrPercent: 119, isExpansionPositive: true, isLeadingCohort: false },
    { id: 'coh-q2', cohortQuarter: 'Q2 FY24', startingArrFormatted: '$28.5M', expansionArrFormatted: '+$6.2M', churnArrFormatted: '-$0.4M', endingArrFormatted: '$34.3M', nrrPercent: 128, isExpansionPositive: true, isLeadingCohort: false },
    { id: 'coh-q3', cohortQuarter: 'Q3 FY24', startingArrFormatted: '$34.3M', expansionArrFormatted: '+$8.1M', churnArrFormatted: '-$0.5M', endingArrFormatted: '$41.9M', nrrPercent: 137, isExpansionPositive: true, isLeadingCohort: false },
    { id: 'coh-q4', cohortQuarter: 'Q4 FY24', startingArrFormatted: '$41.9M', expansionArrFormatted: '+$10.4M', churnArrFormatted: '-$0.6M', endingArrFormatted: '$51.7M', nrrPercent: 146, isExpansionPositive: true, isLeadingCohort: true },
  ],
  segments: [
    { id: 'seg-1', tierName: 'Strategic Enterprise (> $250K ARR)', accountCount: 48, averageArrFormatted: '$485K', nrrRate: 158, hasHighExpansionVelocity: true },
    { id: 'seg-2', tierName: 'Mid-Market Scale ($50K - $250K ARR)', accountCount: 142, averageArrFormatted: '$112K', nrrRate: 138, hasHighExpansionVelocity: true },
    { id: 'seg-3', tierName: 'Growth Velocity (< $50K ARR)', accountCount: 380, averageArrFormatted: '$28K', nrrRate: 124, hasHighExpansionVelocity: false },
  ],
  drivers: [
    { id: 'drv-1', driverCategory: 'Cross-Sell to AI Infrastructure', impactBps: 1480, isGrowthDriver: true },
    { id: 'drv-2', driverCategory: 'Enterprise Security Add-On Tier', impactBps: 1240, isGrowthDriver: true },
    { id: 'drv-3', driverCategory: 'Consumption-Based API Overages', impactBps: 880, isGrowthDriver: true },
  ],
});

export const createConfidentialMpcKeyVaultSlide = (id = `slide-${Date.now()}`): ConfidentialMpcKeyVaultSlideData => ({
  id,
  type: 'confidential-mpc-key-vault',
  title: 'Confidential Multi-Party Computation (MPC) Key Vault',
  subtitle: 'Threshold cryptographic key shard distribution across isolated hardware enclaves guaranteeing zero single-point key reconstruction.',
  kicker: 'CRYPTOGRAPHIC ASSET SECURITY',
  vaultSystemName: 'Sovereign MPC Threshold Enclave-01',
  thresholdScheme: '3-of-5 Shamir Secret Sharing with Curve25519',
  totalKeySharesCount: 5,
  attestationStatus: 'fully-attested',
  hasZeroKnowledgeProof: true,
  hasEnclaveIsolation: true,
  keyShards: [
    { id: 'ks-1', shardIndex: 1, nodeName: 'Zurich Vault Node 01', enclaveType: 'amd-sev-snp', jurisdiction: 'Switzerland (CH)', isAttested: true, isOnline: true, hasGlow: true },
    { id: 'ks-2', shardIndex: 2, nodeName: 'Frankfurt Vault Node 02', enclaveType: 'intel-sgx', jurisdiction: 'Germany (DE)', isAttested: true, isOnline: true, hasGlow: false },
    { id: 'ks-3', shardIndex: 3, nodeName: 'Singapore Vault Node 03', enclaveType: 'aws-nitro', jurisdiction: 'Singapore (SG)', isAttested: true, isOnline: true, hasGlow: false },
    { id: 'ks-4', shardIndex: 4, nodeName: 'Tokyo Vault Node 04', enclaveType: 'amd-sev-snp', jurisdiction: 'Japan (JP)', isAttested: true, isOnline: true, hasGlow: false },
    { id: 'ks-5', shardIndex: 5, nodeName: 'Reykjavik Vault Node 05', enclaveType: 'intel-sgx', jurisdiction: 'Iceland (IS)', isAttested: true, isOnline: true, hasGlow: true },
  ],
  quorumPolicy: {
    id: 'qp-1',
    thresholdM: 3,
    totalN: 5,
    ellipticCurve: 'Ed25519 / Schnorr Signature',
    isQuorumSatisfied: true,
    isSecurityStandardFips140_3: true,
  },
  auditLog: [
    { id: 'al-1', operationType: 'partial-sign', sessionHash: '0x8f2a...c41e', latencyMs: 18.4, isSuccess: true },
    { id: 'al-2', operationType: 'shard-refresh', sessionHash: '0x3d7b...e92a', latencyMs: 24.2, isSuccess: true },
    { id: 'al-3', operationType: 'partial-sign', sessionHash: '0x991c...18ab', latencyMs: 16.9, isSuccess: true },
  ],
});

export const createDeveloperFrictionDxSlide = (id = `slide-${Date.now()}`): DeveloperFrictionDxSlideData => ({
  id,
  type: 'developer-friction-dx-telemetry',
  title: 'Developer Friction & DX Telemetry: Inner-Loop Latency Optimization',
  subtitle: 'Engineering productivity analytics quantifying local build latency, remote CI bottlenecks, and DORA Elite cycle time recovery.',
  kicker: 'DEVELOPER EXPERIENCE & DORA',
  engineeringOrganization: 'Sovereign Systems Engineering Group (850 Engineers)',
  totalDeveloperCount: 850,
  compositeDxScore: 88,
  estimatedAnnualHoursRecoverable: '42,500 hrs / yr ($4.8M Recovered Value)',
  hasLocalCacheAcceleration: true,
  hasDeveloperSentimentTracking: true,
  frictionPoints: [
    { id: 'fp-1', workflowStage: 'Inner Loop HMR', painPointDescription: 'Webpack cold restart latency exceeding 45s per component edit', weeklyHoursLost: 4.8, frictionSeverity: 'high', isRemediated: true, hasActiveAutomation: true },
    { id: 'fp-2', workflowStage: 'Pre-Merge CI Check', painPointDescription: 'Monolithic test suite causing 28m PR gating queue delay', weeklyHoursLost: 6.2, frictionSeverity: 'critical', isRemediated: true, hasActiveAutomation: true },
    { id: 'fp-3', workflowStage: 'Dev Environment Boot', painPointDescription: 'Docker compose dependency conflict during branch switching', weeklyHoursLost: 3.4, frictionSeverity: 'medium', isRemediated: true, hasActiveAutomation: true },
    { id: 'fp-4', workflowStage: 'Review Cycle Wait', painPointDescription: 'Reviewer latency on multi-thousand line oversized diffs', weeklyHoursLost: 5.1, frictionSeverity: 'high', isRemediated: true, hasActiveAutomation: true },
  ],
  metrics: [
    { id: 'dxm-1', metricName: 'Local HMR Latency', currentP95Value: '48 ms', targetP95Value: '< 100 ms', isTargetMet: true, hasPositiveTrend: true },
    { id: 'dxm-2', metricName: 'PR CI Pipeline Duration', currentP95Value: '3.2 min', targetP95Value: '< 5.0 min', isTargetMet: true, hasPositiveTrend: true },
    { id: 'dxm-3', metricName: 'DORA Deployment Frequency', currentP95Value: '18 / day', targetP95Value: '> 10 / day', isTargetMet: true, hasPositiveTrend: true },
    { id: 'dxm-4', metricName: 'Change Failure Rate', currentP95Value: '0.04%', targetP95Value: '< 0.50%', isTargetMet: true, hasPositiveTrend: true },
  ],
  toolchains: [
    { id: 'tc-1', toolName: 'Vite 6 / Turbopack HMR', executionSeconds: 0.05, cacheHitPercent: 99.2, isBottleneck: false },
    { id: 'tc-2', toolName: 'Bazel / Turborepo Remote Cache', executionSeconds: 1.8, cacheHitPercent: 88.5, isBottleneck: false },
    { id: 'tc-3', toolName: 'Sharded Parallel Test Matrix', executionSeconds: 192.0, cacheHitPercent: 74.0, isBottleneck: false },
  ],
});

export const createBoardroomMaSynergySlide = (id = `slide-${Date.now()}`): BoardroomMaSynergySlideData => ({
  id,
  type: 'boardroom-m-and-a-synergy-realization',
  title: 'Boardroom M&A Synergy Realization: Day-100 Integration Milestones',
  subtitle: 'Executive governance tracking run-rate EBITDA synergies, technology unification workstreams, and regulatory signoffs across cross-border mergers.',
  kicker: 'EXECUTIVE STRATEGY & GOVERNANCE',
  transactionCodename: 'Project Apex Meridian (Sovereign Cloud Merger)',
  targetClosingDate: 'Q4 FY2025',
  totalSynergyTargetUsd: '$48.5M Annualized EBITDA',
  currentRunRateSynergyUsd: '$36.2M Realized (74.6%)',
  integrationDayCount: 75,
  hasBoardApproval: true,
  hasQuarterlyAuditSignoff: true,
  pillars: [
    { id: 'sp-1', pillarName: 'Data Center Consolidation', synergyType: 'cost', targetValueUsd: '$18.0M', realizedValueUsd: '$14.2M', realizationPercent: 78.8, isOnTrack: true, hasExecutiveSponsorship: true },
    { id: 'sp-2', pillarName: 'Platform License Unification', synergyType: 'technology', targetValueUsd: '$12.5M', realizedValueUsd: '$10.8M', realizationPercent: 86.4, isOnTrack: true, hasExecutiveSponsorship: true },
    { id: 'sp-3', pillarName: 'Cross-Sell Joint Go-To-Market', synergyType: 'revenue', targetValueUsd: '$18.0M', realizedValueUsd: '$11.2M', realizationPercent: 62.2, isOnTrack: true, hasExecutiveSponsorship: true },
  ],
  milestones: [
    { id: 'im-1', milestoneTitle: 'Unified Identity & Single Sign-On Cutover', dayTarget: 30, workstreamOwner: 'SecOps Team', isCompleted: true, isActive: false, hasRegulatoryApproval: true },
    { id: 'im-2', milestoneTitle: 'Consolidated Billing & Chart of Accounts', dayTarget: 60, workstreamOwner: 'Finance Team', isCompleted: true, isActive: false, hasRegulatoryApproval: true },
    { id: 'im-3', milestoneTitle: 'Data Plane Migration to Sovereign Enclave', dayTarget: 90, workstreamOwner: 'Alim Ul Karim, Chief Software Engineer', isCompleted: false, isActive: true, hasRegulatoryApproval: true },
    { id: 'im-4', milestoneTitle: 'Full Commercial Harmonization & Brand Launch', dayTarget: 100, workstreamOwner: 'GTM Operations', isCompleted: false, isActive: false, hasRegulatoryApproval: true },
  ],
  risks: [
    { id: 'er-1', riskFactor: 'Cross-Border Telecom Regulatory Clearance', mitigationPlan: 'Engaged local counsel in Singapore and Frankfurt', severity: 'manageable', isMitigated: true },
    { id: 'er-2', riskFactor: 'Key Engineering Talent Retention Post-Merger', mitigationPlan: 'Executed 3-year sovereign equity retention pools', severity: 'manageable', isMitigated: true },
  ],
});

export const KINETIC_REVOLUTION_FACTORIES: Record<string, (id?: string) => KineticRevolutionSlideData> = {
  'gpu-cluster-fabric-interconnect': createGpuClusterFabricSlide,
  'rag-needle-haystack-benchmark': createRagNeedleHaystackSlide,
  'ebpf-kernel-telemetry-observability': createEbpfKernelTelemetrySlide,
  'ai-inference-token-economics': createAiInferenceTokenEconomicsSlide,
  'micro-frontend-federation-matrix': createMicroFrontendFederationSlide,
  'progressive-delivery-canary-gate': createProgressiveDeliveryCanarySlide,
  'data-mesh-federated-governance': createDataMeshFederatedSlide,
  'threat-exposure-ctem-matrix': createThreatExposureCtemSlide,
  'subsea-cable-global-backbone': createSubseaCableGlobalBackboneSlide,
  'multi-agent-reflection-deliberation': createMultiAgentReflectionSlide,
  'semantic-cache-hit-topology': createSemanticCacheHitSlide,
  'saas-net-revenue-retention-cohort': createSaasNetRevenueRetentionSlide,
  'confidential-mpc-key-vault': createConfidentialMpcKeyVaultSlide,
  'developer-friction-dx-telemetry': createDeveloperFrictionDxSlide,
  'boardroom-m-and-a-synergy-realization': createBoardroomMaSynergySlide,
};

export const KINETIC_REVOLUTION_ARCHETYPE_OPTIONS: (ArchetypeOption & { description: string })[] = [
  { type: 'gpu-cluster-fabric-interconnect', label: 'GPU Cluster Fabric Interconnect', category: 'AI Infrastructure', desc: '8x H100 nodes, NVSwitch spine crossbar, and 3.2 Tbps RoCEv2 rails', description: '8x H100 nodes, NVSwitch spine crossbar, and 3.2 Tbps RoCEv2 rails', icon: 'Cpu' },
  { type: 'rag-needle-haystack-benchmark', label: 'RAG Needle in Haystack Benchmark', category: 'AI Infrastructure', desc: '8K-2M token context window retrieval depth and accuracy heatmap', description: '8K-2M token context window retrieval depth and accuracy heatmap', icon: 'Search' },
  { type: 'ebpf-kernel-telemetry-observability', label: 'eBPF Kernel Telemetry & Observability', category: 'Systems & Cloud', desc: 'Linux kernel tracepoints, ring buffers, and sub-15ns syscall telemetry', description: 'Linux kernel tracepoints, ring buffers, and sub-15ns syscall telemetry', icon: 'Activity' },
  { type: 'ai-inference-token-economics', label: 'AI Inference Token Economics', category: 'AI Infrastructure', desc: 'TTFT, ITL, paged KV cache VRAM footprint, and gross margin optimization', description: 'TTFT, ITL, paged KV cache VRAM footprint, and gross margin optimization', icon: 'Coins' },
  { type: 'micro-frontend-federation-matrix', label: 'Micro-Frontend Federation Matrix', category: 'Product & Architecture', desc: 'Module Federation v2 remotes, shared singleton dependencies, and event bus', description: 'Module Federation v2 remotes, shared singleton dependencies, and event bus', icon: 'LayoutGrid' },
  { type: 'progressive-delivery-canary-gate', label: 'Progressive Delivery Canary Gate', category: 'Systems & Cloud', desc: 'Automated 5% to 100% traffic shifting with Prometheus error budget SLOs', description: 'Automated 5% to 100% traffic shifting with Prometheus error budget SLOs', icon: 'GitMerge' },
  { type: 'data-mesh-federated-governance', label: 'Data Mesh Federated Governance', category: 'Product & Architecture', desc: 'Domain data products, ODCS data contracts, and cryptographic compliance', description: 'Domain data products, ODCS data contracts, and cryptographic compliance', icon: 'Database' },
  { type: 'threat-exposure-ctem-matrix', label: 'Continuous Threat Exposure (CTEM)', category: 'Strategy & Metrics', desc: 'Gartner 5-stage CTEM cycle, EPSS exploit telemetry, and remediation speed', description: 'Gartner 5-stage CTEM cycle, EPSS exploit telemetry, and remediation speed', icon: 'ShieldAlert' },
  { type: 'subsea-cable-global-backbone', label: 'Subsea Cable Global Backbone', category: 'Product & Architecture', desc: 'Trans-oceanic DWDM fiber network, landing stations, and latency telemetry', description: 'Trans-oceanic DWDM fiber network, landing stations, and latency telemetry', icon: 'Globe' },
  { type: 'multi-agent-reflection-deliberation', label: 'Multi-Agent Reflection & Deliberation', category: 'AI Infrastructure', desc: 'Planner, Executor, Critic, and Verifier consensus convergence trees', description: 'Planner, Executor, Critic, and Verifier consensus convergence trees', icon: 'Users' },
  { type: 'semantic-cache-hit-topology', label: 'Semantic Cache Hit Topology', category: 'AI Infrastructure', desc: 'Exact match L1 and vector cosine L2 embedding cache hit rates', description: 'Exact match L1 and vector cosine L2 embedding cache hit rates', icon: 'Layers' },
  { type: 'saas-net-revenue-retention-cohort', label: 'SaaS Net Revenue Retention Cohort', category: 'Strategy & Metrics', desc: '100% ARR baseline compounding to 146% NRR across quarterly cohorts', description: '100% ARR baseline compounding to 146% NRR across quarterly cohorts', icon: 'TrendingUp' },
  { type: 'confidential-mpc-key-vault', label: 'Confidential MPC Key Vault', category: 'Product & Architecture', desc: '3-of-5 threshold multi-party computation inside hardware-attested enclaves', description: '3-of-5 threshold multi-party computation inside hardware-attested enclaves', icon: 'Lock' },
  { type: 'developer-friction-dx-telemetry', label: 'Developer Friction & DX Telemetry', category: 'Product & Architecture', desc: 'Inner and outer SDLC telemetry, build cache hits, and friction remediation', description: 'Inner and outer SDLC telemetry, build cache hits, and friction remediation', icon: 'Terminal' },
  { type: 'boardroom-m-and-a-synergy-realization', label: 'Boardroom M&A Synergy Realization', category: 'Strategy & Metrics', desc: 'Post-merger integration milestones and EBITDA synergy capture scorecard', description: 'Post-merger integration milestones and EBITDA synergy capture scorecard', icon: 'Briefcase' },
];
