// lint-allow: file-size reason="Suite 2027 enterprise slide mock data factories" max=1600
import type { SlideData } from '../types/presentation';
import type { ArchetypeOption } from './extendedSlideFactories';
import type {
  AiInferenceCostTokenWaterfallSlideData,
  CrossFunctionalRaciMatrixSlideData,
  ZeroTrustMicrosegmentationMapSlideData,
  SaasMagicNumberEfficiencyGaugeSlideData,
  SupplyChainGeopoliticalChokepointSlideData,
  IncidentSev1CommandTimelineSlideData,
  CloudFinopsUnitRateOptimizationSlideData,
  ProductMarketFitCohortTrianglesSlideData,
  EnterpriseAiGovernanceGuardrailsSlideData,
  DataLakehouseMedallionPipelineSlideData,
  MergerAcquisitionSynergyBridgeSlideData,
  DeveloperProductivitySpaceFrameworkSlideData,
  HybridCloudDrFailoverTopologySlideData,
  CustomerHealthScorecardMatrixSlideData,
  ValueStreamBottleneckFlowSlideData,
  Suite2027SlideData,
  Suite2027SlideType,
} from '../types/suite2027Archetypes';

// =============================================================================
// 1. AI Inference Cost Token Waterfall Factory
// =============================================================================
export const createAiInferenceCostTokenWaterfallSlide = (id = `slide-${Date.now()}`): AiInferenceCostTokenWaterfallSlideData => ({
  id,
  type: 'ai-inference-cost-token-waterfall',
  title: 'LLM Inference Unit Cost & Token Waterfall',
  subtitle: 'Decomposing prompt ingestion, KV-cache footprint, generation decoding, and margin retention',
  kicker: 'AI SYSTEMS ECONOMICS',
  modelIdentifier: 'Gemini Ultra Flash 2.5',
  blendedCostPerMillionTokensUsd: 1.85,
  timeToFirstTokenMs: 142,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  activeStep: 0,
  maxSteps: 4,
  isPublished: true,
  hasPresenterNotes: true,
  hasSpeculativeDecoding: true,
  hasQuantizationOptimized: true,
  hasCacheHitRate: true,
  hasTelemetryGlow: true,
  waterfallStages: [
    {
      stepIndex: 0,
      stageName: 'Prompt Ingestion & Context Loading',
      stageSubtitle: 'Vector embedding retrieval and attention matrix prefill',
      tokenThroughputTps: 420,
      cumulativeCostUsd: 0.35,
      isActive: true,
      isCompleted: false,
    },
    {
      stepIndex: 1,
      stageName: 'KV-Cache Memory Footprint',
      stageSubtitle: 'PagedAttention allocation across high-bandwidth GPU memory',
      tokenThroughputTps: 280,
      cumulativeCostUsd: 0.85,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 2,
      stageName: 'Speculative Output Generation',
      stageSubtitle: 'Draft model verification loop with 2.4x latency speedup',
      tokenThroughputTps: 148,
      cumulativeCostUsd: 1.5,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 3,
      stageName: 'Retained Infrastructure Gross Margin',
      stageSubtitle: 'Target unit economics yielding 62% operating margin',
      tokenThroughputTps: 148,
      cumulativeCostUsd: 1.85,
      isActive: false,
      isCompleted: false,
    },
  ],
  costNodes: [
    {
      id: 'node-prompt',
      category: 'Input Prompt Context',
      costPerThousandTokensUsd: 0.00035,
      percentageOfTotalCost: 18.9,
      isOptimized: true,
      hasHardwareAccelerationActive: true,
    },
    {
      id: 'node-kvcache',
      category: 'KV Cache Maintenance',
      costPerThousandTokensUsd: 0.0005,
      percentageOfTotalCost: 27.0,
      isOptimized: true,
      hasHardwareAccelerationActive: true,
    },
    {
      id: 'node-generation',
      category: 'Output Token Decoding',
      costPerThousandTokensUsd: 0.00065,
      percentageOfTotalCost: 35.1,
      isOptimized: true,
      hasHardwareAccelerationActive: true,
    },
    {
      id: 'node-margin',
      category: 'Operating Retained Margin',
      costPerThousandTokensUsd: 0.00035,
      percentageOfTotalCost: 19.0,
      isOptimized: true,
      hasHardwareAccelerationActive: false,
    },
  ],
});

// =============================================================================
// 2. Zero-Trust Microsegmentation Map Factory
// =============================================================================
export const createZeroTrustMicrosegmentationMapSlide = (id = `slide-${Date.now()}`): ZeroTrustMicrosegmentationMapSlideData => ({
  id,
  type: 'zero-trust-microsegmentation-map',
  title: 'Zero-Trust Workload Microsegmentation Map',
  subtitle: 'Real-time eBPF packet inspection, SPIFFE/SPIRE attestation, and sub-millisecond automated quarantine',
  kicker: 'CLOUD SECURITY ARCHITECTURE',
  clusterIdentifier: 'us-east-mesh-k8s-01',
  packetRejectionRatePpm: 12,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  activeStep: 0,
  maxSteps: 4,
  isPublished: true,
  hasPresenterNotes: true,
  isZeroTrustEnforced: true,
  hasEbpfActive: true,
  hasMutualTls: true,
  isQuarantineEngaged: false,
  hasTelemetryGlow: true,
  segmentationStages: [
    {
      stepIndex: 0,
      stageName: 'SVID Identity Attestation',
      stageSubtitle: 'Cryptographic SPIFFE SVID minting and workload attestation',
      enforcedRuleCount: 340,
      packetsInspectedRatePerSec: 450000,
      isActive: true,
      isCompleted: false,
    },
    {
      stepIndex: 1,
      stageName: 'eBPF Packet Filtering',
      stageSubtitle: 'Kernel-level bypass filtering eliminating sidecar latency overhead',
      enforcedRuleCount: 780,
      packetsInspectedRatePerSec: 1200000,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 2,
      stageName: 'East-West Zone Isolation',
      stageSubtitle: 'Deterministic boundary containment preventing lateral movement',
      enforcedRuleCount: 1140,
      packetsInspectedRatePerSec: 1200000,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 3,
      stageName: 'Automated Anomaly Quarantine',
      stageSubtitle: 'Sub-millisecond network boundary severance upon anomalous telemetry',
      enforcedRuleCount: 1480,
      packetsInspectedRatePerSec: 1200000,
      isActive: false,
      isCompleted: false,
    },
  ],
  workloadNodes: [
    {
      id: 'workload-ingress',
      workloadName: 'Envoy Ingress Gateway',
      namespace: 'ingress-system',
      securityZone: 'Border Ingress',
      svidIdentity: 'spiffe://prod.corp/ns/ingress/sa/envoy',
      isQuarantined: false,
      hasEbpfFilterActive: true,
    },
    {
      id: 'workload-checkout',
      workloadName: 'Checkout Core Service',
      namespace: 'commerce',
      securityZone: 'PCI-Cardholder',
      svidIdentity: 'spiffe://prod.corp/ns/commerce/sa/checkout',
      isQuarantined: false,
      hasEbpfFilterActive: true,
    },
    {
      id: 'workload-spanner',
      workloadName: 'Distributed Spanner Proxy',
      namespace: 'persistence',
      securityZone: 'Tier-0 Persistence',
      svidIdentity: 'spiffe://prod.corp/ns/persistence/sa/spanner',
      isQuarantined: false,
      hasEbpfFilterActive: true,
    },
    {
      id: 'workload-quarantined',
      workloadName: 'Anomalous Worker Pod',
      namespace: 'batch-jobs',
      securityZone: 'Sandbox-Untrusted',
      svidIdentity: 'spiffe://prod.corp/ns/batch/sa/worker-94',
      isQuarantined: true,
      hasEbpfFilterActive: true,
    },
  ],
});

// =============================================================================
// 3. Incident SEV-1 Command Timeline Factory
// =============================================================================
export const createIncidentSev1CommandTimelineSlide = (id = `slide-${Date.now()}`): IncidentSev1CommandTimelineSlideData => ({
  id,
  type: 'incident-sev1-command-timeline',
  title: 'SEV-1 Incident Command & Mitigation Timeline',
  subtitle: 'Chronological command sequence resolving high-severity distributed consensus stall',
  kicker: 'SRE & CRISIS MANAGEMENT',
  incidentIdentifier: 'INC-84920-SEV1',
  incidentCommander: 'Alim Ul Karim',
  commanderRole: 'Chief Software Engineer',
  meanTimeToRecoveryMinutes: 38,
  slaTargetMinutes: 60,
  activeStep: 0,
  maxSteps: 4,
  isPublished: true,
  hasPresenterNotes: true,
  isIncidentResolved: true,
  hasWarRoomActive: true,
  hasCanaryIsolated: true,
  hasMetSlaObjective: true,
  hasTelemetryGlow: true,
  timelineStages: [
    {
      stepIndex: 0,
      stageName: 'Telemetry Alert & Automated Paging',
      stageSubtitle: 'Prometheus synthetic probe triggers PagerDuty high-priority escalation',
      timestampOffset: 'T+00m',
      blastRadiusPercentage: 14.2,
      isActive: true,
      isCompleted: false,
    },
    {
      stepIndex: 1,
      stageName: 'Blast Radius Triage & Quorum Isolation',
      stageSubtitle: 'Raft leader re-election initiated to isolate partitioned consensus node',
      timestampOffset: 'T+08m',
      blastRadiusPercentage: 14.2,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 2,
      stageName: 'Canary Rollback & Hotfix Injection',
      stageSubtitle: 'Automated AST hotfix deployment across degraded regional pods',
      timestampOffset: 'T+22m',
      blastRadiusPercentage: 3.8,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 3,
      stageName: 'Post-Incident Service Normalization',
      stageSubtitle: 'Quorum validated across 24 regions with latency normalized to 18ms',
      timestampOffset: 'T+38m',
      blastRadiusPercentage: 0.0,
      isActive: false,
      isCompleted: false,
    },
  ],
  actionNodes: [
    {
      id: 'action-page',
      timeOffsetMinutes: 0,
      actionTitle: 'Automated PagerDuty Escalation',
      actionOwner: 'SRE On-Call Engine',
      executionStatus: 'COMPLETED',
      isAutomated: true,
      hasVerificationCheckPassed: true,
    },
    {
      id: 'action-quarantine',
      timeOffsetMinutes: 8,
      actionTitle: 'Degraded Consensus Node Quarantine',
      actionOwner: 'Alim Ul Karim',
      executionStatus: 'COMPLETED',
      isAutomated: false,
      hasVerificationCheckPassed: true,
    },
    {
      id: 'action-canary',
      timeOffsetMinutes: 22,
      actionTitle: 'Canary AST Hotfix Rollout',
      actionOwner: 'CI/CD Orchestrator',
      executionStatus: 'COMPLETED',
      isAutomated: true,
      hasVerificationCheckPassed: true,
    },
    {
      id: 'action-verification',
      timeOffsetMinutes: 38,
      actionTitle: 'Quorum Attestation Signoff',
      actionOwner: 'Alim Ul Karim',
      executionStatus: 'COMPLETED',
      isAutomated: false,
      hasVerificationCheckPassed: true,
    },
  ],
});

// =============================================================================
// 4. Cloud FinOps Unit Rate Optimization Factory
// =============================================================================
export const createCloudFinopsUnitRateOptimizationSlide = (id = `slide-${Date.now()}`): CloudFinopsUnitRateOptimizationSlideData => ({
  id,
  type: 'cloud-finops-unit-rate-optimization',
  title: 'Cloud FinOps Unit Rate & Arbitrage Optimization',
  subtitle: 'Algorithmic resource reclamation, spot instance arbitrage, and per-tenant unit economics',
  kicker: 'FINANCIAL ENGINEERING',
  organizationName: 'Global Enterprise Cloud',
  annualizedSavingsTargetUsd: 3800000,
  unitCostEfficiencyIndex: 94.2,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  activeStep: 0,
  maxSteps: 4,
  isPublished: true,
  hasPresenterNotes: true,
  hasAutoArbitrageEnabled: true,
  isTaggedFully: true,
  hasContinuousAudit: true,
  hasTelemetryGlow: true,
  optimizationStages: [
    {
      stepIndex: 0,
      stageName: 'Telemetry Ingestion & Cost Attribution',
      stageSubtitle: '100% fine-grained resource tagging across AWS, GCP, and Azure estates',
      totalSpendMonitoredUsd: 955000,
      savingsRunRateUsd: 0,
      isActive: true,
      isCompleted: false,
    },
    {
      stepIndex: 1,
      stageName: 'AI-Driven Anomaly Detection',
      stageSubtitle: 'Isolation of non-production idle capacity and zombie volume attachments',
      totalSpendMonitoredUsd: 955000,
      savingsRunRateUsd: 450000,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 2,
      stageName: 'Spot & Savings Plan Arbitrage',
      stageSubtitle: 'Automated spot drain mitigation with automated Savings Plans coverage',
      totalSpendMonitoredUsd: 955000,
      savingsRunRateUsd: 2100000,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 3,
      stageName: 'Closed-Loop Realized Savings',
      stageSubtitle: 'Continuous automated enforcement reaching $3.8M annualized savings',
      totalSpendMonitoredUsd: 955000,
      savingsRunRateUsd: 3800000,
      isActive: false,
      isCompleted: false,
    },
  ],
  workloadNodes: [
    {
      id: 'workload-gpu',
      workloadName: 'GPU AI Inference Cluster',
      cloudProvider: 'GCP',
      monthlyCostUsd: 420000,
      unitCostPerUserUsd: 0.018,
      realizedSavingsUsd: 140000,
      isTaggedFully: true,
      hasArbitrageActive: true,
    },
    {
      id: 'workload-k8s',
      workloadName: 'Kubernetes App Worker Fleet',
      cloudProvider: 'AWS',
      monthlyCostUsd: 280000,
      unitCostPerUserUsd: 0.012,
      realizedSavingsUsd: 92000,
      isTaggedFully: true,
      hasArbitrageActive: true,
    },
    {
      id: 'workload-storage',
      workloadName: 'Multi-Region Object Storage',
      cloudProvider: 'AWS',
      monthlyCostUsd: 160000,
      unitCostPerUserUsd: 0.007,
      realizedSavingsUsd: 48000,
      isTaggedFully: true,
      hasArbitrageActive: true,
    },
    {
      id: 'workload-egress',
      workloadName: 'Inter-Region Network Egress',
      cloudProvider: 'Azure',
      monthlyCostUsd: 95000,
      unitCostPerUserUsd: 0.005,
      realizedSavingsUsd: 36000,
      isTaggedFully: true,
      hasArbitrageActive: true,
    },
  ],
});

// =============================================================================
// 5. Enterprise AI Governance Guardrails Factory
// =============================================================================
export const createEnterpriseAiGovernanceGuardrailsSlide = (id = `slide-${Date.now()}`): EnterpriseAiGovernanceGuardrailsSlideData => ({
  id,
  type: 'enterprise-ai-governance-guardrails',
  title: 'Enterprise AI Governance & Safety Guardrails',
  subtitle: '4-tier runtime compliance pipeline enforcing hallucination prevention, PII redaction, and cryptographic auditability',
  kicker: 'AI SAFETY ARCHITECTURE',
  governanceFramework: 'NIST AI RMF & EU AI Act',
  overallComplianceScore: 98.8,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  activeStep: 0,
  maxSteps: 4,
  isPublished: true,
  hasPresenterNotes: true,
  isEuAiActCompliant: true,
  hasPiiRedactionActive: true,
  hasAuditLedgerPreserved: true,
  isTamperEvident: true,
  hasTelemetryGlow: true,
  guardrailStages: [
    {
      stepIndex: 0,
      stageName: 'Input Prompt Sanitization & Jailbreak Shield',
      stageSubtitle: 'Semantic classifier detecting adversarial injections and unauthorized prompts',
      inspectionLatencyMs: 1.2,
      passRatePercentage: 98.4,
      isActive: true,
      isCompleted: false,
    },
    {
      stepIndex: 1,
      stageName: 'Hallucination & Factuality Verification Gate',
      stageSubtitle: 'Grounding verification against authorized enterprise knowledge store',
      inspectionLatencyMs: 4.8,
      passRatePercentage: 99.4,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 2,
      stageName: 'PII & Proprietary IP Redaction Filter',
      stageSubtitle: 'Cryptographic token masking ensuring zero leakage of customer data',
      inspectionLatencyMs: 2.1,
      passRatePercentage: 100.0,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 3,
      stageName: 'Cryptographic Audit Ledger Anchoring',
      stageSubtitle: 'Append-only Merkle tree compliance seal proving non-repudiation',
      inspectionLatencyMs: 0.8,
      passRatePercentage: 100.0,
      isActive: false,
      isCompleted: false,
    },
  ],
  metricNodes: [
    {
      id: 'node-prompt-shield',
      guardrailLayer: 'Input Ingestion Shield',
      blockedRequestsCount: 4820,
      latencyOverheadMs: 1.2,
      complianceStandard: 'NIST AI RMF 1.0',
      isCompliant: true,
      hasActiveEnforcement: true,
    },
    {
      id: 'node-factuality',
      guardrailLayer: 'Output Grounding Engine',
      blockedRequestsCount: 610,
      latencyOverheadMs: 4.8,
      complianceStandard: 'EU AI Act High Risk',
      isCompliant: true,
      hasActiveEnforcement: true,
    },
    {
      id: 'node-pii',
      guardrailLayer: 'Data Privacy Mask',
      blockedRequestsCount: 1840,
      latencyOverheadMs: 2.1,
      complianceStandard: 'HIPAA / SOC2 Type II',
      isCompliant: true,
      hasActiveEnforcement: true,
    },
    {
      id: 'node-ledger',
      guardrailLayer: 'Merkle Audit Trail',
      blockedRequestsCount: 0,
      latencyOverheadMs: 0.8,
      complianceStandard: 'ISO/IEC 42001',
      isCompliant: true,
      hasActiveEnforcement: true,
    },
  ],
});

// =============================================================================
// 6. Data Lakehouse Medallion Pipeline Factory
// =============================================================================
export const createDataLakehouseMedallionPipelineSlide = (id = `slide-${Date.now()}`): DataLakehouseMedallionPipelineSlideData => ({
  id,
  type: 'data-lakehouse-medallion-pipeline',
  title: 'Data Lakehouse Streaming Medallion Pipeline',
  subtitle: 'Continuous event ingestion, automated schema evolution, and low-latency feature serving on Apache Iceberg',
  kicker: 'BIG DATA ARCHITECTURE',
  lakehouseEngine: 'Apache Iceberg & Trino',
  totalDataFootprintPetabytes: 4.2,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  activeStep: 0,
  maxSteps: 4,
  isPublished: true,
  hasPresenterNotes: true,
  isStreamingActive: true,
  hasDataQualityPassed: true,
  hasSchemaEnforced: true,
  isIcebergOptimized: true,
  hasTelemetryGlow: true,
  pipelineStages: [
    {
      stepIndex: 0,
      stageName: 'Bronze Raw Event Streaming',
      stageSubtitle: 'Append-only high-throughput Kafka ingestion with zero data transformation',
      throughputEventsPerSec: 1800000,
      dataQualityScorePercent: 98.2,
      isActive: true,
      isCompleted: false,
    },
    {
      stepIndex: 1,
      stageName: 'Silver Deduplication & Quality Enrichment',
      stageSubtitle: 'SCD Type-2 conformance, entity resolution, and automated null quarantine',
      throughputEventsPerSec: 1400000,
      dataQualityScorePercent: 99.9,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 2,
      stageName: 'Gold Curated Feature Aggregation',
      stageSubtitle: 'Dimensional star schema rollups and real-time ML feature store indexing',
      throughputEventsPerSec: 850000,
      dataQualityScorePercent: 99.98,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 3,
      stageName: 'Interactive BI & Inference Serving',
      stageSubtitle: 'Sub-second Trino querying and real-time inference embedding lookups',
      throughputEventsPerSec: 850000,
      dataQualityScorePercent: 100.0,
      isActive: false,
      isCompleted: false,
    },
  ],
  layerNodes: [
    {
      id: 'layer-bronze',
      layerName: 'Bronze Raw Event Stream',
      tableCount: 184,
      storageVolumeTerabytes: 2800,
      freshnessLatencySeconds: 2.4,
      isSchemaEnforced: false,
      hasIcebergOptimized: true,
    },
    {
      id: 'layer-silver',
      layerName: 'Silver Enriched Dimensions',
      tableCount: 92,
      storageVolumeTerabytes: 1100,
      freshnessLatencySeconds: 8.0,
      isSchemaEnforced: true,
      hasIcebergOptimized: true,
    },
    {
      id: 'layer-gold',
      layerName: 'Gold Analytical Aggregations',
      tableCount: 46,
      storageVolumeTerabytes: 300,
      freshnessLatencySeconds: 14.5,
      isSchemaEnforced: true,
      hasIcebergOptimized: true,
    },
    {
      id: 'layer-delivery',
      layerName: 'Delivery Query Layer',
      tableCount: 18,
      storageVolumeTerabytes: 45,
      freshnessLatencySeconds: 0.8,
      isSchemaEnforced: true,
      hasIcebergOptimized: true,
    },
  ],
});

// =============================================================================
// 7. Merger & Acquisition Synergy Bridge Factory
// =============================================================================
export const createMergerAcquisitionSynergyBridgeSlide = (id = `slide-${Date.now()}`): MergerAcquisitionSynergyBridgeSlideData => ({
  id,
  type: 'merger-acquisition-synergy-bridge',
  title: 'M&A Value Accretion & Synergy Realization Bridge',
  subtitle: 'Post-acquisition waterfall modeling baseline EBITDA, cost rationalization, and cross-sell expansion',
  kicker: 'STRATEGIC M&A OVERSIGHT',
  dealCodename: 'Project Titan Integration',
  targetEnterpriseValueMillionsUsd: 90.0,
  integrationHorizonDays: 180,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  activeStep: 0,
  maxSteps: 4,
  isPublished: true,
  hasPresenterNotes: true,
  hasSynergyTargetMet: true,
  isIntegrationOnSchedule: true,
  hasExecutiveSignoffCompleted: true,
  hasTelemetryGlow: true,
  synergyStages: [
    {
      stepIndex: 0,
      stageName: 'Pre-Deal Baseline EBITDA & Asset Audit',
      stageSubtitle: 'Certified baseline cash flows prior to operational integration',
      cumulativeValueMillionsUsd: 45.0,
      realizationProgressPercentage: 100.0,
      isActive: true,
      isCompleted: false,
    },
    {
      stepIndex: 1,
      stageName: 'Cost Rationalization & Cloud Consolidation',
      stageSubtitle: 'Elimination of redundant SaaS tools and consolidated data center leases',
      cumulativeValueMillionsUsd: 65.0,
      realizationProgressPercentage: 92.5,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 2,
      stageName: 'Commercial Cross-Sell & Platform Expansion',
      stageSubtitle: 'Cross-selling core software capabilities into acquired enterprise accounts',
      cumulativeValueMillionsUsd: 82.5,
      realizationProgressPercentage: 88.0,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 3,
      stageName: 'Target Enterprise Value Realization',
      stageSubtitle: 'Final post-merger integration yielding $90M target valuation',
      cumulativeValueMillionsUsd: 90.0,
      realizationProgressPercentage: 104.0,
      isActive: false,
      isCompleted: false,
    },
  ],
  bridgeNodes: [
    {
      id: 'node-baseline',
      category: 'Pre-Deal Baseline Value',
      impactAmountMillionsUsd: 45.0,
      isPositiveContribution: true,
      hasRealizedAuditVerification: true,
    },
    {
      id: 'node-cost-synergies',
      category: 'G&A and Cloud Cost Consolidation',
      impactAmountMillionsUsd: 20.0,
      isPositiveContribution: true,
      hasRealizedAuditVerification: true,
    },
    {
      id: 'node-revenue-synergies',
      category: 'Product Cross-Sell Accretion',
      impactAmountMillionsUsd: 17.5,
      isPositiveContribution: true,
      hasRealizedAuditVerification: true,
    },
    {
      id: 'node-target-ev',
      category: 'Realized Target Valuation',
      impactAmountMillionsUsd: 90.0,
      isPositiveContribution: true,
      hasRealizedAuditVerification: true,
    },
  ],
});

// =============================================================================
// 8. Hybrid Cloud DR Failover Topology Factory
// =============================================================================
export const createHybridCloudDrFailoverTopologySlide = (id = `slide-${Date.now()}`): HybridCloudDrFailoverTopologySlideData => ({
  id,
  type: 'hybrid-cloud-dr-failover-topology',
  title: 'Hybrid Cloud Automated DR Failover Topology',
  subtitle: 'Zero-data-loss cross-cloud regional swing achieving sub-60-second recovery time objective',
  kicker: 'HIGH AVAILABILITY & SRE',
  systemName: 'Global Core Banking Mesh',
  targetRpoSeconds: 0,
  targetRtoSeconds: 60,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  activeStep: 0,
  maxSteps: 4,
  isPublished: true,
  hasPresenterNotes: true,
  isFailoverComplete: true,
  hasZeroDataLoss: true,
  isAnycastRerouted: true,
  hasReplicaPromoted: true,
  hasTelemetryGlow: true,
  failoverStages: [
    {
      stepIndex: 0,
      stageName: 'Primary Region Health Check Degradation',
      stageSubtitle: 'Synthetic edge probes detect 3 consecutive heartbeat timeouts in AWS us-east-1',
      recoveryPointObjectiveSeconds: 0,
      recoveryTimeObjectiveSeconds: 10,
      isActive: true,
      isCompleted: false,
    },
    {
      stepIndex: 1,
      stageName: 'Global Anycast DNS Ingress Swing',
      stageSubtitle: 'BGP anycast routes swing 100% ingress volume from primary to secondary edge',
      recoveryPointObjectiveSeconds: 0,
      recoveryTimeObjectiveSeconds: 24,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 2,
      stageName: 'Distributed DB Read-Replica Promotion',
      stageSubtitle: 'Synchronous replica in Azure central-us promoted to active write master',
      recoveryPointObjectiveSeconds: 0,
      recoveryTimeObjectiveSeconds: 38,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 3,
      stageName: 'Secondary Workload Normalization',
      stageSubtitle: 'Full production workload serving all requests with zero data loss verified',
      recoveryPointObjectiveSeconds: 0,
      recoveryTimeObjectiveSeconds: 48,
      isActive: false,
      isCompleted: false,
    },
  ],
  siteNodes: [
    {
      id: 'site-aws',
      siteName: 'Primary Region (AWS)',
      cloudRegion: 'AWS us-east-1',
      trafficLoadPercentage: 0,
      replicationLagSeconds: 0,
      isPrimaryActive: false,
      hasQuorumHealthy: false,
    },
    {
      id: 'site-azure',
      siteName: 'Secondary Failover (Azure)',
      cloudRegion: 'Azure central-us',
      trafficLoadPercentage: 100,
      replicationLagSeconds: 0,
      isPrimaryActive: true,
      hasQuorumHealthy: true,
    },
  ],
});

// =============================================================================
// 9. Value Stream Bottleneck Flow Factory
// =============================================================================
export const createValueStreamBottleneckFlowSlide = (id = `slide-${Date.now()}`): ValueStreamBottleneckFlowSlideData => ({
  id,
  type: 'value-stream-bottleneck-flow',
  title: 'Software Delivery Value Stream & Bottleneck Flow',
  subtitle: 'Identifying constraints, reducing non-value-add wait times, and elevating flow efficiency from 38% to 68%',
  kicker: 'DEVOPS VALUE STREAM MAPPING',
  engineeringOrgName: 'Core Engineering Platforms',
  totalLeadTimeDays: 4.8,
  totalCycleTimeHours: 6.2,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  activeStep: 0,
  maxSteps: 4,
  isPublished: true,
  hasPresenterNotes: true,
  hasContinuousDelivery: true,
  isBottleneckIdentified: true,
  hasCanaryVerified: true,
  hasOptimizedFlow: true,
  hasTelemetryGlow: true,
  streamStages: [
    {
      stepIndex: 0,
      stageName: 'Customer Feature Ingestion & Spec Scoping',
      stageSubtitle: 'Refined epics decomposed into hermetic architectural task units',
      cycleTimeHours: 1.7,
      efficiencyPercentage: 82.0,
      isActive: true,
      isCompleted: false,
    },
    {
      stepIndex: 1,
      stageName: 'Hermetic Build & Automated Unit Test Suite',
      stageSubtitle: 'Parallelized CI runner compilation with 100% build cache hit rate',
      cycleTimeHours: 1.2,
      efficiencyPercentage: 74.0,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 2,
      stageName: 'Comprehensive AST Security Scan Bottleneck',
      stageSubtitle: 'Deep static semantic analysis identifying critical path delay bottleneck',
      cycleTimeHours: 11.7,
      efficiencyPercentage: 30.0,
      isActive: false,
      isCompleted: false,
    },
    {
      stepIndex: 3,
      stageName: 'Automated Production Canary Deployment',
      stageSubtitle: 'Progressive traffic ramp with sub-second error rate rollback gates',
      cycleTimeHours: 1.6,
      efficiencyPercentage: 88.0,
      isActive: false,
      isCompleted: false,
    },
  ],
  streamNodes: [
    {
      id: 'vsm-backlog',
      stageName: 'Backlog Feature Ingestion',
      processTimeHours: 0.5,
      waitTimeHours: 1.2,
      flowEfficiencyPercentage: 29.4,
      isBottleneckStage: false,
      hasAutomationOptimized: true,
    },
    {
      id: 'vsm-build',
      stageName: 'Hermetic Build & Tests',
      processTimeHours: 0.8,
      waitTimeHours: 0.4,
      flowEfficiencyPercentage: 66.7,
      isBottleneckStage: false,
      hasAutomationOptimized: true,
    },
    {
      id: 'vsm-security',
      stageName: 'AST Static Security Scan',
      processTimeHours: 3.5,
      waitTimeHours: 8.2,
      flowEfficiencyPercentage: 29.9,
      isBottleneckStage: true,
      hasAutomationOptimized: false,
    },
    {
      id: 'vsm-canary',
      stageName: 'Automated Canary Deployment',
      processTimeHours: 1.4,
      waitTimeHours: 0.2,
      flowEfficiencyPercentage: 87.5,
      isBottleneckStage: false,
      hasAutomationOptimized: true,
    },
  ],
});

// =============================================================================
// 10. Cross-Functional RACI Matrix Factory
// =============================================================================
export const createCrossFunctionalRaciMatrixSlide = (id = `slide-${Date.now()}`): CrossFunctionalRaciMatrixSlideData => ({
  id,
  type: 'cross-functional-raci-matrix',
  title: 'Cross-Functional Initiative RACI Matrix',
  subtitle: 'Unambiguous executive accountability across engineering, product, compliance, and infrastructure workstreams',
  kicker: 'ORGANIZATIONAL GOVERNANCE',
  governanceCycle: 'FY2027 Strategic Roadmap',
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  activeStep: 0,
  maxSteps: 1,
  isPublished: true,
  hasPresenterNotes: true,
  isCompliantWithGovernance: true,
  hasAuditTrail: true,
  hasTelemetryGlow: true,
  matrixRows: [
    {
      id: 'raci-ai-infra',
      initiativeName: 'LLM Inference Cost & Cluster Orchestration',
      category: 'AI Infrastructure',
      chiefSoftwareEngineerRaci: 'A',
      vpInfrastructureRaci: 'R',
      headSecOpsRaci: 'C',
      leadDataScientistRaci: 'R',
      finOpsDirectorRaci: 'C',
      headComplianceRaci: 'I',
      hasExecutiveSignoff: true,
    },
    {
      id: 'raci-zero-trust',
      initiativeName: 'Global Zero-Trust Microsegmentation',
      category: 'Enterprise Security',
      chiefSoftwareEngineerRaci: 'A',
      vpInfrastructureRaci: 'R',
      headSecOpsRaci: 'R',
      leadDataScientistRaci: 'I',
      finOpsDirectorRaci: 'I',
      headComplianceRaci: 'C',
      hasExecutiveSignoff: true,
    },
    {
      id: 'raci-dr-drill',
      initiativeName: 'Hybrid Multi-Cloud DR Failover Drills',
      category: 'Site Reliability',
      chiefSoftwareEngineerRaci: 'A',
      vpInfrastructureRaci: 'R',
      headSecOpsRaci: 'C',
      leadDataScientistRaci: 'I',
      finOpsDirectorRaci: 'I',
      headComplianceRaci: 'C',
      hasExecutiveSignoff: true,
    },
    {
      id: 'raci-finops',
      initiativeName: 'Cloud FinOps Unit Rate Arbitrage',
      category: 'Financial Engineering',
      chiefSoftwareEngineerRaci: 'C',
      vpInfrastructureRaci: 'C',
      headSecOpsRaci: 'I',
      leadDataScientistRaci: 'I',
      finOpsDirectorRaci: 'A',
      headComplianceRaci: 'C',
      hasExecutiveSignoff: true,
    },
    {
      id: 'raci-ai-gov',
      initiativeName: 'EU AI Act Compliance & Merkle Ledger',
      category: 'Regulatory Compliance',
      chiefSoftwareEngineerRaci: 'A',
      vpInfrastructureRaci: 'C',
      headSecOpsRaci: 'C',
      leadDataScientistRaci: 'R',
      finOpsDirectorRaci: 'I',
      headComplianceRaci: 'R',
      hasExecutiveSignoff: true,
    },
  ],
});

// =============================================================================
// 11. SaaS Magic Number Efficiency Gauge Factory
// =============================================================================
export const createSaasMagicNumberEfficiencyGaugeSlide = (id = `slide-${Date.now()}`): SaasMagicNumberEfficiencyGaugeSlideData => ({
  id,
  type: 'saas-magic-number-efficiency-gauge',
  title: 'SaaS Magic Number & Capital Efficiency',
  subtitle: 'Bessemer benchmark evaluation demonstrating top-decile sales velocity, rapid CAC payback, and elite Rule of 40 performance',
  kicker: 'VENTURE & FINANCIAL PERFORMANCE',
  fiscalQuarter: 'Q4 FY2026',
  saasMagicNumber: 1.42,
  cacPaybackMonths: 8.4,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  activeStep: 0,
  maxSteps: 1,
  isPublished: true,
  hasPresenterNotes: true,
  isTopDecilePerformance: true,
  hasHealthyPayback: true,
  isGrowthEfficient: true,
  hasTelemetryGlow: true,
  gauges: [
    {
      id: 'gauge-magic-number',
      metricLabel: 'SaaS Magic Number',
      currentValue: 1.42,
      benchmarkTarget: 1.0,
      unit: 'x',
      efficiencyRating: 'Top Decile',
      isOptimalTier: true,
    },
    {
      id: 'gauge-cac-payback',
      metricLabel: 'CAC Payback Velocity',
      currentValue: 8.4,
      benchmarkTarget: 12.0,
      unit: 'Months',
      efficiencyRating: 'Elite Tier',
      isOptimalTier: true,
    },
    {
      id: 'gauge-nrr',
      metricLabel: 'Net Revenue Retention',
      currentValue: 134.0,
      benchmarkTarget: 120.0,
      unit: '%',
      efficiencyRating: 'Top Decile',
      isOptimalTier: true,
    },
    {
      id: 'gauge-rule-of-40',
      metricLabel: 'Rule of 40 Score',
      currentValue: 58.0,
      benchmarkTarget: 40.0,
      unit: '%',
      efficiencyRating: 'Top Decile',
      isOptimalTier: true,
    },
  ],
});

// =============================================================================
// 12. Supply Chain Geopolitical Chokepoints Factory
// =============================================================================
export const createSupplyChainGeopoliticalChokepointSlide = (id = `slide-${Date.now()}`): SupplyChainGeopoliticalChokepointSlideData => ({
  id,
  type: 'supply-chain-geopolitical-chokepoint',
  title: 'Global Trade Chokepoints & Supply Chain Exposure',
  subtitle: 'Geopolitical maritime bottleneck analysis assessing transit delays, tariff exposures, and semiconductor supply resiliency',
  kicker: 'GLOBAL LOGISTICS & SOVEREIGN RISK',
  operationalYear: '2026-2027',
  totalVulnerabilityScore: 42.0,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  activeStep: 0,
  maxSteps: 1,
  isPublished: true,
  hasPresenterNotes: true,
  isDisrupted: false,
  hasContinuousAudit: true,
  hasTelemetryGlow: true,
  chokepointNodes: [
    {
      id: 'choke-malacca',
      chokepointName: 'Malacca Strait',
      globalTradeSharePercentage: 32.0,
      delayVarianceDays: 3.2,
      vulnerabilityIndexScore: 68.0,
      isAlternativeRouteAvailable: true,
      hasVulnerabilityAlert: false,
    },
    {
      id: 'choke-suez',
      chokepointName: 'Suez Canal / Red Sea',
      globalTradeSharePercentage: 12.0,
      delayVarianceDays: 14.0,
      vulnerabilityIndexScore: 78.0,
      isAlternativeRouteAvailable: true,
      hasVulnerabilityAlert: true,
    },
    {
      id: 'choke-panama',
      chokepointName: 'Panama Canal',
      globalTradeSharePercentage: 5.0,
      delayVarianceDays: 6.5,
      vulnerabilityIndexScore: 45.0,
      isAlternativeRouteAvailable: true,
      hasVulnerabilityAlert: false,
    },
    {
      id: 'choke-taiwan',
      chokepointName: 'Taiwan Strait Semiconductor Corridor',
      globalTradeSharePercentage: 65.0,
      delayVarianceDays: 2.1,
      vulnerabilityIndexScore: 84.0,
      isAlternativeRouteAvailable: false,
      hasVulnerabilityAlert: true,
    },
  ],
});

// =============================================================================
// 13. Product-Market Fit Cohort Triangles Factory
// =============================================================================
export const createProductMarketFitCohortTrianglesSlide = (id = `slide-${Date.now()}`): ProductMarketFitCohortTrianglesSlideData => ({
  id,
  type: 'product-market-fit-cohort-triangles',
  title: 'Product-Market Fit Cohort Retention Triangles',
  subtitle: 'Longitudinal cohort analysis demonstrating steep initial engagement and a rock-solid 70% asymptotic retention curve',
  kicker: 'VENTURE CAPITAL PMF ANALYSIS',
  productName: 'Enterprise Cloud AI Platform',
  asymptoticRetentionRate: 70.4,
  quickRatio: 4.2,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  activeStep: 0,
  maxSteps: 1,
  isPublished: true,
  hasPresenterNotes: true,
  hasFlattenedRetentionCurve: true,
  isProductMarketFitAchieved: true,
  hasNetNegativeChurn: true,
  hasTelemetryGlow: true,
  cohortRows: [
    {
      id: 'cohort-jan',
      cohortLabel: 'Jan 2026 Cohort',
      userCount: 1200,
      month0RetentionPercent: 100.0,
      month1RetentionPercent: 84.2,
      month3RetentionPercent: 76.5,
      month6RetentionPercent: 71.0,
      month12RetentionPercent: 70.4,
      isAsymptoteFlattened: true,
    },
    {
      id: 'cohort-feb',
      cohortLabel: 'Feb 2026 Cohort',
      userCount: 1450,
      month0RetentionPercent: 100.0,
      month1RetentionPercent: 85.0,
      month3RetentionPercent: 77.8,
      month6RetentionPercent: 72.1,
      month12RetentionPercent: 71.8,
      isAsymptoteFlattened: true,
    },
    {
      id: 'cohort-mar',
      cohortLabel: 'Mar 2026 Cohort',
      userCount: 1820,
      month0RetentionPercent: 100.0,
      month1RetentionPercent: 87.4,
      month3RetentionPercent: 79.2,
      month6RetentionPercent: 73.0,
      month12RetentionPercent: 72.5,
      isAsymptoteFlattened: true,
    },
  ],
});

// =============================================================================
// 14. Developer Productivity SPACE Framework Factory
// =============================================================================
export const createDeveloperProductivitySpaceFrameworkSlide = (id = `slide-${Date.now()}`): DeveloperProductivitySpaceFrameworkSlideData => ({
  id,
  type: 'developer-productivity-space-framework',
  title: 'Developer Productivity SPACE Framework',
  subtitle: 'Multidimensional engineering velocity analysis covering satisfaction, performance, activity, collaboration, and flow efficiency',
  kicker: 'ENGINEERING HEALTH & DORA METRICS',
  engineeringOrgName: 'Core Platform Engineering',
  overallHealthScore: 94.2,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  activeStep: 0,
  maxSteps: 1,
  isPublished: true,
  hasPresenterNotes: true,
  isDoraEliteTier: true,
  hasDeepWorkProtected: true,
  hasHealthyVelocity: true,
  hasTelemetryGlow: true,
  dimensions: [
    {
      id: 'space-s',
      dimensionCode: 'S',
      dimensionTitle: 'Satisfaction & Well-Being',
      primaryMetric: 'Developer Happiness Index: 88%',
      metricScore: 88.0,
      benchmarkPercentile: 92.0,
      isEliteTier: true,
    },
    {
      id: 'space-p',
      dimensionCode: 'P',
      dimensionTitle: 'Performance & Quality',
      primaryMetric: 'Code Review Quality Score: 94%',
      metricScore: 94.0,
      benchmarkPercentile: 96.0,
      isEliteTier: true,
    },
    {
      id: 'space-a',
      dimensionCode: 'A',
      dimensionTitle: 'Activity & Delivery',
      primaryMetric: 'Deploy Frequency: 42 deploys/day',
      metricScore: 92.0,
      benchmarkPercentile: 95.0,
      isEliteTier: true,
    },
    {
      id: 'space-c',
      dimensionCode: 'C',
      dimensionTitle: 'Communication & Collaboration',
      primaryMetric: 'Median PR Review Time: 18 minutes',
      metricScore: 96.0,
      benchmarkPercentile: 98.0,
      isEliteTier: true,
    },
    {
      id: 'space-e',
      dimensionCode: 'E',
      dimensionTitle: 'Efficiency & Deep Flow',
      primaryMetric: 'Uninterrupted Deep Work: 4.8h/day',
      metricScore: 91.0,
      benchmarkPercentile: 94.0,
      isEliteTier: true,
    },
  ],
});

// =============================================================================
// 15. Customer Health Scorecard Matrix Factory
// =============================================================================
export const createCustomerHealthScorecardMatrixSlide = (id = `slide-${Date.now()}`): CustomerHealthScorecardMatrixSlideData => ({
  id,
  type: 'customer-health-scorecard-matrix',
  title: 'Enterprise Customer Health Scorecard',
  subtitle: 'Multidimensional health audit across Tier-1 strategic enterprise accounts measuring telemetry adoption and renewal certainty',
  kicker: 'EXECUTIVE CUSTOMER SUCCESS',
  reportingQuarter: 'Q4 FY2026',
  portfolioRetentionRatePercent: 98.4,
  leadArchitect: 'Alim Ul Karim',
  leadRole: 'Chief Software Engineer',
  activeStep: 0,
  maxSteps: 1,
  isPublished: true,
  hasPresenterNotes: true,
  hasLowSupportEscalations: true,
  hasContinuousAudit: true,
  hasTelemetryGlow: true,
  accounts: [
    {
      id: 'acct-apex',
      accountName: 'Apex Financial Group',
      annualRecurringRevenueUsd: 1800000,
      featureAdoptionRatePercent: 94.5,
      executiveAlignmentTier: 'Strong',
      openEscalationCount: 0,
      npsSentimentScore: 78,
      isContractRenewalSecured: true,
      hasExecutiveSponsorAligned: true,
    },
    {
      id: 'acct-nova',
      accountName: 'Nova BioHealth Labs',
      annualRecurringRevenueUsd: 1450000,
      featureAdoptionRatePercent: 91.2,
      executiveAlignmentTier: 'Strong',
      openEscalationCount: 1,
      npsSentimentScore: 72,
      isContractRenewalSecured: true,
      hasExecutiveSponsorAligned: true,
    },
    {
      id: 'acct-aerospace',
      accountName: 'Global Aerospace Systems',
      annualRecurringRevenueUsd: 1200000,
      featureAdoptionRatePercent: 88.0,
      executiveAlignmentTier: 'Moderate',
      openEscalationCount: 0,
      npsSentimentScore: 65,
      isContractRenewalSecured: true,
      hasExecutiveSponsorAligned: true,
    },
    {
      id: 'acct-meridian',
      accountName: 'Meridian Global Retail',
      annualRecurringRevenueUsd: 950000,
      featureAdoptionRatePercent: 96.4,
      executiveAlignmentTier: 'Strong',
      openEscalationCount: 0,
      npsSentimentScore: 84,
      isContractRenewalSecured: true,
      hasExecutiveSponsorAligned: true,
    },
  ],
});

// =============================================================================
// Suite 2027 Factory Registry Map
// =============================================================================
export const SUITE_2027_FACTORIES: Record<string, (id?: string) => SlideData> = {
  'ai-inference-cost-token-waterfall': createAiInferenceCostTokenWaterfallSlide,
  'cross-functional-raci-matrix': createCrossFunctionalRaciMatrixSlide,
  'zero-trust-microsegmentation-map': createZeroTrustMicrosegmentationMapSlide,
  'saas-magic-number-efficiency-gauge': createSaasMagicNumberEfficiencyGaugeSlide,
  'supply-chain-geopolitical-chokepoint': createSupplyChainGeopoliticalChokepointSlide,
  'incident-sev1-command-timeline': createIncidentSev1CommandTimelineSlide,
  'cloud-finops-unit-rate-optimization': createCloudFinopsUnitRateOptimizationSlide,
  'product-market-fit-cohort-triangles': createProductMarketFitCohortTrianglesSlide,
  'enterprise-ai-governance-guardrails': createEnterpriseAiGovernanceGuardrailsSlide,
  'data-lakehouse-medallion-pipeline': createDataLakehouseMedallionPipelineSlide,
  'merger-acquisition-synergy-bridge': createMergerAcquisitionSynergyBridgeSlide,
  'developer-productivity-space-framework': createDeveloperProductivitySpaceFrameworkSlide,
  'hybrid-cloud-dr-failover-topology': createHybridCloudDrFailoverTopologySlide,
  'customer-health-scorecard-matrix': createCustomerHealthScorecardMatrixSlide,
  'value-stream-bottleneck-flow': createValueStreamBottleneckFlowSlide,
};

// Generic Factory
export const createSuite2027Slide = (
  type: Suite2027SlideType | string,
  id = `slide-${Date.now()}`
): Suite2027SlideData => {
  const factory = SUITE_2027_FACTORIES[type];
  return factory ? (factory(id) as Suite2027SlideData) : createAiInferenceCostTokenWaterfallSlide(id);
};

// =============================================================================
// Archetype Options Catalog for Suite 2027
// =============================================================================
export const SUITE_2027_ARCHETYPE_OPTIONS: ArchetypeOption[] = [
  {
    type: 'ai-inference-cost-token-waterfall',
    label: 'AI Inference Cost Token Waterfall',
    category: 'Strategy & Metrics',
    desc: 'LLM token economics waterfall tracking prompt context, KV cache, speculative decoding, and unit margin',
    icon: 'Cpu',
  },
  {
    type: 'cross-functional-raci-matrix',
    label: 'Cross-Functional RACI Matrix',
    category: 'Corporate Strategy',
    desc: 'Executive initiative governance matrix assigning Responsible, Accountable, Consulted, and Informed roles',
    icon: 'Grid',
  },
  {
    type: 'zero-trust-microsegmentation-map',
    label: 'Zero-Trust Microsegmentation Map',
    category: 'Platform & Network',
    desc: 'Workload microsegmentation and eBPF packet inspection topology with automated threat quarantine',
    icon: 'Shield',
  },
  {
    type: 'saas-magic-number-efficiency-gauge',
    label: 'SaaS Magic Number Efficiency Gauge',
    category: 'Strategy & Metrics',
    desc: 'Bessemer capital efficiency dials visualizing SaaS Magic Number, CAC payback, and Rule of 40 performance',
    icon: 'Gauge',
  },
  {
    type: 'supply-chain-geopolitical-chokepoint',
    label: 'Supply Chain Geopolitical Chokepoints',
    category: 'Corporate Strategy',
    desc: 'Global maritime trade choke analysis measuring semiconductor supply disruption and alternate routings',
    icon: 'Globe',
  },
  {
    type: 'incident-sev1-command-timeline',
    label: 'Incident SEV-1 Command Timeline',
    category: 'Platform & Network',
    desc: 'Mission-critical incident response sequence with blast radius triage, AST rollback, and MTTR compliance',
    icon: 'Activity',
  },
  {
    type: 'cloud-finops-unit-rate-optimization',
    label: 'Cloud FinOps Unit Rate Optimization',
    category: 'Strategy & Metrics',
    desc: 'Multi-cloud unit rate cost bridge identifying idle workloads, spot arbitrage, and annualized savings',
    icon: 'TrendingUp',
  },
  {
    type: 'product-market-fit-cohort-triangles',
    label: 'PMF Cohort Retention Triangles',
    category: 'Strategy & Metrics',
    desc: 'Longitudinal user retention triangle proving asymptotic plateauing and net negative churn',
    icon: 'Layers',
  },
  {
    type: 'enterprise-ai-governance-guardrails',
    label: 'Enterprise AI Governance Guardrails',
    category: 'Platform & Network',
    desc: 'Four-stage AI compliance pipeline enforcing prompt shielding, factuality gates, and Merkle audit ledgers',
    icon: 'Lock',
  },
  {
    type: 'data-lakehouse-medallion-pipeline',
    label: 'Data Lakehouse Medallion Pipeline',
    category: 'Product & Architecture',
    desc: 'Streaming Bronze-to-Gold Iceberg data refinery with automated schema evolution and sub-second serving',
    icon: 'Database',
  },
  {
    type: 'merger-acquisition-synergy-bridge',
    label: 'M&A Synergy Realization Bridge',
    category: 'Corporate Strategy',
    desc: 'Post-merger value accretion waterfall stepping from baseline EBITDA to full cross-sell enterprise valuation',
    icon: 'Shuffle',
  },
  {
    type: 'developer-productivity-space-framework',
    label: 'Developer Productivity SPACE Framework',
    category: 'Team & Credibility',
    desc: 'Multidimensional engineering health framework assessing satisfaction, performance, activity, and flow',
    icon: 'Users',
  },
  {
    type: 'hybrid-cloud-dr-failover-topology',
    label: 'Hybrid Cloud DR Failover Topology',
    category: 'Platform & Network',
    desc: 'Automated disaster recovery regional swing with Anycast DNS routing and zero-data-loss replica promotion',
    icon: 'RefreshCw',
  },
  {
    type: 'customer-health-scorecard-matrix',
    label: 'Customer Health Scorecard Matrix',
    category: 'Story & Conversion',
    desc: 'Tier-1 enterprise account health scorecard tracking feature adoption, executive alignment, and renewal ARR',
    icon: 'Smile',
  },
  {
    type: 'value-stream-bottleneck-flow',
    label: 'Value Stream Bottleneck Flow',
    category: 'Product & Architecture',
    desc: 'Software delivery value stream mapping identifying CI/CD delays, queue wait times, and flow efficiency',
    icon: 'GitPullRequest',
  },
];
