import React from 'react';
import type { SlideData } from '../../types/presentation';
import { ThreeHorizonsStrategySlide } from './nextgen/ThreeHorizonsStrategySlide';
import { AiAgentFleetTopologySlide } from './nextgen/AiAgentFleetTopologySlide';
import { ApiRateLimitGatewaySlide } from './nextgen/ApiRateLimitGatewaySlide';
import { MultiCloudDrFailoverSlide } from './nextgen/MultiCloudDrFailoverSlide';
import { FintechPaymentClearingSlide } from './nextgen/FintechPaymentClearingSlide';
import { EsgDecarbonizationRoadmapSlide } from './nextgen/EsgDecarbonizationRoadmapSlide';
import { ModelContextProtocolMeshSlide } from './nextgen/ModelContextProtocolMeshSlide';
import { DataCleanRoomSlide } from './nextgen/DataCleanRoomSlide';
import { DeveloperPlatformIdpSlide } from './nextgen/DeveloperPlatformIdpSlide';
import { ExecutiveMaSynergySlide } from './nextgen/ExecutiveMaSynergySlide';
import { CyberThreatKillChainSlide } from './nextgen/CyberThreatKillChainSlide';
import { SupplyChainDigitalTwinSlide } from './nextgen/SupplyChainDigitalTwinSlide';
import { VoiceAiConversationalMeshSlide } from './nextgen/VoiceAiConversationalMeshSlide';
import { ComplianceSoc2ReadinessLadderSlide } from './nextgen/ComplianceSoc2ReadinessLadderSlide';
import { ValueStreamDoraFlywheelSlide } from './nextgen/ValueStreamDoraFlywheelSlide';
import { ExecutiveStorytellingHookSlide } from './nextgen/corporate/ExecutiveStorytellingHookSlide';
import { LeadershipSynergyDuoSlide } from './nextgen/corporate/LeadershipSynergyDuoSlide';
import { OperationalWorkCultureSlide } from './nextgen/corporate/OperationalWorkCultureSlide';
import { BentoCapabilitiesMatrixSlide } from './nextgen/corporate/BentoCapabilitiesMatrixSlide';
import { OpportunityCostWaterfallSlide } from './nextgen/corporate/OpportunityCostWaterfallSlide';
import { BenchmarkRegionalPricingSlide } from './nextgen/commercial/BenchmarkRegionalPricingSlide';
import { SprintOnboardingRoadmapSlide } from './nextgen/commercial/SprintOnboardingRoadmapSlide';
import { SimulatedBrowserShowcaseSlide } from './nextgen/commercial/SimulatedBrowserShowcaseSlide';
import { ClientTestimonialWallSlide } from './nextgen/commercial/ClientTestimonialWallSlide';
import { GlobalEdgeMeshSlide } from './nextgen/commercial/GlobalEdgeMeshSlide';
import { AiGovernanceSafetyGovernorSlide } from './nextgen/techgov/AiGovernanceSafetyGovernorSlide';
import { DeveloperVelocityFlywheelSlide } from './nextgen/techgov/DeveloperVelocityFlywheelSlide';
import { StrategicDecarbonizationEsgSlide } from './nextgen/techgov/StrategicDecarbonizationEsgSlide';
import { MarketTensionQuadrantSlide } from './nextgen/techgov/MarketTensionQuadrantSlide';
import { ExecutiveCloseContactSlide } from './nextgen/techgov/ExecutiveCloseContactSlide';
import { WhiteMasterSlide } from './WhiteMasterSlide';
import { ModernSlideRenderer } from './ModernSlideRenderer';

export const NextGenSlideRenderer: React.FC<{ slide: SlideData }> = ({ slide }) => {
  switch (slide.type) {
    case 'three-horizons-strategy-matrix': return <ThreeHorizonsStrategySlide slide={slide as any} />;
    case 'ai-agent-fleet-topology': return <AiAgentFleetTopologySlide slide={slide as any} />;
    case 'api-rate-limit-gateway': return <ApiRateLimitGatewaySlide slide={slide as any} />;
    case 'multi-cloud-dr-failover-mesh': return <MultiCloudDrFailoverSlide slide={slide as any} />;
    case 'fintech-payment-clearing-engine': return <FintechPaymentClearingSlide slide={slide as any} />;
    case 'esg-decarbonization-roadmap': return <EsgDecarbonizationRoadmapSlide slide={slide as any} />;
    case 'model-context-protocol-mesh': return <ModelContextProtocolMeshSlide slide={slide as any} />;
    case 'data-clean-room-collaboration': return <DataCleanRoomSlide slide={slide as any} />;
    case 'developer-platform-idp-hub': return <DeveloperPlatformIdpSlide slide={slide as any} />;
    case 'executive-mergers-acquisitions-synergy': return <ExecutiveMaSynergySlide slide={slide as any} />;
    case 'cyber-threat-kill-chain-matrix': return <CyberThreatKillChainSlide slide={slide as any} />;
    case 'supply-chain-digital-twin-lattice': return <SupplyChainDigitalTwinSlide slide={slide as any} />;
    case 'voice-ai-realtime-conversational-mesh': return <VoiceAiConversationalMeshSlide slide={slide as any} />;
    case 'compliance-audit-soc2-readiness-ladder': return <ComplianceSoc2ReadinessLadderSlide slide={slide as any} />;
    case 'value-stream-engineering-dora-flywheel': return <ValueStreamDoraFlywheelSlide slide={slide as any} />;
    case 'executive-storytelling-hook': return <ExecutiveStorytellingHookSlide slide={slide as any} />;
    case 'leadership-synergy-duo': return <LeadershipSynergyDuoSlide slide={slide as any} />;
    case 'operational-work-culture': return <OperationalWorkCultureSlide slide={slide as any} />;
    case 'bento-capabilities-matrix': return <BentoCapabilitiesMatrixSlide slide={slide as any} />;
    case 'opportunity-cost-waterfall': return <OpportunityCostWaterfallSlide slide={slide as any} />;
    case 'benchmark-regional-pricing': return <BenchmarkRegionalPricingSlide slide={slide as any} />;
    case 'sprint-onboarding-roadmap': return <SprintOnboardingRoadmapSlide slide={slide as any} />;
    case 'simulated-browser-showcase': return <SimulatedBrowserShowcaseSlide slide={slide as any} />;
    case 'client-testimonial-wall': return <ClientTestimonialWallSlide slide={slide as any} />;
    case 'global-edge-mesh': return <GlobalEdgeMeshSlide slide={slide as any} />;
    case 'ai-governance-safety-governor': return <AiGovernanceSafetyGovernorSlide slide={slide as any} />;
    case 'developer-velocity-flywheel': return <DeveloperVelocityFlywheelSlide slide={slide as any} />;
    case 'strategic-decarbonization-esg': return <StrategicDecarbonizationEsgSlide slide={slide as any} />;
    case 'market-tension-quadrant': return <MarketTensionQuadrantSlide slide={slide as any} />;
    case 'executive-close-contact': return <ExecutiveCloseContactSlide slide={slide as any} />;
    default: return <ModernSlideRenderer slide={slide} />;
  }
};
