import React from 'react';
import { SlideData } from '../../types/presentation';
import { WhiteMasterSlide } from './WhiteMasterSlide';
import { TitleSlide } from './TitleSlide';
import { CeoPersonaSlide } from './CeoPersonaSlide';
import { BeforeAfterSlide } from './BeforeAfterSlide';
import { TalentFunnelSlide } from './TalentFunnelSlide';
import { PricingProofSlide } from './PricingProofSlide';
import { KeyPlayerSlide } from './KeyPlayerSlide';
import { StepsChainSlide } from './StepsChainSlide';
import { TestimonialsSlide } from './TestimonialsSlide';
import { CompetitiveEdgeSlide } from './CompetitiveEdgeSlide';
import { TechStackSlide } from './TechStackSlide';
import { StepsSlide } from './StepsSlide';
import { MetricGridSlide } from './MetricGridSlide';
import { ProblemSolutionSlide } from './ProblemSolutionSlide';
import { QuadrantMatrixSlide } from './QuadrantMatrixSlide';
import { MarketOpportunitySlide } from './MarketOpportunitySlide';
import { TimelineRoadmapSlide } from './TimelineRoadmapSlide';
import { FeatureGridSlide } from './FeatureGridSlide';
import { ArchitectureDiagramSlide } from './ArchitectureDiagramSlide';
import { QuoteCalloutSlide } from './QuoteCalloutSlide';
import { StatsCalloutSlide } from './StatsCalloutSlide';
import { TeamGridSlide } from './TeamGridSlide';
import { CaseStudySlide } from './CaseStudySlide';
import { ComparisonColumnsSlide } from './ComparisonColumnsSlide';
import { ProcessCycleSlide } from './ProcessCycleSlide';
import { CodeTerminalSlide } from './CodeTerminalSlide';
import { CallToActionSlide } from './CallToActionSlide';
import { GrowthEngineSlide } from './GrowthEngineSlide';
import { TalentPyramidSlide } from './TalentPyramidSlide';
import { CostComparisonSlide } from './CostComparisonSlide';
import { DepthStackSlide } from './DepthStackSlide';
import { RevealGridSlide } from './RevealGridSlide';
import { BeforeAfterShowcaseSlide } from './BeforeAfterShowcaseSlide';
import { DailyWorkCultureSlide } from './DailyWorkCultureSlide';
import { OurWorkShowcaseSlide } from './OurWorkShowcaseSlide';
import { ExecutiveDuoSlide } from './ExecutiveDuoSlide';
import { AfterSalesSupportSlide } from './AfterSalesSupportSlide';
import { SearchSerpProofSlide } from './SearchSerpProofSlide';
import { ContentCalendarSlide } from './ContentCalendarSlide';
import { MindsetShiftSlide } from './MindsetShiftSlide';
import { SessionOutlineSlide } from './SessionOutlineSlide';
import { CounterStatSlide } from './CounterStatSlide';
import { PollSurveySlide } from './PollSurveySlide';
import { TypewriterPromptSlide } from './TypewriterPromptSlide';
import { ExpandedSlideRenderer } from './ExpandedSlideRenderer';

export const SlideRenderer: React.FC<{ slide: SlideData }> = ({ slide }) => {
  switch (slide.type) {
    case 'white-master': return <WhiteMasterSlide slide={slide} />;
    case 'title': return <TitleSlide slide={slide} />;
    case 'persona': return <CeoPersonaSlide slide={slide} />;
    case 'key-player': return <KeyPlayerSlide slide={slide} />;
    case 'before-after': return <BeforeAfterSlide slide={slide} />;
    case 'talent-funnel': return <TalentFunnelSlide slide={slide} />;
    case 'pricing': return <PricingProofSlide slide={slide} />;
    case 'steps-chain': return <StepsChainSlide slide={slide} />;
    case 'testimonials': return <TestimonialsSlide slide={slide} />;
    case 'competitive-edge': return <CompetitiveEdgeSlide slide={slide} />;
    case 'tech-stack': return <TechStackSlide slide={slide} />;
    case 'steps': return <StepsSlide slide={slide as any} />;
    case 'metric-grid': return <MetricGridSlide slide={slide as any} />;
    case 'problem-solution': return <ProblemSolutionSlide slide={slide as any} />;
    case 'quadrant-matrix': return <QuadrantMatrixSlide slide={slide as any} />;
    case 'market-opportunity': return <MarketOpportunitySlide slide={slide as any} />;
    case 'timeline-roadmap': return <TimelineRoadmapSlide slide={slide as any} />;
    case 'feature-grid': return <FeatureGridSlide slide={slide as any} />;
    case 'architecture-diagram': return <ArchitectureDiagramSlide slide={slide as any} />;
    case 'quote-callout': return <QuoteCalloutSlide slide={slide as any} />;
    case 'stats-callout': return <StatsCalloutSlide slide={slide as any} />;
    case 'team-grid': return <TeamGridSlide slide={slide as any} />;
    case 'case-study': return <CaseStudySlide slide={slide as any} />;
    case 'comparison-columns': return <ComparisonColumnsSlide slide={slide as any} />;
    case 'process-cycle': return <ProcessCycleSlide slide={slide as any} />;
    case 'code-terminal': return <CodeTerminalSlide slide={slide as any} />;
    case 'call-to-action': return <CallToActionSlide slide={slide as any} />;
    case 'growth-engine': return <GrowthEngineSlide slide={slide as any} />;
    case 'talent-pyramid': return <TalentPyramidSlide slide={slide as any} />;
    case 'cost-comparison': return <CostComparisonSlide slide={slide as any} />;
    case 'daily-work-culture': return <DailyWorkCultureSlide slide={slide as any} />;
    case 'our-work-showcase': return <OurWorkShowcaseSlide slide={slide as any} />;
    case 'executive-duo': return <ExecutiveDuoSlide slide={slide as any} />;
    case 'after-sales-support': return <AfterSalesSupportSlide slide={slide as any} />;
    case 'search-serp-proof': return <SearchSerpProofSlide slide={slide as any} />;
    case 'content-calendar': return <ContentCalendarSlide slide={slide as any} />;
    case 'mindset-shift': return <MindsetShiftSlide slide={slide as any} />;
    case 'session-outline': return <SessionOutlineSlide slide={slide as any} />;
    case 'reveal-grid': return <RevealGridSlide slide={slide as any} />;
    case 'counter-stat': return <CounterStatSlide slide={slide as any} />;
    case 'poll-survey': return <PollSurveySlide slide={slide as any} />;
    case 'typewriter-prompt': return <TypewriterPromptSlide slide={slide as any} />;
    case 'depth-stack': return <DepthStackSlide slide={slide as any} />;
    case 'before-after-showcase' as any: return <BeforeAfterShowcaseSlide slide={slide as any} />;
    default: return <ExpandedSlideRenderer slide={slide} />;
  }
};
